<?php
    $usuario = $this->usuario;
    $rolUsr = $this->rolUsuario;
    $roles = $this->roles;
    
    //print_r($usuario);
    
    $urlUsr = $this->url(array('controller'=>'usuario','action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Editando rol de usuario: <strong><?php echo $usuario['nickname'] ?></strong></h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlUsr; ?>">
						<i class="fa fa-chevron-left"></i> Regresar a Usuarios.
					</a>
				</div>
				<hr />
				<div>
					<form class="form-horizontal">
						<div class="form-group">
							<label for="rol" class="control-label col-md-2">Rol Usuario:</label>
							<div class="col-md-5">
								<label class="control-label"><strong><?php echo $rolUsr['rol']; ?></strong></label>
							</div>
						</div>
						
						<div class="form-group">
							<label for="rol" class="control-label col-md-2">Roles:</label>
							<div class="col-md-5">
								<select class="form-control">
									<?php foreach ($roles as $rol): ?>
									<option value="<?php echo $rol['idRol'] ?>"><?php echo $rol['rol'] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-success" type="submit">
									<i class="fa fa-refresh"></i> Actualizar Rol
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>