<?php
    $conjunto = $this->conjunto;
    $conjuntos = $this->conjuntos;
?>
<div class="row">
	<div class="col-md-12">
	    <div class="panel panel-success">
            <div class="panel-heading">
                <h5 class="panel-title">Conjunto: <strong><?php echo $conjunto["nombre"] ?></strong> </h5>
            </div>
            <div class="panel-body">
                
            </div>
        </div>
	</div>
	<?php if($conjunto["conjuntoAnterior"] == "0" || $conjunto["conjuntoSiguiente"] == "0"){ ?>
	<div class="col-md-12">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h5 class="panel-title">Editar Conjunto: <strong><?php echo $conjunto["nombre"] ?></strong> </h5>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Conjunto Anterior:</label>
                        <div class="col-md-10">
                            <select name="anterior" class="form-control">
                                <option value="0">Este es el primer conjunto</option>
                                <?php foreach ($conjuntos as $con) : ?>
                                <option value="<?php echo $con["idConjuntoEvaluador"] ?>"><?php echo $con["nombre"] ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="" class="col-md-2 control-label">Conjunto Siguiente: </label>
                        <div class="col-md-10">
                            <select name="siguiente" class="form-control">
                                <option value="0">Este es el último conjunto</option>
                                <?php foreach ($conjuntos as $con) : ?>
                                <option value="<?php echo $con["idConjuntoEvaluador"] ?>"><?php echo $con["nombre"] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-send"></i> Actualizar Conjunto
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
	<?php } ?>
</div>