<?php
	
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-title">
				Agregar Evaluador en Conjunto
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<div class="form-group">
							<label for="" class="control-label col-xs-2"></label>
							<div class="col-xs-10">
								<input id="evaluador" name="evaluador" type="text" class="form-control" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
