<?php
	$formulario = $this->formulario;
	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
	$urlConjuntos = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"index"),null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Nuevo Conjunto de Evaluacion</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlConjuntos ?>">
						<i class="fa fa-arrow-circle-left"></i> Regresar a Conjuntos
					</a>
					<?php if(!is_null($messageSuccess)){ ?>
	                <br /><br />
	                <div class="alert alert-success" role="alert">
	                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	                      <span aria-hidden="true">&times;</span>
	                    </button>
	                    <?php echo $messageSuccess; ?>
	                </div>
	                <?php }elseif(!is_null($messageFail)){ ?>
	                <div class="alert alert-danger" role="alert">
	                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	                      <span aria-hidden="true">&times;</span>
	                    </button>
	                    <?php echo $messageFail; ?>
	                </div>
	                <?php } ?>
				</div>
				<hr />
				<div>
					<?php echo $formulario; ?>
				</div>
			</div>
		</div>
	</div>
</div>