<?php 
	$conjunto = $this->conjunto;
    //print_r($conjunto);
	$encuestas = $this->encuestas;
    $evaluaciones = $this->evaluaciones;
	//$asignacionesDisponibles = $this->asignacionesDisponibles;
    $asignacionesGrupo = $this->asignacionesGrupo;
    $asignacionesDisponibles = $asignacionesGrupo;
	$asignacionesConjunto = $this->asignacionesConjunto;
	$urlGrupoConjunto = $this->url(array('module'=>'encuesta','controller'=>'conjunto','action'=>'conjuntos','gpo'=>$conjunto['idGrupoEscolar']),null,true);
	
	$urlConjuntos = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"index"),null,true);
	$urlAltaEvaluacion = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"agregareval","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,true);
	$urlAltaAsignacion = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"agregarasign","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,true);
    
	$valorId = 0;
	if ($conjunto['idConjuntoAnterior'] == 0) {
	    $valorId = $conjunto['idConjuntoEvaluador'];
	}else{
	    $valorId = $conjunto['idConjuntoAnterior'];
	}
	$params = array("module"=>"encuesta","controller"=>"conjunto","action"=>"asignaciones","co"=>$valorId);
	$urlPreviousConjunto = $this->url($params,null,true);
	
	$valorId = 0;
	if ($conjunto['idConjuntoSiguiente'] == 0) {
	    $valorId = $conjunto['idConjuntoEvaluador'];
	}else{
	    $valorId = $conjunto['idConjuntoSiguiente'];
	}
	$params = array("module"=>"encuesta","controller"=>"conjunto","action"=>"asignaciones","co"=>$valorId);
    $urlNextConjunto = $this->url($params,null,true);
    $urlGrupo = $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"index","gpo"=>$conjunto["idGrupoEscolar"],),null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Asociar Asignaciones a Conjunto <strong><?php echo $conjunto["conjunto"] ?></strong></h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-link" href="<?php echo $urlGrupoConjunto; ?>">
						<i class="fa fa-cubes"></i> Regresar a Grupo
					</a>
					<a class="btn btn-link" href="<?php echo $urlPreviousConjunto; ?>">
                        <i class="fa fa-arrow-circle-o-left"></i> Anterior Conjunto
                    </a>
					<a target="_blank" class="btn btn-link" href="<?php echo $urlGrupo; ?>">
					    <i class="fa fa-external-link-square"></i> Ir al Grupo
					</a>
					<a class="btn btn-link" href="<?php echo $urlNextConjunto; ?>">
                        <i class="fa fa-arrow-circle-o-right"></i> Siguiente Conjunto
                    </a>
				</div>
				<hr />
				<div>
					<div class="form-horizontal" >
					    <div class="form-group">
                            <label for="idEvaluacion" class="col-xs-2 control-label">Evaluaciones Disponibles</label>
                            <div class="col-xs-10">
                                <select id="idEvaluacion" class="form-control" name="idEvaluacion">
                                    <?php foreach ($evaluaciones as $evaluacion) : ?>
                                    <option value="<?php echo $evaluacion["idEncuesta"]; ?>"><?php echo $evaluacion["nombre"]; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
						<div class="form-group">
							<label for="idAsignacion" class="col-xs-2 control-label">Asignaciones Disponibles</label>
							<div class="col-xs-10">
								<select id="idAsignacion" class="form-control" name="idAsignacion">
									<?php foreach ($asignacionesDisponibles as $asignacionDisponible) : 
										$relacion = $asignacionDisponible["materia"]["materiaEscolar"]." - " .$asignacionDisponible["docente"]["apellidos"].", ".$asignacionDisponible["docente"]["nombres"];
										?>
									<option value="<?php echo $asignacionDisponible["asignacion"]["idAsignacionGrupo"]; ?>"><?php echo $relacion; ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-offset-2 col-xs-10">
								<button id="btnSubmit" class="btn btn-success" type="button">
									<i class="fa fa-plus-circle"></i> Asociar Asignacion.
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Asignaciones del Conjunto <strong><?php echo $conjunto["conjunto"] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Materia</th>
								<th>Docente</th>
								<th>Evaluacion</th>
								<th>Modificar</th>
								<th>Eliminar</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($asignacionesConjunto as $asignacion): 
							    $paramsMod = array(
                                    "module" => "encuesta",
                                    "controller" => "conjunto",
                                    "action" => "editasign",
                                    "co" => $conjunto["idConjuntoEvaluador"],
                                    "as" => $asignacion["idAsignacion"],
                                    "ev" => $asignacion["evaluacion"]['idEncuesta']
                                );
                                
                                $urlMod = $this->url($paramsMod,null,true);
                                
                                $paramsMod["action"] = "delasign";
                                
                                $urlDel = $this->url($paramsMod,null,true);
							    ?>
							<tr>
								<td><?php echo $asignacion["materia"]["materiaEscolar"] ?></td>
								<td><?php echo $asignacion["docente"]["apellidos"].", ".$asignacion["docente"]["nombres"] ?></td>
								<td><?php echo $asignacion["evaluacion"]['nombre'] ?></td>
								<td>
								    <a class="btn btn-link" href="<?php echo $urlMod; ?>">
								        <i class="fa fa-pencil"></i> Modificar
								    </a>
								</td>
								<td>
								    <a class="btn btn-link" href="<?php echo $urlDel; ?>">
								        <i class="fa fa-remove"></i> Eliminar
								    </a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    $().ready(function(){
        var appname = "/colegio/encuesta";
        var url = window.location.origin + appname;
        //var idConjunto = $("#idConjuntoEvaluador").attr("value");
        var idConjunto = <?php echo $conjunto['idConjuntoEvaluador']; ?>;
        
        $("#btnSubmit").click(function(){
            var idEvaluacion = $("#idEvaluacion").val();
            var idAsignacion = $("#idAsignacion").val();
            
            console.log("idEvaluacion: " + idEvaluacion);
            console.log("idAsignacion: " + idAsignacion);
            
            var urlRelacion = url + "/conjunto/agregarasign/co/"+idConjunto+"/ev/"+idEvaluacion+"/as/"+idAsignacion;
            console.log("UrlRelacion: "+urlRelacion);
            
            $.ajax({
                url: urlRelacion,
                success: function(data){
                    console.log("Recibido por el server!!")	;
                    //location.reload();
                }
            });
        });
    });
</script>
