<?php 
	$evaluadores = $this->evaluadores;
	$conjunto = $this->conjunto;
	$tiposEvaluador = Zend_Registry::get("tiposEvaluador");
	$dbAdapter = Zend_Registry::get("dbmodquery");
	$evaluacionDAO = new Encuesta_DAO_Evaluacion($dbAdapter);
	$urlAsociarEvaluador = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"agregareval","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,TRUE);
	$urlConjuntos = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"index"),null,TRUE);
    $urlScriptEvaluadores = $this->baseUrl()."/public/js/helpers/searchEvaluadores.js"; 
?>
<div class="row">
	<div class="col-xs-12">
		<div id="searchPanel" class="panel panel-success" conjunto="<?php echo $conjunto["idConjuntoEvaluador"]; ?>">
			<div class="panel-heading">
				<h5 class="panel-title">Agregar Evaluador en Conjunto</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlConjuntos; ?>">
						<i class="fa fa-arrow-circle-left"></i> Regresar a los conjuntos
					</a>
				</div>
				<hr />
				<div>
					<div class="form-horizontal">
						<div class="form-group">
							<label for="evaluador" class="control-label col-xs-2">Evaluador: </label>
							<div class="col-xs-10">
								<input id="evaluador" name="evaluador" type="text" class="form-control" autofocus="" />
							</div>
						</div>
					</div>
				</div>
				<hr />
				<div>
					<table id="evaluadores" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombre</th>
								<th>Apellidos</th>
								<th>Tipo</th>
								<th>Asociar</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Evaluadores del Conjunto: <strong><?php echo $conjunto["nombre"] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombres</th>
								<th>Apellidos</th>
								<th>Tipo</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($evaluadores as $evaluador) : ?>
							<tr>
								<td><?php echo $evaluador["nombres"]; ?></td>
								<td><?php echo $evaluador["apellidos"]; ?></td>
								<td><?php echo $tiposEvaluador[$evaluador["tipo"]]; ?></td>
							</tr>
							<?php endforeach;  ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $urlScriptEvaluadores; ?>"></script>