<?php 
	$evaluadores = $this->evaluadores;
	$conjunto = $this->conjunto;
	$tiposEvaluador = Zend_Registry::get("tiposEvaluador");
	$dbAdapter = Zend_Registry::get("dbmodquery");
	$evaluacionDAO = new Encuesta_DAO_Evaluacion($dbAdapter);
	$urlAsociarEvaluador = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"agregareval","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,TRUE); 
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Agregar Evaluador en Conjunto</h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<div class="form-group">
							<label for="evaluador" class="control-label col-xs-2">Evaluador: </label>
							<div class="col-xs-10">
								<input id="evaluador" name="evaluador" type="text" class="form-control" />
							</div>
						</div>
					</div>
				</div>
				
				<div>
					<table id="evaluadores" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Agregar</th>
								<th>Nombre</th>
								<th>Apellidos</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Evaluadores del Conjunto: <strong><?php echo $conjunto["nombre"] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombres</th>
								<th>Apellidos</th>
								<th>Tipo</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($evaluadores as $evaluador) : ?>
							<tr>
								<td><?php echo $evaluador["nombres"]; ?></td>
								<td><?php echo $evaluador["apellidos"]; ?></td>
								<td><?php echo $tiposEvaluador[$evaluador["tipo"]]; ?></td>
							</tr>
							<?php endforeach;  ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		var appname = "/colegio/encuesta";
		var url = window.location.origin + appname;
		
		$("#evaluador").on('blur',function(){
			console.log("Saliendo del input!!");
			var valor = $(this).val();
			console.log(valor);
			if(valor != ""){
				
				var urlCond = "/eval/" + valor; 
				
				var urlQueryEvaluador = url + "/json/evals"+urlCond;
				console.log(urlQueryEvaluador);
				
				$.ajax({
					url: urlQueryEvaluador,
					dataType: "json",
					success: function(data){
						
						console.dir(data);
						var tbody = $("#evaluadores").find('tbody'); 
						tbody.empty();
						
						$.each(data, function(i,item){
							
							//var checkbox = $("<input></input>").attr("type", "checkbox");
							
							tbody.append($('<tr>').
								append($('<td>').append(item.nombres)).
								append($('<td>').append(item.apellidos)) )
							);
						});
						/**/
					}
				});
				/**/
			}
		});
	});
</script>