<?php 
	$conjuntos = $this->conjuntos;
	$dbAdapter = Zend_Registry::get("dbmodquery");
	$grupoDAO = new Encuesta_DAO_Grupos($dbAdapter);
	$urlAlta = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"alta"),null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Conjuntos de Evaluacion</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-success" href="<?php echo $urlAlta; ?>">
						<i class="fa fa-plus-circle"></i> Agregar Nuevo Conjunto
					</a>
				</div>
				<hr />
				<div>
					<table id="conjuntos" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Conjunto</th>
								<th>Grupo</th>
								<th>Creado</th>
								<th>Asignaciones</th>
								<th>Evaluadores</th>
								<th>Evaluaciones</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($conjuntos as $conjunto) : 
								$grupo = $grupoDAO->obtenerGrupo($conjunto["idGrupoEscolar"]);
								$urlEvaluadores = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"evaluadores","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,TRUE);
								$urlEvals = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"evaluaciones","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,TRUE);
								$urlAsignaciones = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"asignaciones","idConjunto"=>$conjunto["idConjuntoEvaluador"]),null,TRUE);
								
								?>
							<tr>
								<td><?php echo $conjunto["nombre"] ?></td>
								<td><?php echo $grupo->getGrupo(); ?></td>
								<td><?php echo $conjunto["creacion"] ?></td>
								<td>
									<a class="btn btn-link" href="<?php echo $urlAsignaciones;  ?>">
										<i class="fa fa-graduation-cap"></i> Asignaciones Conjunto
									</a>
								</td>
								<td>
									<a class="btn btn-link" href="<?php echo $urlEvaluadores;  ?>">
										<i class="fa fa-users"></i> Evaluadores
									</a>
								</td>
								<td>
									<a class="btn btn-link" href="<?php echo $urlEvals;  ?>">
										<i class="fa fa-check-square-o"></i> Evaluaciones
									</a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		$("#conjuntos").DataTable();
	});
</script>