<?php 
	$conjuntos = $this->conjuntos;
	$grupoDAO = $this->grupoDAO;
	//$dbAdapter = Zend_Registry::get("dbmodquery");
	//$grupoDAO = new Encuesta_DAO_Grupos($dbAdapter);
	$params = array("module"=>"encuesta","controller"=>"conjunto","action"=>"alta");
	$urlAltaConjunto = $this->url($params,null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Conjuntos de Evaluacion</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-success" href="<?php echo $urlAltaConjunto; ?>">
						<i class="fa fa-plus-circle"></i> Agregar Nuevo Conjunto
					</a>
				</div>
				<hr />
				<div>
					<table id="conjuntos" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Grupo</th>
								<th>Conjunto</th>
								<th>Creación</th>
								<th>Asignaciones</th>
								<th>Evaluadores</th>
								<th>Evaluaciones</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($conjuntos as $conjunto) : 
								$grupo = $grupoDAO->obtenerGrupo($conjunto["idGrupoEscolar"]);
								$urlEvaluadores = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"evaluadores","co"=>$conjunto["idConjuntoEvaluador"]),null,true);
								$urlEvals = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"evaluaciones","co"=>$conjunto["idConjuntoEvaluador"]),null,true);
								$urlAsignaciones = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"asignaciones","co"=>$conjunto["idConjuntoEvaluador"]),null,true);
								$urlAdmin = $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"admin","co"=>$conjunto["idConjuntoEvaluador"]),null,true);
								?>
							<tr>
								<td><?php echo $grupo['grupoEscolar']; ?></td>
								<td>
								    <a target="_blank" class="btn btn-link" href="<?php echo $urlAdmin ?>">
								        <?php echo $conjunto["conjunto"] ?>
								    </a>
								</td>
								<td>
									<?php echo $conjunto["creacion"] ?>
								</td>
								<td>
									<a target="_blank" class="btn btn-link" href="<?php echo $urlAsignaciones;  ?>">
										<i class="fa fa-graduation-cap"></i> Asignaciones Conjunto
									</a>
								</td>
								<td>
									<a target="_blank" class="btn btn-link" href="<?php echo $urlEvaluadores;  ?>">
										<i class="fa fa-users"></i> Evaluadores
									</a>
								</td>
								<td>
									<a target="_blank" class="btn btn-link" href="<?php echo $urlEvals;  ?>">
										<i class="fa fa-check-square-o"></i> Evaluaciones
									</a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		$("#conjuntos").DataTable();
	});
</script>