<?php 
    $grupos = $this->grupos;
    $ciclo = $this->cicloEscolar;
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Conjuntos de Evaluacion en el Ciclo Escolar: <strong><?php echo $ciclo['ciclo'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<fieldset>
							<legend>Consulta de Conjuntos</legend>
							
							<div class="form-group">
    							<label for="idGrupoEscolar" class="control-label col-md-2">Grupo Escolar: </label>
    							<div class="col-md-5">
    								<select name="idGrupoEscolar" class="form-control">
    									<?php foreach ($grupos as $grupo) :  ?>
        								<option value="<?php echo $grupo['idGrupoEscolar']; ?>"><?php echo $grupo['grupoEscolar']; ?></option>
        								<?php endforeach; ?>
    								</select>
    							</div>
    						</div>
    						    						
    						<div class="form-group">
    							<div class="col-md-offset-2 col-md-10">
    								<button class="btn btn-info" type="submit">
    									<i class="fa fa-search"></i> Enviar
    								</button>
    							</div>
    						</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>