<?php
    $docentes = $this->docentes;
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-default">
    		<div class="panel-heading">
	            <h5 class="panel-title">Docentes del Sistema</h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"docente","action"=>"alta"),null,true) ?>">
	                    <span class="fa fa-plus"></span> Agregar Docente
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table id="docentes" class="table table-striped table-condensed">
	                    <thead>
	                        <tr>
	                            <th>Nombre</th>
	                            <th>Apellidos</th>
	                            <th>Creación</th>
	                            <th>Evaluaciones</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <?php foreach ($docentes as $docente) : ?>
	                        <tr>
	                            <td><?php echo $docente->getNombres() ?></td>
	                            <td><?php echo $docente->getApellidos() ?></td>
	                            <td><?php echo $docente->getFecha() ?></td>
	                            <td>
	                                <a class="btn btn-info btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"docente","action"=>"evaluaciones","idDocente"=>$docente->getIdRegistro()),null,true); ?>">
	                                    <span class="fa fa-search"></span> Evaluaciones
	                                </a>
	                            </td>
	                        </tr>
	                        <?php endforeach ?>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>
<script>
	$().ready(function(){
		$("#docentes").DataTable();
	});
</script>