<?php
    $docentes = $this->docentes;
    
    $params = array("module"=>"encuesta","controller"=>"docente","action"=>"alta");
    $urlAltaDocente = $this->url($params,null,true);
?>
<div class="row">
    <div class="col-md-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	            <h5 class="panel-title">Docentes del Sistema</h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-success" href="<?php echo $urlAltaDocente; ?>">
	                    <span class="fa fa-plus"></span> Agregar Docente
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table id="docentes" class="table table-striped table-condensed">
	                    <thead>
	                        <tr>
	                            <th>Nombre</th>
	                            <th>Apellidos</th>
	                            <th>Creación</th>
	                            <th>Configurar</th>
	                            <th>Evaluaciones</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <?php foreach ($docentes as $docente) :
	                           $params = array("module"=>"encuesta","controller"=>"docente","action"=>"admin","do" =>$docente['idDocente']);
	                           $urlConfig = $this->url($params,null,true);
	                           $params = array("module"=>"encuesta","controller"=>"docente","action"=>"evaluaciones","do"=>$docente['idDocente']);
	                           $urlEvaluaciones = $this->url($params,null,true);
	                        ?>
	                        <tr>
	                            <td><?php echo $docente['nombres'] ?></td>
	                            <td><?php echo $docente['apellidos'] ?></td>
	                            <td><?php echo $docente['creacion'] ?></td>
	                            <td>
	                                <a class="btn btn-link" href="<?php echo $urlConfig; ?>">
	                                    <i class="fa fa-cogs"></i> Configurar
	                                </a>
	                            </td>
	                            <td>
	                                <a class="btn btn-info btn-block" href="<?php echo $urlEvaluaciones; ?>">
	                                    <i class="fa fa-search"></i> Evaluaciones
	                                </a>
	                            </td>
	                        </tr>
	                        <?php endforeach ?>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>
<script>
	$().ready(function(){
		$("#docentes").DataTable();
	});
</script>