<?php 
	$evaluador = $this->evaluador;
    $tiposEvaluador = Zend_Registry::get("tiposEvaluador");
	
	$urlEdit = $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"edit","idEvaluador"=>$evaluador["idEvaluador"]),null,true);
	$urlEvaluadores = $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"index"),null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Actualizando Evaluador</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlEvaluadores ?>">
						<i class="fa fa-arrow-circle-left"></i> Regresar a Evaluadores
					</a>
				</div>
				<hr />
				<div>
					<?php //echo $formulario; ?>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
					    <div class="form-group">
					        <label for="apellidos" class="col-md-2 control-label">Apellidos: </label>
					        <div class="col-md-10">
					            <input name="apellidos" class="form-control" value="<?php echo ucwords(strtolower($evaluador["apellidos"])); ?>" />
					        </div>
					    </div>
					    
					    <div class="form-group">
					        <label for="nombres" class="col-md-2 control-label">Nombres: </label>
					        <div class="col-md-10">
					            <input name="nombres" class="form-control" value="<?php echo ucwords(strtolower($evaluador["nombres"])); ?>" />
					        </div>
					    </div>
					    
					    <div class="form-group">
                            <label for="tipo" class="col-md-2 control-label">Tipos Evaluador: </label>
                            <div class="col-md-10">
                                <select name="tipo" class="form-control">
                                    <?php foreach ($tiposEvaluador as $index => $value) : ?>
                                    <option value="<?php echo $index ?>"><?php echo $value; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
					    
					    <div class="form-group">
					        <div class="col-md-offset-2 col-md-10">
					            <button class="btn btn-success" type="submit">
					                <i class="fa fa-refresh"></i> Actualizar
					            </button>
					        </div>
					    </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>