<?php
	$formulario = $this->formulario;
	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
	$urlEvaluadores = $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"index"),null,true);
	$urlScript = $this->baseUrl()."/public/js/helpers/checkEvaluador.js";
	
	$estatusEvaluadores = $this->estatusEvaluadores;
	
	$tiposEvaluador = array(
	    'ALUM' => 'Alumna',
	    'DOCE' => 'Docente',
	    'EXAL' => 'ExAlumna',
	    'PAFA' => 'Padres de Familia'
	);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">
					Registrar nuevo evaluador
				</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlEvaluadores; ?>">
						<i class="fa fa-arrow-circle-left"></i> Regresar a Evaluadores
					</a>
					<?php if(!is_null($messageSuccess)){ ?>
	                <br /><br />
	                <div class="alert alert-success" role="alert">
	                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	                      <span aria-hidden="true">&times;</span>
	                    </button>
	                    <?php echo $messageSuccess; ?>
	                </div>
	                <?php }elseif(!is_null($messageFail)){ ?>
	                <div class="alert alert-danger" role="alert">
	                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	                      <span aria-hidden="true">&times;</span>
	                    </button>
	                    <?php echo $messageFail; ?>
	                </div>
	                <?php } ?>
					<hr />
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<div class="form-group">
							<label for="tipo" class="control-label col-md-2">Tipo Evaluador:</label>
							<div class="col-md-10">
								<select name="tipo" id="tipo" class="form-control">
									<?php foreach ($tiposEvaluador as $clave => $tipoEvaluador) : ?>
									<option value="<?php echo $clave; ?>"><?php echo $tipoEvaluador; ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="idEstatusEvaluador" class="control-label col-md-2">Estatus Evaluador:</label>
							<div class="col-md-10">
								<select name="idEstatusEvaluador" id="idEstatusEvaluador" class="form-control">
									<?php foreach ($estatusEvaluadores as $estatusEvaluador) : ?>
									<option value="<?php echo $estatusEvaluador['idEstatusEvaluador']; ?>"><?php echo $estatusEvaluador['descripcion']; ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
					
						<div class="form-group">
							<label for="apellidos" class="control-label col-md-2">Apellidos:</label>
							<div class="col-md-10">
								<input id="apellidos" name="apellidos" type="text" class="form-control" placeholder="Apellidos..." />
							</div>
						</div>
						
						<div class="form-group">
							<label for="nombres" class="control-label col-md-2">Nombres:</label>
							<div class="col-md-10">
								<input id="nombres" name="nombres" type="text" class="form-control" placeholder="Nombres..." />
							</div>
						</div>
						
						<div class="form-group">
							<label for="clave" class="control-label col-md-2">Clave (Matricula):</label>
							<div class="col-md-10">
								<input id="clave" name="clave" type="text" class="form-control" placeholder="Clave o Matricula..." />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button class="btn btn-success">
									<i class="fa fa-save"></i> Agregar Evaluador
								</button>
							</div>
						</div>
					</form>
				</div>
				<hr />
				<div>
					<header>
						<h4>Evaluadores Registrados</h4>
					</header>
					<hr />
					<table id="evaluadores" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombre</th>
								<th>Apellidos</th>
								<th>Administrar</th>
								<th>Tipo</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $urlScript; ?>"></script>
<script type="text/javascript">
	$().ready(function(){
		$('#evaluadores').DataTable();
	});
</script>
