<?php
	$evaluadores = $this->evaluadores;
	$tiposEvaluador = Zend_Registry::get("tiposEvaluador");
	$urlAlta = $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"alta"),null,true);
    $urlNormalize = $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"normalizen"),null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Evaluadores Registrados</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-success" href="<?php echo $urlAlta ?>">
						<i class="fa fa-plus-circle"></i> Agregar Evaluador
					</a>
					
					<a class="btn btn-warning" href="<?php echo $urlNormalize ?>">
					    <i class="fa fa-refresh"></i> Normalizar Evaluadores
					</a>
				</div>
				<hr />
				<div>
					<table id="evaluadores" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombres</th>
								<th>Apellidos</th>
								<th>Tipo</th>
								<th>Configurar</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($evaluadores as $evaluador) : ?>
							<tr>
								<td><?php echo $evaluador["nombres"] ?></td>
								<td><?php echo $evaluador["apellidos"] ?></td>
								<td><?php echo $tiposEvaluador[$evaluador["tipo"]] ?></td>
								<td>
									<?php $urlAdmin = $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"admin","ev"=>$evaluador["idEvaluador"]),null,true); ?>
									<a class="btn btn-link" href="<?php echo $urlAdmin ?>">
										<i class="fa fa-cogs"></i> Configurar
									</a>
								</td>
							</tr>
							<?php endforeach ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		$("#evaluadores").DataTable();
	});
</script>