<?php
    $formulario = $this->formulario;
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
    
    $params = array("module"=>"biblioteca","controller"=>"autor","action"=>"index");
    $urlAutores = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Alta de Autor(es) en Biblioteca.</h5>
			</div>
			<div class="panel-body">
			    <div>
                    <a class="btn btn-info" href="<?php echo $urlAutores; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Autores
                    </a><br />
                    <?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <br />
                    <?php } ?>
                </div>
                <hr />
                <div>
                    <?php echo $formulario; ?>
                </div>
			</div>
		</div>
	</div>
</div>

<script>
	$().ready(function(){
		$("select#tipo").on('change',function(){
			//console.log("combo cambio!!!");
			var valorCombo = $(this).val();
			//console.log(valorCombo);
			
			switch(valorCombo) {
				case("VR") :
				case("IN") :
					//console.log("Varios o Indefinido seleccionado");
					$("input#nombres").attr('disabled','true');
					$("input#apellidos").attr('disabled','true');
					$("input#autores").removeAttr('disabled');
					break;
				case("UN") :
					//console.log("Unico seleccionado");
					$("input#autores").attr('disabled','true');
					$("input#nombres").removeAttr('disabled');
					$("input#apellidos").removeAttr('disabled');
					break;
			}
		});
		
	});
</script>