<?php
    $autores = $this->autores;
    
    $params = array("module"=>"biblioteca","controller"=>"autor","action"=>"alta");
    $urlAltaAutor = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Autores Registrados en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaAutor; ?>">
			            <i class="fa fa-plus"></i> Nuevo Autor
			        </a>
			    </div>
			    <hr />
			    <div>
			   
			        <table id="tAutor" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Tipo</th>
			                    <th>Nombres</th>
			                    <th>Apellidos</th>
			                    <th>Autores</th>
			                    <th>Creación</th>
			                    <td>Editar</td>
			                    </td>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($autores as $autor) :
			                 $urlAdminAutores = $this->url(array('module'=>'biblioteca','controller'=>'autor','action'=>'admin','atr'=>$autor['idAutor']));
			                ?>
			                <tr>
			                    <td><?php echo $autor["tipo"]; ?></td>
			                    <td><?php echo $autor["nombres"]; ?></td>
			                    <td><?php echo $autor["apellidos"]; ?></td>
			                    <td><?php echo $autor["autores"]; ?></td>
			                    <td><?php echo $autor["creacion"]; ?></td>
			                    <td>
			                    	<a class="btn btn-link" href="<?php echo $urlAdminAutores; ?>">
			                   			<i class="fa fa-edit"></i> 
			                   		</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			         
			            </tbody>
			        </table>
			    
			    </div>
			</div>
		</div>
	</div>
</div>

<script>

	$().ready(function(){
		console.log("jQuery Activo!!");

		$("#tAutor").DataTable();
		
	});
		
</script>