<?php
    $autores = $this->autores;
    
    $params = array("module"=>"biblioteca","controller"=>"autor","action"=>"alta");
    $urlAltaAutor = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Autores Registrados en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaAutor; ?>">
			            <i class="fa fa-plus"></i> Nuevo Autor
			        </a>
			    </div>
			    <hr />
			    <div>
			        <table class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Tipo</th>
			                    <th>Nombres</th>
			                    <th>Apellidos</th>
			                    <th>Autores</th>
			                    <th>Creación</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($autores as $autor) : ?>
			                <tr>
			                    <td><?php echo $autor["tipo"]; ?></td>
			                    <td><?php echo $autor["nombres"]; ?></td>
			                    <td><?php echo $autor["apellidos"]; ?></td>
			                    <td><?php echo $autor["autores"]; ?></td>
			                    <td><?php echo $autor["creacion"]; ?></td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
</div>