<?php 
	$formulario = $this->formulario;
    $tiposPregunta = Zend_Registry::get("tipo");
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h5 class="panel-title">Alta de Pregunta en <strong><?php echo $this->mensaje; ?></strong></h5>
            </div>
            <div class="panel-body">
                <div>
                </div>
                <hr />
                <div>
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group">
                            <label class="col-xs-2 control-label" for="pregunta">Pregunta: </label>
                            <div class="col-xs-10">
                                <input class="form-control" type="text" name="pregunta" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-xs-2 control-label" for="tipoPregunta">Tipo Pregunta: </label>
                            <div class="col-xs-10">
                                <select class="form-control" name="tipoPregunta">
                                    <?php foreach ($tiposPregunta as $index => $value) : ?>
                                    <option value="<?php echo $index ?>"><?php echo $value ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button class="btn btn-success" type="submit">
                                    <i class="fa fa-plus"></i> Agregar Pregunta
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <?php if(!is_null($this->opciones)){ $opciones = $this->opciones; ?>
                <article class="col-md-3">
                    <header>
                        <h3>
                            Opciones de la Pregunta:
                        </h3>
                    </header>
                    <div>
                        <table class="table table-striped table-condensed">
                            <tbody>
                                <?php foreach ($opciones as $key => $value) : ?>
                                <tr>
                                    <td><?php echo $value; ?></td>
                                </tr>   
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </article>
                <?php }  ?>
            </div>
        </div>
    </div>
</div>
