<?php
    $module = "evento";
    
    $urlEventoAlta = $this->url(array("module"=>$module,"controller"=>"evento", "action"=>"alta"),null,true);
    $urlEventoQuery = $this->url(array("module"=>$module,"controller"=>"consulta", "action"=>"index"),null,true);
    $urlRegistroAlta = $this->url(array("module"=>$module,"controller"=>"registro", "action"=>"alta"),null,true);
    
    $eventos = $this->eventos;
    $eventosVacios = false;
    $classSuccess = 'btn-success';
    $classDanger = 'btn-danger';
    
    
    $btnAssocClass = 'btn-success';
    $btnConfirmClass = 'btn-success';
    
    if (empty($eventos)) {
        print_r('Eventos vacios');
        $eventosVacios = true;
    }
    
    $classHasEvents = $eventosVacios == false ? $classSuccess : $classDanger;
    
    $btnAssocClass = $eventosVacios == false ? $classSuccess : $classDanger;
    $urlRegistroAlta = $eventosVacios == false ? $this->url(array("module"=>$module,"controller"=>"registro", "action"=>"alta"),null,true) : '#';
    $urlRegistroConfirm = $eventosVacios == false ? $this->url(array("module"=>$module,"controller"=>"registro", "action"=>"index"),null,true) : '#';
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Acciones del Sistema de Eventos</h5>
			</div>
			<div class="panel-body">
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Detalle</th>
								<th>Params</th>
								<th>Acción</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<p>
										Alta de Evento
									</p>
								</td>
								<td></td>
								<td>
									<a class="btn btn-success" href="<?php echo $urlEventoAlta; ?>">
										<i class="fa fa-plus-square-o" ></i> Alta Evento
									</a>
								</td>
							</tr>
							
							<tr>
								<td>
									<p>
										Consulta asistentes en evento
									</p>
								</td>
								<td>
									<select id="queryEvento" class="form-control">
										<?php foreach ($eventos as $evento): ?>
										<option value="<?php echo $evento['id'] ?>"><?php echo $evento['nombre'] ?></option>
										<?php endforeach; ?>
									</select>
								</td>
								<td>
									<button id="btnQuery" class="btn btn-success" href="<?php echo $urlEventoQuery; ?>">
										<i class="fa fa-search"></i> Consulta Asistentes
									</button>
								</td>
							</tr>
							
							<tr>
								<td>
									<p>
										Registro de Asistentes a Evento
									</p>
								</td>
								<td>
									<select id="sEvento" class="form-control">
										<?php foreach ($eventos as $evento): ?>
										<option value="<?php echo $evento['id'] ?>"><?php echo $evento['nombre'] ?></option>
										<?php endforeach; ?>
									</select>
								</td>
								<td>
									<button id="btnRegister" class="btn <?php echo $classHasEvents;  ?>" >
										<i class="fa fa-user-plus"></i> Registro Asistentes
									</button>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div></div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		var appname = "/colegio/evento";
		var url = window.location.origin + appname;

		$("#btnQuery").on('click',function(){
			var idEvento = $("#queryEvento").val();
			// console.log("IdEvento = "+idEvento);
			var urlRegAsis = url + "/consulta/index/ev/"+idEvento;
			// console.log("UrlRegAsisEvento = "+urlRegAsis);
			window.location.href = urlRegAsis;
		});
		
		$("#btnRegister").on('click',function(){
			var idEvento = $("#sEvento").val();
			// console.log("IdEvento = "+idEvento);
			var urlRegAsis = url + "/registro/alta/ev/"+idEvento;
			// console.log("UrlRegAsisEvento = "+urlRegAsis);
			window.location.href = urlRegAsis;
		});

		$("#btnRAsis").on('click',function(){
			var idEvento = $("#asisEvento").val();

			var urlRegAsis = url + "/registro/confirm/ev/"+idEvento;
			window.location.href = urlRegAsis;
		});


		
	});

</script>
