<?php 
	$grupo = $this->grupo;
	$conjuntos = $this->conjuntos;
	
	$evaluadores = $this->evaluadores;
	
?>
<section id="evaluadores">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Evaluadores del grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong> </h3>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
            	<?php foreach ($evaluadores as $evaluador): 
            	$conjunto = $evaluador['conjunto'];
            	$grupo = $evaluador['grupo'];
            	$evals = $evaluador['evaluadores'];
            	$evaluaciones = $evaluador['evaluaciones'];
            	//print_r($evaluaciones);
            	if (!empty($evals)) {
            	?>
            	<table class="table table-striped table-condensed">
                	<thead>
                		<tr>
                			<th>Conjunto</th>
                			<th>Apellidos</th>
                			<th>Nombres</th>
                			<th>Evaluaciones</th>
                		</tr>
                	</thead>
                	<tbody>
                		<?php foreach ($evals as $eval) : ?>
                		<tr>
                			<td><?php echo $conjunto['nombre']; ?></td>
                			<td><?php echo $eval['apellidos'] ?></td>
                			<td><?php echo $eval['nombres'] ?></td>
                			<td>
                				<?php foreach ($evaluaciones as $evaluacion): 
                				$params = array(
                				    'module'=>'encuesta',
                				    'controller'=>'evaluacion',
                				    'action' => 'evaluaciones',
                				    'ev' => $evaluacion['idEncuesta'],
                				    'co' => $conjunto['idConjuntoEvaluador'],
                				    'er' => $eval['idEvaluador'],
                				    
                				);
                				$url = $this->url($params,null,true);
                				?>
                				<a href="<?php echo $url; ?>" class="btn btn-link">
                					<i class="fa fa-check-square-o"></i> Evaluacion <?php echo $evaluacion['nombreClave'] ?>
                				</a>
                				<br />
                				<?php endforeach; ?>
                			</td>
                		</tr>
                		<?php endforeach; ?>
                	</tbody>
                </table>
                <hr />
            	<?php } endforeach; ?>
            </div>
        </div>
    </div>
</section>
