<?php
	$dbAdapter = Zend_Registry::get("dbmodquery");
	
	$grupoDAO = new Encuesta_DAO_Grupos($dbAdapter);
	$materiaDAO = new Encuesta_DAO_Materia($dbAdapter);
	$registroDAO = new Encuesta_DAO_Registro($dbAdapter);
	$encuestaDAO = new Encuesta_DAO_Encuesta($dbAdapter);
	
	$encuestas = $encuestaDAO->getEncRelByIdGrupoEscolar($this->idGrupo);
	
	$asignaciones = $this->asignaciones;
	$grupo = $grupoDAO->obtenerGrupo($this->idGrupo);
	
	$asignacionesRealizadas;
	
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">
					Evaluaciones del Grupo: <strong><?php echo $grupo->getGrupo() ?></strong>
				</h3>
			</div>
			<div class="panel-body">
				<?php foreach ($encuestas as $encuesta) :
					//print_r($encuesta["idEncuesta"]); 
					$encuestaActual = $encuestaDAO->getEncuestaById($encuesta["idEncuesta"]);
					
					
					
					?>
				<div>
					<h4>Evaluacion: <strong><?php echo $encuestaActual->getNombre() ?></strong> </h4>
				</div>
				<hr />
				<table class="table table-striped table-condensed">
					<thead>
						<th>Materia</th>
						<th>Docente</th>
						<th>Evaluar</th>
					</thead>
					<tbody>
						<?php foreach ($asignaciones as $asignacion) :
							$materia = $materiaDAO->obtenerMateria($asignacion["idMateriaEscolar"]);
							$docente = $registroDAO->obtenerRegistro($asignacion["idRegistro"]);
							?>
						<tr>
							<td><?php echo $materia->getMateriaEscolar() ?></td>
							<td><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></td>
							<td>
								<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"evaluacion","action"=>"evaluar","idEncuesta"=>$encuesta["idEncuesta"],"idAsignacion"=>$asignacion["idAsignacionGrupo"],),null,true) ?>">
									<i class="fa fa-check-square"></i> Evaluar
								</a>
							</td>
						</tr>	
						<?php endforeach; ?>
					</tbody>
				</table>
				<?php endforeach; ?>
			</div>
	</div>
	</div>
</div>