<?php
    $tipos = $this->tipos;
    $ubicaciones = $this->ubicaciones;
    $usuarios = $this->usuarios;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Consulta de Equipos</h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<div class="form-group">
							<label for="tipo" class="control-label col-md-2">Tipo Equipo: </label>
							<div class="col-md-5">
								<select name="tipo" id="tipo" class="form-control">
									<option value="0">Tipo Equipo</option>
									<?php foreach ($tipos as $tipo): ?>
									<option value="<?php echo $tipo["id"] ?>" ><?php echo $tipo["tipo"] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="ubicacion" class="control-label col-md-2">Ubicación Equipo: </label>
							<div class="col-md-5">
								<select name="ubicacion" id="ubicacion" class="form-control">
									<option value="0">Ubicación equipo</option>
									<?php foreach ($ubicaciones as $ubicacion): ?>
									<option value="<?php echo $ubicacion["id"] ?>" ><?php echo $ubicacion["ubicacion"]; ?> </option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="usuario" class="control-label col-md-2">Usuario Equipo: </label>
							<div class="col-md-5">
								<select name="tipo" id="usuario" class="form-control">
									<option value="0">Tipo Equipo</option>
									<?php foreach ($usuarios as $usuario): ?>
									<option value="<?php echo $usuario["id"] ?>" ><?php echo $usuario["usuario"] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button class="btn btn-success" id="btnQuery">
									<i class="fa fa-search"></i> Consultar Equipos
								</button>
							</div>
						</div>
					</div>
				</div>
				<hr />
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Equipo</th>
								<th>Num Serie</th>
								<th>Detalle A</th>
								<th>Detalle B</th>
								<th>Detalle C</th>
								<th>Detalle D</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
<!--

//-->
$().ready(function(){

	var appname = "/colegio/soporte";
    var url = window.location.origin + appname;
	console.log("jQuery corriendo");
	// Tipo
	//$("#btnQueryReports").on('click',function() {
	$("#btnQuery").on('click',function(){
		console.log("consulta generada");
		var tipo = $("#tipo").val();
		var ubicacion = $("#ubicacion").val();
		var usuario = $("#usuario").val();

		console.log(tipo);
		console.log(ubicacion);
		console.log(usuario);

		var urlQuery = url + "/json/queryres"

		if(tipo != 0){
			urlQuery += "/tp/"+tipo;
		}

		if(ubicacion != 0){
			urlQuery += "/ub/"+ubicacion;
		}

		if(usuario != 0){
			urlQuery += "/us/"+usuario;
		}

		console.log(urlQuery);
	});
	
});

</script>
