<?php

    $idiomas = $this->idiomas;
    
    $formulario = $this->formulario;
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
    
    $params = array("module"=>"biblioteca","controller"=>"idioma","action"=>"index");
    $urlIdioma = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Edición de Idioma</h5>
			</div>
			<div class="panel-body">
			    <div>
                    <a class="btn btn-info" href="<?php echo $urlIdioma; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Idiomas
                    </a><br />
                    <?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <br />
                    <?php } ?>
                    
                </div>
                <hr />
                <div >
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                 		<div class="form-group">
                 			<label for="idioma" class="control-label col-md-2"> Idioma</label>
                 			<div class="col-md-5">
								<input name="idioma" type="text" class="form-control" value="<?php echo $idiomas['idioma']?>"/>
							</div>
                 		</div>
                 		
                 		<div class="form-group">
                 			<label for="ingles" class="control-label col-md-2"> Inglés</label>
                 			<div class="col-md-5">
								<input name="ingles" type="text" class="form-control" value="<?php echo $idiomas['english']?>" />
							</div>
                 		</div>
                 		
                 			<div class="form-group">
                 			<label for="codigo" class="control-label col-md-2">Código</label>
                 			<div class="col-md-5">
								<input name="codigo" type="text" class="form-control" value="<?php echo $idiomas['codigo']?>" />
							</div>
                 		</div>
                 		
                 		<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-warning" type="submit">
									<i class="fa fa-refresh"></i> Actualizar Idioma
								</button>
							</div>
						</div>
                 	</form>
			</div>
		</div>
	</div>
</div>