<?php
    $idiomas = $this->idiomas;
    
    $params = array("module"=>"biblioteca","controller"=>"idioma","action"=>"alta");
    $urlAltaIdioma = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Idiomas registrados en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaIdioma; ?>">
			            <i class="fa fa-plus"></i> Nuevo Idioma
			        </a>
			    </div>
			    <hr />
			    <div>
			        <table class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Idioma</th>
			                    <th>Inglés</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                    <th>Editar</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($idiomas as $idioma) : 
			                  $urlAdminIdioma = $this->url(array('module'=>'biblioteca','controller'=>'idioma','action'=>'admin','idm'=>$idioma['idIdioma']));
			                ?>
			                <tr>
			                    <td><?php echo $idioma["idioma"]; ?></td>
			                    <td><?php echo $idioma["english"]; ?></td>
			                    <td><?php echo $idioma["codigo"]; ?></td>
			                    <td><?php echo $idioma["creacion"]; ?></td>
			                    <td>
			                    	 <a class="btn btn-link" href="<?php echo $urlAdminIdioma; ?>">
										<i class="fa fa-edit"></i> 
									</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
</div>