<?php
    $grupo = $this->grupo;
    $evaluaciones = $this->evaluaciones;
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Evaluadores del Grupo: <strong><?php echo $grupo->getGrupo(); ?></strong></h5>
            </div>
            <div class="panel-body">
                <div>
                    
                </div>
                <hr />
                <div>
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Materia</th>
                                <th>Docente</th>
                                <th>Evaluaciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($evaluaciones as $asignacion => $evaluacion) : 
                                $urlEvaluaciones = $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"evalsas","as"=>$asignacion),null,true);
                                ?>
                            <tr>
                                <td><?php echo $evaluacion["materia"]["materiaEscolar"]; ?></td>
                                <td><?php echo $evaluacion["docente"]["apellidos"].", ". $evaluacion["docente"]["nombres"] ?></td>
                                <td>
                                    <a class="btn btn-link" href="<?php echo $urlEvaluaciones; ?>">
                                        <i class="fa fa-check-circle"></i> Evaluaciones
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>