<?php
    $conjuntos = $this->conjuntos;
    $params = array(
        "module"=>"encuesta",
        "controller"=>"resultado",
        "action"=>"index"
    );
    
    $urlEvals = $this->url($params,null,true);
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Evaluaciones por Conjuntos</h5>
            </div>
            <div class="panel-body">
                <div>
                    <a class="btn btn-info" href="<?php echo $urlEvals; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a las Evaluaciones
                    </a>
                </div>
                <hr />
                <div>
                    <table id="table" class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Conjunto</th>
                                <th>Evaluaciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($conjuntos as $conjunto) : 
                                $params = array(
                                    "module"=>"encuesta",
                                    "controller"=>"resultado",
                                    "action"=>"evalsco",
                                    "co"=>$conjunto["idConjuntoEvaluador"],
                                );
                                $urlEvals = $this->url($params,null,true);
                                ?>
                            <tr>
                                <td><?php echo $conjunto["nombre"]; ?></td>
                                <td>
                                    <a class="btn btn-link" href="<?php echo $urlEvals; ?>">
                                        <i class="fa fa-cubes"></i> Evaluaciones
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $().ready(function(){
        $("#table").DataTable();
    });
</script>