<?php
    $asignacion = $this->asignacion;
    $materia = $this->materia;
    $docente = $this->docente;
    $grupoE = $this->grupoE;
    $evaluaciones = $this->evaluaciones;
    
    $encuestaDAO = $this->encuestaDAO;
    //print_r($grupoE);
    //print_r($asignacion);
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Resultados de la asignación en el Grupo: <strong><?php echo $grupoE['grupoEscolar']; ?></strong></h5>
            </div>
            <div class="panel-body">
                <div>
                    <h4>Materia: <strong><?php echo $materia["materiaEscolar"]; ?></strong></h4>
                    <h4>Docente: <strong><?php echo $docente["apellidos"].", ".$docente["nombres"]; ?></strong></h4>
                </div>
                <hr />
                <div>
                    <?php foreach ($evaluaciones as $evaluacion) : 
                        //print_r($evaluacion);
                        $encuesta = $encuestaDAO->getEncuestaById($evaluacion["idEncuesta"]);
                        //print_r($encuesta->toArray());
                        
                        //$url = $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"resgras","as"=>$asignacion["idAsignacionGrupo"],"ev"=>$encuesta["idEncuesta"]),null,true);
                        
                        switch ($encuesta["idEncuesta"]) {
                            case '1':
                                
                                break;
                            case '2':
                                $url = $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"resgras","as"=>$asignacion["idAsignacionGrupo"],"ev"=>$encuesta["idEncuesta"]),null,true);
                                break;
                            case '3':
                                $url = $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"resgras","as"=>$asignacion["idAsignacionGrupo"],"ev"=>$encuesta["idEncuesta"]),null,true);
                                break;
                            case '4':
                                $url = $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"resautoev","as"=>$asignacion["idAsignacionGrupo"],"ev"=>$encuesta["idEncuesta"]),null,true);
                                break;
                        }
                        
                        ?>
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Encuesta</th>
                                <th>Resultados</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <?php echo $encuesta["nombre"]; ?>
                                </td>
                                <td>
                                    <a class="btn btn-link" href="<?php echo $url; ?>">
                                        <i class="fa fa-bar-chart"></i> Resultado
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>