<?php
    $conjunto = $this->conjunto;
    $asignacionesConjunto = $this->asignacionesConjunto;
    
    $encuestaDAO = $this->encuestaDAO;
    $materiaDAO = $this->materiaDAO;
    $registroDAO = $this->registroDAO;
    
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Evaluaciones Disponibles</h5>
			</div>
			<div class="panel-body">
				<div></div>
				<div>
				    <?php foreach ($asignacionesConjunto as $idEncuesta => $asignaciones) : 
				        $encuesta = $encuestaDAO->getEncuestaById($idEncuesta);
                        //print_r($asignaciones);print_r("<br />");
				        ?>
				    <div>
				        <h3>Resultados de la Evaluación: <strong><?php echo $encuesta->getNombre(); ?></strong></h3>
				    </div>
				    <hr />
				    <table class="table table-striped table-condensed">
				        <thead>
				            <tr>
				                <th>Materia</th>
				                <th>Docente</th>
				                <th>Evaluaciones</th>
				            </tr>
				        </thead>
				        <tbody>
				            <?php foreach ($asignaciones as $asignacion) : 
				                $materia = $materiaDAO->getMateriaById($asignacion["idMateriaEscolar"]);
				                $registro = $registroDAO->obtenerRegistro($asignacion["idRegistro"]);
                                
                                $params = array(
                                    "module"=>"encuesta",
                                    "controller"=>"resultado",
                                    "action"=>"rescon",
                                    "co" => $conjunto["idConjuntoEvaluador"],
                                    "ev" => $idEncuesta,
                                    "as" => $asignacion["idAsignacionGrupo"]
                                );
                                $urlResultado = $this->url($params,null,true);
				                ?>
				            <tr>
				                <td>
				                    <?php echo $materia["materiaEscolar"] ?>
				                </td>
				                <td>
				                    <?php echo $registro->getApellidos().", ".$registro->getNombres() ?>
				                </td>
				                <td>
				                    <a class="btn btn-link" href="<?php echo $urlResultado; ?>">
				                        <i class="fa fa-external-link"></i> Resultado Evaluación
				                    </a>
				                </td>
				            </tr>
				            <?php endforeach; ?>
				        </tbody>
				    </table>
				    <hr />
				    <?php endforeach ?>
				</div>
			</div>
		</div>
	</div>
</div>