<?php
    $params = array(
        "module"=>"encuesta",
        "controller"=>"resultado",
        "action"=>"conjuntos"
    );
    $urlConjuntos = $this->url($params,null,true);
    $params["action"] = "grupos";
    $urlGrupos = $this->url($params,null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
		    <div class="panel-heading">
		        <h5 class="panel-title">Consultar Evaluaciones</h5>
		    </div>
    		<div class="panel-body">
    			<div>
    			    <a class="btn btn-success" href="<?php echo $urlGrupos; ?>">
                        <i class="fa fa-search"></i> Evaluaciones por Grupos
                    </a>
    			</div>
    		</div>
	   </div>
    </div>
</div>