<?php
    $evaluacion = $this->evaluacion;
    $asignacion = $this->asignacion;
    
    $evaluadores = $this->evaluadores;
    $evaluacionDAO = $this->evaluacionDAO;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Docentes</h5>
			</div>
			<div class="panel-body">
			    <div>
			        
			    </div>
			    <hr />
			    <div>
			        <table class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Evaluador</th>
			                    <th>Resultados</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($evaluadores as $evaluador) : 
			                    $url = $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"autoeval","as"=>$asignacion["idAsignacionGrupo"],"ev"=>$evaluacion["idEncuesta"], "er"=>$evaluador["idEvaluador"]),null,true);
			                    ?>
			                <tr>
			                    <td><?php echo $evaluador["apellidos"].", ".$evaluador["nombres"] ?></td>
			                    <td>
			                        <a class="btn btn-success" href="<?php echo $url ?>">
			                            <i class="fa fa-file-pdf-o"></i> Resultado
			                        </a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
</div>