<?php
    $conjunto = $this->conjunto;
    $materia = $this->materia;
    $docente = $this->docente;
    
    $preguntaDAO = $this->preguntaDAO;
    $respuestaDAO = $this->respuestaDAO;
    $resultados = $this->resultados;
    $totalEvaluadores = count($resultados);
    //
    $preferencias = $this->preferencias;
?>
<div class="row">
    <div class="col-xs-10">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Resultado de Evaluación para: <strong></strong> </h5>
            </div>
            <div class="panel-body">
                <div>
                    <h4>Grupo: <?php echo $conjunto["nombre"]; ?></h4>
                    <h4>Docente: </h4>
                    <h4>Materia: </h4>
                    <h4>Evaluadores: <?php echo $totalEvaluadores; ?> </h4>
                    <a class="btn btn-success" href="" target="_blank">
                        <i class="fa fa-file-pdf-o"></i> Archivo PDF
                    </a>
                </div>
                <div>
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Pregunta</th>
                                <th>Puntaje</th>
                                <th>Promedio</th>
                                <th>Grafico</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($preferencias as $idPregunta => $contenedor) : 
                                //print_r($resultado);print_r("<br /><br />");
                                $pregunta = $preguntaDAO->getPreguntaById($idPregunta);
                                //$opcionMayor = $op
                                $opcionMayor = $contenedor["opcionMayor"];
                                $preferencia = $contenedor["preferencia"];
                                $valorMayor = null;
                                switch ($opcionMayor["tipoValor"]) {
                                    case 'EN':
                                        $valorMayor = $opcionMayor["valorEntero"];
                                        break;
                                    case 'DC':
                                        $valorMayor = $opcionMayor["valorDecimal"];
                                        break;
                                    case 'TX':
                                        $valorMayor = $opcionMayor["valorTexto"];
                                        break;
                                }
                                $puntajeMayor = $valorMayor * $totalEvaluadores;
                                $puntajeObtenido = $preferencia;
                                $calificacion = (10*$puntajeObtenido) / $puntajeMayor;
                                ?>
                            <tr>
                                <td><?php echo $pregunta->getNombre(); ?></td>
                                <td><?php echo $preferencia; ?></td>
                                <td><?php echo sprintf('%.2f', $calificacion); ?></td>
                                <td>
                                    <a class="btn btn-link" target="_blank" href="<?php ?>">
                                        <i class="fa fa-area-chart"></i> 
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>