<?php
    $conjunto = $this->conjunto;
    $materia = $this->materia;
    $docente = $this->docente;
?>
<div class="row">
	<div class="col-xs-10">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Resultado de Evaluación para: <strong></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
				    <h3>Grupo: <?php echo $conjunto["nombre"]; ?></h3>
				</div>
				<div>
				    
				</div>
			</div>
		</div>
	</div>
</div>
