<?php
    $asignacion = $this->asignacion;
    $encuesta = $this->encuesta;
    
    $docente = $this->docente;
    $materia = $this->materia;
    
    $preguntaDAO = $this->preguntaDAO;
    $respuestaDAO = $this->respuestaDAO;
    
    $preferencias = $this->preferencias;
    $totalEvaluadores = $this->totalEvaluadores;
    $sumaTotal = 0.0;
    $promedioTotal = 0.0;
    $totalPreguntas = 0;
    
    $idReporte = $this->idReporte;
    
    $urlRepGrupal = $this->url(array("module"=>"encuesta","controller"=>"reporte","action"=>"descarga","idReporte"=>$idReporte),null,TRUE);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Evaluacion Grupal: <strong></strong></h5>
			</div>
			<div class="panel-body">
			    <div>
			        <h4>Materia: <strong><?php echo $materia["materiaEscolar"]; ?></strong> </h4>
			        <h4>Docente: <strong><?php echo $docente["apellidos"].", ".$docente["nombres"]  ?></strong> </h4>
			        <h4>Evaluadores: <strong><?php echo $totalEvaluadores; ?></strong></h4>
			        <a class="btn btn-success" href="<?php echo $urlRepGrupal; ?>">
			            <i class="fa fa-file-pdf-o"></i> Reporte Grupal de la Asignacion
			        </a>
			    </div>
			    <hr />
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Pregunta</th>
                            <th>Puntaje</th>
                            <th>Promedio</th>
                            <th>Gráfico</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($preferencias as $idPregunta => $contenedor) : 
                            //print_r($resultado);print_r("<br /><br />");
                            $pregunta = $preguntaDAO->getPreguntaById($idPregunta);
                            $totalPreguntas++;
                            //$opcionMayor = $op
                            $opcionMayor = $contenedor["opcionMayor"];
                            $preferencia = $contenedor["preferencia"];
                            $valorMayor = null;
                            switch ($opcionMayor["tipoValor"]) {
                                case 'EN':
                                    $valorMayor = $opcionMayor["valorEntero"];
                                    break;
                                case 'DC':
                                    $valorMayor = $opcionMayor["valorDecimal"];
                                    break;
                                case 'TX':
                                    $valorMayor = $opcionMayor["valorTexto"];
                                    break;
                            }
                            $puntajeMayor = $valorMayor * $totalEvaluadores;
                            $puntajeObtenido = $preferencia;
                            $calificacion = (10*$puntajeObtenido) / $puntajeMayor;
                            $sumaTotal += $calificacion;
                            ?>
                        <tr>
                            <td><?php echo $pregunta->getNombre(); ?></td>
                            <td><?php echo $preferencia; ?></td>
                            <td><?php echo sprintf('%.2f', $calificacion); ?></td>
                            <td>
                                <a class="btn btn-link" target="_blank" href="<?php ?>">
                                    <i class="fa fa-area-chart"></i> 
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <?php echo "Promedio General: <strong>". sprintf('%.2f', $sumaTotal/$totalPreguntas. "</strong>"); ?>
            </div>
		</div>
	</div>
</div>