<?php
    $resumen = $this->resumen;
    
    $utilText = new Encuesta_Util_Text;
    $asignacion = $this->asignacion;
    $encuesta = $this->encuesta;
    
    $docente = $this->docente;
    $materia = $this->materia;
    $grupoE = $this->grupoE;
    
    $preguntaDAO = $this->preguntaDAO;
    $respuestaDAO = $this->respuestaDAO;
    
    $preferencias = $this->preferencias;
    $totalEvaluadores = $this->totalEvaluadores;
    $sumaTotal = 0.0;
    $promedioTotal = 0.0;
    $totalPreguntas = 0;
    
    $idReporte = $this->idReporte;
    $respuestas = null;
    
    //print_r($idReporte);
    
    $params = array("module"=>"encuesta","controller"=>"reporte","action"=>"descarga","rpt"=>$idReporte);
    $urlRepGrupal = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Evaluacion Grupal: <strong><?php echo $encuesta['nombre']; ?></strong></h5>
			</div>
			<div class="panel-body">
			    <div>
			        <h4>
			        	Grupo: <strong><?php echo $grupoE['grupoEscolar']  ?></strong> - 
			        	Evaluadores: <strong><?php echo $totalEvaluadores; ?></strong><br />
			        	Materia: <strong><?php echo $materia["materiaEscolar"]; ?></strong> - 
			        	Docente: <strong><?php echo $docente["apellidos"].", ".$docente["nombres"]  ?></strong>
			        </h4>
			        <a class="btn btn-success" href="<?php echo $urlRepGrupal; ?>">
			            <i class="fa fa-file-pdf-o"></i> Ver Reporte
			        </a>
			        
			        <a href="" class="btn btn-info">
			        	<i class="fa fa-area-chart"></i> Ver Gráfico
			        </a>
			    </div>
			    <hr />
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Pregunta</th>
                            <th>Puntaje</th>
                            <th>Promedio</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($preferencias as $idPregunta => $contenedor) : 
                            //print_r($resultado);print_r("<br /><br />");
                            $pregunta = $preguntaDAO->getPreguntaById($idPregunta);
                            $preferencia = null;
                            $calificacion = null;
                            
                            if ($pregunta->getTipo() == "SS") {
                                $totalPreguntas++;
                                //$opcionMayor = $op
                                $opcionMayor = $contenedor["opcionMayor"];
                                $preferencia = $contenedor["preferencia"];
                                $valorMayor = null;
                                switch ($opcionMayor["tipoValor"]) {
                                    case 'EN':
                                        $valorMayor = $opcionMayor["valorEntero"];
                                        break;
                                    case 'DC':
                                        $valorMayor = $opcionMayor["valorDecimal"];
                                        break;
                                    case 'TX':
                                        $valorMayor = $opcionMayor["valorTexto"];
                                        break;
                                }
                                $puntajeMayor = $valorMayor * $totalEvaluadores;
                                $puntajeObtenido = $preferencia;
                                $calificacion = (10*$puntajeObtenido) / $puntajeMayor;
                                $sumaTotal += $calificacion;
                            }elseif($pregunta->getTipo() == "AB"){
                                $respuestas = $contenedor["abiertas"];
                            }
                            ?>
                        <tr>
                            <td><?php echo $pregunta->getNombre(); ?></td>
                            <td><?php if ($pregunta->getTipo() == "SS") {
                                echo $preferencia;
                            } ?></td>
                            <td><?php if ($pregunta->getTipo() == "SS") {
                                echo sprintf('%.2f', $calificacion);
                            } ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer panel-info">
                <?php echo "Promedio General: <strong>". sprintf('%.2f', $sumaTotal/$totalPreguntas. "</strong>"); ?>
            </div>
		</div>
	</div>
</div>