<?php
	$niveles = $this->niveles;
	$niveles = array();
	$evaluaciones = array();
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
	<div class="container">
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
				<span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="#page-top">CSC México</a>
		</div>
		
		<div id="menu-nav-1" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="hidden">
					<a href="#page-top"></a>
				</li>
				<li class="page-scroll">
					<a href="#modulos">Modulos</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

<header>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<img class="img-responsive" alt="Una imagen aca!" src="<?php echo $this->baseUrl() ?>/public/images/profileDos.png">
				<div class="intro-text">
					<span class="name">Colegio Sagrado Corazón</span>
					<hr class="star-light">
					<span class="skills">Preescolar - Primaria - Secundaria - Preparatoria</span>
				</div>
			</div>
		</div>
	</div>
</header>

<section id="modulos">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Modulos</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-address-book-o"></i> Encuestas
				</a>
				<br />
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"soporte","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-address-book-o"></i> Soporte
				</a>
				<br />
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-address-book-o"></i> Biblioteca
				</a>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</section>

<footer class="text-center">
	<div class="footer-above">
		<div class="container">
			<div class="row">
				<div class="footer-col col-md-4">
					<h3>Dirección</h3>
					<p>numero,calle,<br>colonia, codigo postal</p>
				</div>
				<div class="footer-col col-md-4">
					<h3>En la Web</h3>
					<ul class="list-inline">
						<li>
							<a href="" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
						</li>
						<li>
							<a href="" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
						</li>
						<li>
							<a href="" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
						</li>
					</ul>
				</div>
				<div class="footer-col col-md-4">
					<h3>Acerca de</h3>
					<p>
						
						<a class="btn-social btn-outline" href="https://www.facebook.com/Zazil-Consultores-522417087936523/?fref=ts" target="_blank">
							<i class="fa fa-fw fa-facebook"></i> Zazil Consultores S.A. de C.V. 
						</a> <br>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-below">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					Copyright &copy; Plataforma de Evaluaciones By Zazil Consultores 2016 - 2017
				</div>
			</div>
		</div>
	</div>
</footer>