<?php
	$niveles = $this->niveles;
	$niveles = array();
	$evaluaciones = array();
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
	<div class="container">
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
				<span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="#page-top">CSC México</a>
		</div>
		
		<div id="menu-nav-1" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="hidden">
					<a href="#page-top"></a>
				</li>
				<li class="page-scroll">
					<a href="#login">Login</a>
				</li>
				<li class="page-scroll">
					<a href="#modulos">Modulos</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

<header>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<img class="img-responsive" alt="Una imagen aca!" src="<?php echo $this->baseUrl() ?>/public/images/profileDos.png">
				<div class="intro-text">
					<span class="name">Colegio Sagrado Corazón</span>
					<hr class="star-light">
					<span class="skills">Preescolar - Primaria - Secundaria - Preparatoria</span>
				</div>
			</div>
		</div>
	</div>
</header>

<section id="login">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<h2>Login</h2>
				<hr class="star-primary" />
			</div>
		</div>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<form action="<?php echo $this->url(array('controller'=>'index', 'action'=>'login')); ?>" class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
					<fieldset>
						<legend>Login</legend>
						<div class="form-group">
							<label for="nickname" class="col-xs-2 control-label">Nickname: </label>
							<div class="col-xs-10">
								<input id="nickname" name="nickname" type="text" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="password" class="col-xs-2 control-label">Password</label>
							<div class="col-xs-10">
								<input id="password" name="password" type="password" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="clave" class="col-xs-2 control-label">Clave</label>
							<div class="col-xs-10">
								<input id="clave" name="clave" type="password" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-xs-offset-2 col-xs-10">
								<button class="btn btn-success">
									<i class="fa fa-user"></i> Login
								</button>
							</div>
						</div>
					</fieldset>
				</form>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</section>

<section id="modulos">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Modulos</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-check"></i> Encuestas
				</a>
				<br />
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"soporte","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-user-circle-o"></i> Soporte Técnico
				</a>
				<br />
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-book"></i> Biblioteca
				</a>
				<br />
				<a class="btn btn-success btn-block btn-outline" href="<?php echo $this->url(array("module"=>"evento","controller"=>"index","action"=>"index"),null,true) ?>">
					<i class="fa fa-birthday-cake"></i> Eventos
				</a>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</section>

<footer class="text-center">
	<div class="footer-above">
		<div class="container">
			<div class="row">
				<div class="footer-col col-md-4">
					<h3>Dirección</h3>
					<p>numero,calle,<br>colonia, codigo postal</p>
				</div>
				<div class="footer-col col-md-4">
					<h3>En la Web</h3>
					<ul class="list-inline">
						<li>
							<a href="" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
						</li>
						<li>
							<a href="" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
						</li>
						<li>
							<a href="" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
						</li>
					</ul>
				</div>
				<div class="footer-col col-md-4">
					<h3>Acerca de</h3>
					<p>
						<a class="btn-social btn-outline" href="https://www.facebook.com/Zazil-Consultores-522417087936523/?fref=ts" target="_blank">
							<i class="fa fa-fw fa-facebook"></i> Zazil Consultores S.A. de C.V. 
						</a> <br>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-below">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					Copyright &copy; Plataforma de Evaluaciones By <a href="https://www.facebook.com/Zazil-Consultores-522417087936523/?fref=ts" target="_blank">Zazil Consultores 2016 - 2017</a>
				</div>
			</div>
		</div>
	</div>
</footer>