<?php 
	$ciclo = $this->ciclo;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"edita","idCiclo"=>$ciclo['idCicloEscolar']),null,true));
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	            <h5 class="panel-title">Detalle del ciclo escolar</h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"ciclos","idPlan"=>$ciclo['idPlanEducativo']), null, true); ?>">
	                    <span class="fa fa-arrow-circle-left"></span> Ciclos Escolares.
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-striped table-condensed">
	                    <thead>
	                    	<tr>
	                    		<th>Ciclo</th>
    	                        <th>Inicio</th>
    	                        <th>Término</th>
    	                        <th>Creación</th>
    	                        <th>Descripción</th>
	                    	</tr>
	                    </thead>
	                    <tbody>
	                        <tr>
	                            <td><?php echo $ciclo['ciclo']; ?></td>
	                            <td><?php echo $ciclo['inicio']; ?></td>
	                            <td><?php echo $ciclo['termino']; ?></td>
	                            <td><?php echo $ciclo['fecha']; ?></td>
	                            <td><?php echo $ciclo['descripcion']; ?></td>
	                        </tr>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-warning">
    		<div class="panel-heading">
	            <h5 class="panel-title">Editar Ciclo Escolar: <strong><?php echo $ciclo['ciclo']; ?></strong></h5>
	        </div>
	        <div class="panel-body">
	            <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded"
	                action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"edita","idCiclo"=>$ciclo['idCicloEscolar']),null,true) ?>">
	                <div class="form-group">
	                        <label class="col-xs-2 control-label" for="ciclo">Ciclo: </label>
	                        <div class="col-xs-10">
	                            <input name="ciclo" class="form-control" type="text" value="<?php echo $ciclo['ciclo']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-xs-2 control-label" for="inicio">Fecha Inicio: </label>
	                        <div class="col-xs-10">
	                            <input name="inicio" class="form-control" type="text" value="<?php echo $ciclo['inicio']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-xs-2 control-label" for="termino">Fecha Termino</label>
	                        <div class="col-xs-10">
	                            <input name="termino" class="form-control" type="text" value="<?php echo $ciclo['termino']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-xs-2 control-label" for="vigente">Ciclo en Curso: </label>
	                        <div class="col-xs-10">
	                            <input name="vigente" type="checkbox" <?php if ($ciclo['vigente'] == 1) echo "checked=''" ?> />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-xs-2 control-label" for="descripcion">Descripcion: </label>
	                        <div class="col-xs-10">
	                            <input name="descripcion" class="form-control" type="text" value="<?php echo $ciclo['descripcion']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <div class="col-xs-offset-2 col-xs-10">
	                            <button class="btn btn-warning" type="submit">
	                                <span class="fa fa-refresh"></span> Actualizar Ciclo Escolar
	                            </button>
	                        </div>
	                    </div>
	            </form>
	        </div>
    	</div>
    </div>
</div>
