<?php 
    $planEstudios = $this->plan;
	$ciclo = $this->ciclo;
	
	$tInicio = new DateTime($ciclo['inicio']);
	$tTermino = new DateTime($ciclo['termino']);
	$tCreacion = new DateTime($ciclo['fecha']);
	
	$params = array("module"=>"encuesta","controller"=>"ciclo","action"=>"ciclos","pl"=>$ciclo['idPlanEducativo']);
	$urlCiclos = $this->url($params,null,true);
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	            <h5 class="panel-title"><strong><i class="fa fa-search"></i></strong> Detalle del ciclo escolar: <strong><?php echo $ciclo['ciclo'] ?></strong></h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-info" href="<?php echo $urlCiclos; ?>">
	                    <span class="fa fa-arrow-circle-left"></span> Ciclos Escolares.
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-striped table-condensed">
	                    <thead>
	                    	<tr>
	                    		<th>Plan Educativo</th>
	                    		<th>Ciclo Escolar</th>
    	                        <th>Descripción</th>
    	                        <th>Inicio</th>
    	                        <th>Término</th>
    	                        <th>Creación</th>
	                    	</tr>
	                    </thead>
	                    <tbody>
	                        <tr>
	                        	<td><?php echo $planEstudios['planEducativo']; ?></td>
	                            <td><?php echo $ciclo['ciclo']; ?></td>
	                            <td><?php echo $ciclo['descripcion']; ?></td>
	                            <td><?php echo $tInicio->format('d-m-Y H:i:s'); ?></td>
	                            <td><?php echo $tTermino->format('d-m-Y H:i:s'); ?></td>
	                            <td><?php echo $tCreacion->format('d-m-Y H:i:s'); ?></td>
	                        </tr>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
    	<div class="panel panel-warning">
    		<div class="panel-heading">
	            <h5 class="panel-title"><strong><i class="fa fa-pencil"></i></strong> Editar Ciclo Escolar: <strong><?php echo $ciclo['ciclo']; ?></strong></h5>
	        </div>
	        <div class="panel-body">
	            <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
	                <div class="form-group">
	                        <label class="col-md-2 control-label" for="ciclo">Ciclo: </label>
	                        <div class="col-md-10">
	                            <input name="ciclo" class="form-control" type="text" value="<?php echo $ciclo['ciclo']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-md-2 control-label" for="inicio">Fecha Inicio: </label>
	                        <div class="col-md-10">
	                            <input name="inicio" class="form-control" type="text" value="<?php echo $ciclo['inicio']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-md-2 control-label" for="termino">Fecha Termino</label>
	                        <div class="col-md-10">
	                            <input name="termino" class="form-control" type="text" value="<?php echo $ciclo['termino']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label for="vigente" class="col-md-2 control-label">Ciclo en Curso: </label>
	                        <div class="col-md-10">
	                            <input name="vigente" type="checkbox" <?php if ($ciclo['vigente'] == 1) echo 'checked="checked"'; ?> />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <label class="col-md-2 control-label" for="descripcion">Descripcion: </label>
	                        <div class="col-md-10">
	                            <input name="descripcion" class="form-control" type="text" value="<?php echo $ciclo['descripcion']; ?>" />
	                        </div>
	                    </div>
	                    
	                    <div class="form-group">
	                        <div class="col-md-offset-2 col-md-10">
	                            <button class="btn btn-warning" type="submit">
	                                <span class="fa fa-refresh"></span> Actualizar Ciclo Escolar
	                            </button>
	                        </div>
	                    </div>
	            </form>
	        </div>
    	</div>
    </div>
</div>
