<?php
    //$ciclosEscolares = $this->ciclosEscolares;
    //$nivelesEscolares = $this->nivelesEscolares;
    //$niveles = array();
    //$evaluaciones = array();
    $ubicaciones = $this->ubicaciones;
    $usuarios = $this->usuarios;
    $inventarioActivo = false;
    $consultaActiva = true;
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
                <span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url(array("module"=>"default", "controller"=>"index", "action"=>"index"),null,true); ?>">
                Homepage
            </a>
        </div>
        
        <div id="menu-nav-1" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#login">Login</a>
                </li>
                <?php if ($inventarioActivo) { ?>
                <li class="page-scroll">
                    <a href="#inventario">Inventario</a>
                </li>
                <?php }  ?>
                <?php if ($consultaActiva) { ?>
                <li class="page-scroll">
                    <a href="#consulta">Consulta</a>
                </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>

<header id="login">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Login</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <form class="form-horizontal" action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"login"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
                    <fieldset>
                        <legend>Acceso al Sistema:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="usuario">Usuario: </label>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" name="usuario" placeholder="Usuario..." autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="password">Password: </label>
                            <div class="col-xs-10">
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    Acceder
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>
</header>
<?php if ($inventarioActivo) { ?>
<section id="evaluaciones">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Evaluaciones</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>
</section>
<?php } ?>

<?php if ($consultaActiva) { ?>
<section id="consulta">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Consulta de Soporte</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div id="form-eval" class="form-horizontal">
                    <fieldset>
                        <legend>Realizar evaluación:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="ciclo">Usuario: </label>
                            <div class="col-xs-10">
                                <select id="ciclo" class="form-control" name="usuario">
                                    <?php foreach ($usuarios as $index => $usuario) : ?>
                                    <option><?php echo $usuario['Usuario']; ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="ubicacion">Ubicación: </label>
                            <div class="col-xs-10">
                                <select id="nivel" class="form-control" name="ubicacion">
                                    <?php foreach ($ubicaciones as $index => $ubicacion) : ?>
                                        <option> <?php echo $ubicacion['ubicacion']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button id="btnConsult" class="btn btn-success" type="button">
                                    <i class="fa fa-search"></i> Consultar
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>  
</section>
<?php } ?>

<footer class="text-center">
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Plataforma de Evaluaciones By Zazil Consultores 2016 - 2017
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="<?php echo $this->baseUrl()."/public" ?>/js/helpers/homepage.js"></script>