<?php 
    $auth = Zend_Auth::getInstance();
?>
<br /><br />
<div id="view-content">
	<p>View script for controller <b>Index</b> and script/action name <b>login</b></p>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Login en el sistema!</h5>
			</div>
			<div class="panel-body">
				<div>Zend Auth nos proporciona:</div>
				<div>
					<?php 
					   $datos = $auth->getStorage();
					   print_r($datos->read());
					?>
				</div>
			</div>
		</div>
	</div>
</div>