<?php 
    $auth = Zend_Auth::getInstance();
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Login en el sistema!</h5>
			</div>
			<div class="panel-body">
				<div>Zend Auth nos proporciona:</div>
				<div>
					<?php
					   $identity = $auth->getIdentity();
					   //$datos = $auth->getStorage();
					   // print_r($datos->read());
					   //print_r($identity['user']);
					?>
				</div>
			</div>
		</div>
	</div>
</div>