<?php
    $subdivisiones = $this->subdivisiones;
    
    $params = array("module"=>"biblioteca","controller"=>"subdivision","action"=>"alta");
    $urlAltaSubdivision = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Subdivisiones Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaSubdivision; ?>">
			            <i class="fa fa-plus"></i> Nueva Subdivisión
			        </a>
			    </div>
			    <hr />
			    <div>
			        <table id="tSubdivision" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Subdivisión</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                    <th>Editar</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($subdivisiones as $subdivision) :
			                $urlAdminSubdivision = $this->url(array('module'=>'biblioteca','controller'=>'subdivision','action'=>'admin','sdv'=>$subdivision['idSubdivision']));
			                ?>
			                <tr>
			                    <td><?php echo $subdivision["subdivision"]; ?></td>
			                    <td><?php echo $subdivision["codigo"]; ?></td>
			                    <td><?php echo $subdivision["creacion"]; ?></td>
			                    <td>
			                    	<a class="btn btn-link" href="<?php echo $urlAdminSubdivision; ?>">
										<i class="fa fa-edit"></i> 
									</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
</div>

<script>

	$().ready(function(){
		//console.log("jQuery Activo!!");

		$("#tSubdivision").DataTable();
		
	});
		
</script>