<?php
    $evento = $this->evento;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Consulta de Asistentes en Evento: <strong><?php echo $evento['nombre']; ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<div class="form-group">
							<label for="nombres" class="control-label col-md-2">Nombres: </label>
							<div class="col-md-5">
								<input id="nombres" name="nombres" class="form-control" type="text" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="apaterno" class="control-label col-md-2">Apellido Paterno: </label>
							<div class="col-md-5">
								<input id="apaterno" name="apaterno" class="form-control" type="text" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="amaterno" class="control-label col-md-2">Apellido Materno: </label>
							<div class="col-md-5">
								<input id="amaterno" name="amaterno" class="form-control" type="text" />
							</div>
						</div>
					</div>
				</div>
				<hr />
				<div>
					<table id="tResults" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombres</th>
								<th>A. Paterno</th>
								<th>A. Materno</th>
								<th>E-Mail</th>
								<th>Estatus</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$().ready(function(){
		var appname = "/colegio/evento";
		var url = window.location.origin + appname;
		var evento = <?php echo $evento['id'] ?>;
		
		$("#nombres").on('blur', function(){
			constructQuery();
		});
		$("#apaterno").on('blur', function() {
			constructQuery();
		});
		$("#amaterno").on('blur', function() {
			constructQuery();
		});

		function constructQuery() {

			//var evento = $("#evento").val();
			var nombres = $("#nombres").val();
			var apaterno = $("#apaterno").val();
			var amaterno = $("#amaterno").val();

			var params = "/ev/"+evento;
			
			if(nombres != ""){
				params += "/ns/"+nombres;
			}
			if(apaterno != ""){
				params += "/ap/"+apaterno;
			}
			if(amaterno != ""){
				params += "/am/"+amaterno;
			}
			//console.log(params);

			var urlQuery = encodeURI(url + "/json/findreg" + params);
			console.log(urlQuery);
			$.ajax({
                url: urlQuery,
                dataType: "json",
                success: function(data){
                    console.dir(data);

                    var tbody = $("#tResults").find('tbody');
                    tbody.empty();
                    $.each(data, function(i,item){

                        var urlDetails = url + "/asistente/detalle/as/"+item.id;

                    	var alink = $("<a></a>")
                        .attr("class","btn btn-link")
                        .attr("href",urlDetails)
                        .attr("target","_blank")
                        .text("Detalle");
                        
                    	tbody.append($('<tr>').
                        	append($('<td>').append(item.nombres)).
                            append($('<td>').append(item.apaterno)).
                            append($('<td>').append(item.amaterno)).
                            append($('<td>').append(item.email)).
                            append($('<td>').append(alink))
                        );
                    });
                    
                }
            });
		}
	});
</script>