<?php
    $deporte = $this->deporte;    
    
    $params = array('module'=>'deportes','controller'=>'deporte','action'=>'index');
    $urlDeportes = $this->url($params,null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Editar Deporte</h5>
			</div>
			<div class="panel-body">
				<div>
					<a href="<?php echo $urlDeportes; ?>" class="btn btn-info">
						<i class="fa fa-arrow-circle-left"></i> Volver a Deportes
					</a>
				</div>
				<hr />
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<fieldset>
							<legend>Actualizar Deporte</legend>
							
							<div class="form-group">
    							<label for="deporte" class="control-label col-md-2">Deporte: </label>
    							<div class="col-md-10">
    								<input name="deporte" type="text" class="form-control" value="<?php echo $deporte['deporte'] ?>" />
    							</div>
    						</div>
    						
    						<div class="form-group">
    							<label for="descripcion" class="control-label col-md-2">Descripción: </label>
    							<div class="col-md-10">
    								<input name="descripcion" type="text" class="form-control" value="<?php echo $deporte['descripcion'] ?>" />
    							</div>
    						</div>
    						    						
    						<div class="form-group">
    							<div class="col-md-offset-2 col-md-10">
    								<button class="btn btn-warning" type="submit">
    									<i class="fa fa-refresh"></i> Actualizar Deporte
    								</button>
    							</div>
    						</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

