<?php
    $deportes = $this->deportes;
    
    $params = array('module'=>'deportes','controller'=>'dashboard','action'=>'actions');
    $urlActions = $this->url($params,null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Deportes Registrados en el Sistema</h5>
			</div>
			<div class="panel-body">
				<div>
					<a href="<?php echo $urlActions; ?>" class="btn btn-info">
						<i class="fa fa-arrow-circle-left"></i> Ir a Acciones
					</a>
				</div>
				<hr />
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Deporte</th>
								<th>Descripción</th>
								<th>Creación</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($deportes as $deporte) {
							     $params = array('module'=>'deportes','controller'=>'deporte','action'=>'configdep','dep'=>$deporte['idDeporte']);
							     $urlConfigDeporte = $this->url($params,null,true);
							    ?>
							<tr>
								<td>
									<a href="<?php echo $urlConfigDeporte; ?>" class="btn btn-link">
										<i class="fa fa-gears"></i> <?php echo $deporte['deporte']; ?>
									</a>
								</td>
								<td><?php echo $deporte['descripcion']; ?></td>
								<td><?php echo $deporte['creacion']; ?></td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Nuevo Deporte en el Sistema</h5>
			</div>
			<div class="panel-body">
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<fieldset>
							<legend>Nuevo Deporte</legend>
							
							<div class="form-group">
    							<label for="deporte" class="control-label col-md-2">Deporte: </label>
    							<div class="col-md-10">
    								<input name="deporte" type="text" class="form-control" placeholder="Deporte..." />
    							</div>
    						</div>
    						
    						<div class="form-group">
    							<label for="descripcion" class="control-label col-md-2">Descripción: </label>
    							<div class="col-md-10">
    								<input name="descripcion" type="text" class="form-control" placeholder="Descripción..." />
    							</div>
    						</div>
							
    						<div class="form-group">
    							<div class="col-md-offset-2 col-md-10">
    								<button class="btn btn-success" type="submit">
    									<i class="fa fa-save"></i> Guardar Deporte
    								</button>
    							</div>
    						</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>