<?php
	$plan = $this->plan;
	$formulario = $this->formulario;
	$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"edita","idPlan"=>$plan["idPlanEducativo"]),null,true));
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-default">
    		<div class="panel-heading">
	            Detalle de Plan de Estudios: <strong><?php echo $plan["planEducativo"] ?></strong>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"index"),null,true) ?>">
	                    <span class="fa fa-arrow-circle-left"></span> Regresar a Planes de Estudio
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-striped table-condensed">
	                    <thead>
	                        <tr>
	                            <th>Plan Educativo</th>
	                            <th>Vigente</th>
	                            <th>Creación</th>
	                            <th>Descripción</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <tr>
	                            <td><?php echo $plan["planEducativo"]; ?></td>
	                            <td><?php echo ($plan["vigente"] == 1) ? "Vigente" : "No Vigente" ; ?></td>
	                            <td><?php echo $plan["fecha"]; ?></td>
	                            <td><?php echo $plan["descripcion"]; ?></td>
	                        </tr>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-warning">
    		<div class="panel-heading">
	            <h5 class="panel-title">Editar Plan de Estudios</h5>
	        </div>
	        <div class="panel-body">
	            <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded"
	                    action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"edita","idPlan"=>$plan["idPlanEducativo"]),null,true) ?>">
	                <div class="form-group">
	                    <label for="planEducativo" class="col-xs-2 control-label">Plan de Estudios: </label>
	                    <div class="col-xs-10">
	                        <input class="form-control" type="text" name="planEducativo" placeholder="Nombre plan estudios" autofocus="" value="<?php echo $plan["planEducativo"] ?>" />
	                    </div>
	                </div>
	                
	                <div class="form-group">
	                    <label for="descripcion" class="col-xs-2 control-label">Descripción: </label>
	                    <div class="col-xs-10">
	                        <input class="form-control" type="text" name="descripcion" placeholder="Descripción" value="<?php echo $plan["descripcion"] ?>" />
	                    </div>
	                </div>
	                
	                <div class="form-group">
	                    <label class="col-xs-2 control-label" for="vigente">Vigente?: </label>
	                    <div class="col-xs-10">
	                        <label>
	                            <div class="checkbox">
	                                <span class="cheked">
	                                    <input name="vigente" type="checkbox" name="vigente" <?php echo ($plan["vigente"] == 1) ? "checked=''" : "" ;  ?> />
	                                </span>
	                            </div>
	                        </label>
	                    </div>
	                </div>
	                
	                <div class="form-actions">
	                    <div class="pull-right">
	                        <button class="btn btn-warning" type="submit" >
	                            <span class="fa fa-refresh"></span> Actualizar Plan
	                        </button>
	                    </div>
	                </div>
	            </form>
        </div>
    	</div>
    </div>
</div>
