<?php
	$formulario = $this->formulario;
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<div class="row">
    <div class="col-md-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
                <h5 class="panel-title">Nuevo Plan de Estudios</h5>
            </div>
            <div class="panel-body">
                <div>
                    <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"index"),null,true) ?>">
                        <span class="fa fa-arrow-left"></span> Planes de Estudios
                    </a>
                    <?php if(!is_null($messageSuccess)){ ?>
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <?php } ?>
                </div>
                <hr />
                <div>
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group">
                            <label for="planEducativo" class="col-md-2 control-label">Plan de Estudios: </label>
                            <div class="col-md-10">
                                <input class="form-control" type="text" name="planEducativo" placeholder="Nombre plan estudios" autofocus="autofocus" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="descripcion" class="col-md-2 control-label">Descripción: </label>
                            <div class="col-md-10">
                                <input class="form-control" type="text" name="descripcion" placeholder="Descripción" />
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="col-md-2 control-label" for="vigente">Vigente?: </label>
                            <div class="col-md-10">
                                <div class="checkbox">
                                    <span class="cheked">
                                        <input name="vigente" type="checkbox" name="vigente" />
                                    </span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                <button type="submit" class="btn btn-success">
                                    <span class="fa fa-save"></span> Guardar Plan
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    	</div>
    </div>
</div>
