<?php
	$planes = $this->planes;
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-default">
    		<div class="panel-heading">
	            <span></span>
	            <h5 class="panel-title">Consulta de Planes de Estudio</h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"alta"),null,true) ?>">
	                    <span class="fa fa-plus-circle"></span> Agregar Plan de Estudios 
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-striped table-condensed">
	                    <thead>
	                        <tr>
	                            <th>Plan de Estudios</th>
	                            <th>Vigente</th>
	                            <th>Ciclos Escolares</th>
	                            <th>Configurar</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <?php foreach ($planes as $plan) : ?>
	                        <tr>
	                            <td><?php echo $plan["planEducativo"] ?></td>
	                            <td><?php echo ($plan["vigente"] == 1 ) ?  "Vigente" : "No Vigente" ; ?></td>
	                            <td>
	                                <a class="btn btn-info btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"ciclo","action"=>"ciclos","idPlan"=>$plan["idPlanEducativo"],),null,true) ?>">
	                                    <span class="fa fa-search"></span> Ciclos Escolares
	                                </a>
	                            </td>
	                            <td>
	                                <a class="btn btn-warning btn-block" href="<?php echo $this->url(array("module"=>"encuesta", "controller"=>"plan", "action"=>"admin", "idPlan"=>$plan["idPlanEducativo"])) ?>">
	                                    <span class="fa fa-cogs"></span> Configurar
	                                </a>
	                            </td>
	                        </tr>
	                        <?php endforeach ?>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
        
    </div>
</div>
