<?php
	$grupo = $this->grupo;
	$grado = $this->grado;
	$nivel = $this->nivel;
	$materiasGrupo = $this->materiasGrupo;
	$materiasGrado = $this->materiasGrado;
	$materiasDisponibles = $this->materiasDisponibles;
    
	$asignacionDAO = $this->asignacionDAO;
    $docenteDAO = $this->docenteDAO;
    
    $params = array("module"=>"encuesta","controller"=>"grupoe","action"=>"consulta","gr"=>$grado['idGradoEducativo']);
    $urlGrupos = $this->url($params,null,true);
    
    $params = array("module"=>"encuesta","controller"=>"conjunto","action"=>"conjuntos","gpo"=>$grupo['idGrupoEscolar']);
    $urlConjuntos = $this->url($params,null,true);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Grado: <strong><?php echo $grado['gradoEducativo']; ?></strong> >> Grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong></h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-link" href="<?php echo $urlGrupos; ?>">
						<i class="fa fa-arrow-circle-left"></i> Regresar a grupos
					</a>
					
					<a class="btn btn-link" href="<?php echo $urlConjuntos; ?>">
						<i class="fa fa-external-link-square"></i> Ir a conjuntos
					</a>
				</div>
				<hr />
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"asociarm","gpo" => $grupo['idGrupoEscolar']),null,true) ?>" >
						<div class="form-group">
							<label class="col-xs-2 control-label" for="idMateriaEscolar">Materias Disponibles: </label>
							<div class="col-xs-10">
								<select name="idMateriaEscolar" class="form-control">
									<?php foreach ($materiasDisponibles as $materiaDisponible) : ?>
									<option value="<?php echo $materiaDisponible["idMateriaEscolar"] ?>"><?php echo $materiaDisponible["materiaEscolar"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-xs-offset-2 col-xs-10">
								<button class="btn btn-warning" type="submit">
									<i></i> Asociar Materia a Grupo
								</button>
							</div>
						</div>
					</form>
				</div>				
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong></h5>
			</div>
			<div class="panel-body">				
				<div>
					<table class="table table-condensed table-striped">
						<thead>
							<tr>
								<th>Nivel</th>
								<th>Grado</th>
								<th>Grupo</th>
								<th>Materia</th>
								<th>Docente</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($materiasGrupo as $materiaGrupo) : 
							    //print_r($materiaAsociada["idMateriaEscolar"]);
							    ?>
							<tr>
								<td><?php echo $nivel['nivelEducativo'] ?></td>
								<td><?php echo $grado['gradoEducativo']; ?></td>
								<td><?php echo $grupo['grupoEscolar'] ?></td>
								<td><?php echo $materiaGrupo['materiaEscolar'] ?></td>
								<td>
								    <?php if ($asignacionDAO->existeDocenteEnAsignacion($grupo['idGrupoEscolar'], $materiaGrupo['idMateriaEscolar']) ) {
								        $params = array('idGrupoEscolar'=>$grupo['idGrupoEscolar'],'idMateriaEscolar'=>$materiaGrupo['idMateriaEscolar']);
								        $asignacion = $asignacionDAO->getAsignacionByParams($params);
								        $docente = $docenteDAO->getDocenteById($asignacion["idDocente"]);
                                        //$registro = $registroDAO->getRegistroById($asignacion["idRegistro"]);
                                        echo $docente["apellidos"]." ".$docente["nombres"];
									}else{ ?>
								        <a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"asocdoc","gpo"=>$grupo['idGrupoEscolar'],"mat"=>$materiaGrupo["idMateriaEscolar"]),null,true) ?>">
                                            <i class="fa fa-plus-circle"></i> Asociar Docente
                                        </a>
								    <?php } ?>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>