<?php
    $grupo = $this->grupo;
    $materia = $this->materia;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h4 class="panel-title">
				Grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong>
			</h4>
		</div>
		<div class="panel-body">
			<?php //echo $formulario; ?>
			<div>
			   <h4>Asociando Materia: <strong><?php echo $materia['materiaEscolar'] ?></strong> con Docente</h4>
			   <hr />
			   <div class="form-horizontal">
                   <div class="form-group">
                       <label for="nombres" class="col-md-2 control-label">Nombres:</label>
                       <div class="col-md-10">
                           <input id="nombres" name="nombres" class="form-control" autofocus="autofocus" />
                       </div>
                   </div>
                   
                   <div class="form-group">
                       <label for="apellidos" class="col-md-2 control-label">Apellidos: </label>
                       <div class="col-md-10">
                           <input id="apellidos" name="apellidos" class="form-control" autofocus="autofocus" />
                       </div>
                   </div>
               </div>
			</div>
			<hr />
			<div>
			    <table id="docentes" class="table table-striped table-condensed">
			        <thead>
			            <tr>
			                <th>Nombres</th>
			                <th>Apellidos</th>
			                <th>Asociar</th>
			            </tr>
			        </thead>
			        <tbody>
			        </tbody>
			    </table>
			</div>
		</div>
	</div>
</section>
<script>
    $().ready(function(){
        var appname = "/colegio/encuesta";
        var url = window.location.origin + appname;
        
        $("#nombres, #apellidos").on('blur', function(){
            console.log("Saliendo del input!!");
            var valor = $(this).val();
            console.log(valor);
            var nombres = $("#nombres").val();
            var apellidos = $("#apellidos").val();
            
            if(valor != ""){
				var complement = '';
				if(nombres != ""){
					complement += '/nombres/'+nombres;
				}

				if(apellidos != ""){
					complement += '/apellidos/'+nombres;
				}

				if(complement != ''){
					complement = encodeURI(complement); 
				}
                
                //var urlDocentes = "/param/"+valor;
                var urlQueryDocentes = url + "/json/docentes" + complement;
                
                var idMateria = <?php echo $materia['idMateriaEscolar']; ?>;
                var idGrupo = <?php echo $grupo['idGrupoEscolar']; ?>;
                
                console.log(urlQueryDocentes);
                
                $.ajax({
                    url: urlQueryDocentes,
                    dataType: "json",
                    success: function(data){
                        console.dir(data);
                        var tbody = $("#docentes").find('tbody'); 
                        tbody.empty();
                        
                        $.each(data, function(index, value){
                            var link = $("<a />").attr("class", "btn btn-success");
                            var urlLink = url + "/grupoe/asociarmd/gpo/"+idGrupo+"/mat/"+idMateria+"/doc/"+value.idDocente;
                            //console.log(urlLink);
                            link.attr("href", urlLink).text("Asociar");
                            
                            tbody.append($('<tr>').
                                append($('<td>').append(value.nombres)).
                                append($('<td>').append(value.apellidos)).
                                append($('<td>').append(link)) );
                        });
                        /* */
                    }
                });
            }
        });
        
        
        
    });
</script>
