<?php
    $grupo = $this->grupo;
    $materia = $this->materia;
	
	$formulario = $this->formulario;
	
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h4 class="panel-title">
				Grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong>
			</h4>
		</div>
		<div class="panel-body">
			<?php //echo $formulario; ?>
			<div>
			   <h4>Asociando Materia: <strong><?php echo $materia['materiaEscolar'] ?></strong> con Docente</h4>
			   <hr />
			   <div class="form-horizontal">
                   <div class="form-group">
                       <label class="col-md-2 control-label">Materia:</label>
                       <div class="col-md-10">
                           <label class="control-label"><?php echo $materia['materiaEscolar']; ?></label>
                       </div>
                   </div>
                   
                   <div class="form-group">
                       <label class="col-md-2 control-label">Docente: </label>
                       <div class="col-md-10">
                           <input id="docente" class="form-control" autofocus="autofocus" />
                       </div>
                   </div>
               </div>
			</div>
			<hr />
			<div>
			    <table id="docentes" class="table table-striped table-condensed">
			        <thead>
			            <tr>
			                <th>Nombres</th>
			                <th>Apellidos</th>
			                <th>Asociar</th>
			            </tr>
			        </thead>
			        <tbody>
			        </tbody>
			    </table>
			</div>
		</div>
	</div>
</section>
<script>
    $().ready(function(){
        var appname = "/colegio/encuesta";
        var url = window.location.origin + appname;
        
        $("#docente").on('blur', function(){
            console.log("Saliendo del input!!");
            var valor = $(this).val();
            console.log(valor);
            
            if(valor != ""){
                var urlDocentes = "/param/"+valor;
                var urlQueryDocentes = url + "/json/docentes" + urlDocentes;
                var idMateria = <?php echo $materia['idMateriaEscolar']; ?>;
                var idGrupo = <?php echo $grupo['idGrupoEscolar']; ?>;
                
                console.log(urlQueryDocentes);
                
                $.ajax({
                    url: urlQueryDocentes,
                    dataType: "json",
                    success: function(data){
                        
                        console.dir(data);
                        var tbody = $("#docentes").find('tbody'); 
                        tbody.empty();
                        
                        $.each(data, function(i,item){
                            var link = $("<a />").attr("class", "btn btn-success");
                            var urlLink = url + "/grupoe/asociarmd/gpo/"+idGrupo+"/mat/"+idMateria+"/doc/"+item.idRegistro;
                            //console.log(urlLink);
                            link.attr("href", urlLink).text("Asociar");
                            
                            tbody.append($('<tr>').
                                append($('<td>').append(item.nombres)).
                                append($('<td>').append(item.apellidos)).
                                append($('<td>').append(link)) );
                        });
                        /* */
                    }
                });
            }
        });
        
        
        
    });
</script>
