<?php 
	$ciclo = $this->ciclo;
	$nivel = $this->nivel;
	$grado = $this->grado;
	$grupos = $this->grupos;
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Busqueda de Grupos en Nivel: <strong><?php echo $nivel['nivelEducativo']; ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","gr"=>$grado['idGradoEducativo']), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar al Grado: <strong><?php echo $grado['gradoEducativo']; ?></strong>.
			</a><br /><br />
			<?php echo $this->formulario; ?>
			
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Ciclo</th>
    					<th>Nivel</th>
    					<th>Grado</th>
    					<th>Configurar</th>
    					<th>Consulta</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($grupos as $grupo) : 
					    $urlGrupo = $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"index","gpo"=>$grupo['idGrupoEscolar']),null,true);
					    ?>
					<tr>
						<td><?php echo $ciclo['ciclo']; ?></td>
						<td><?php echo $nivel['nivelEducativo']; ?></td>
						<td><?php echo $grado['gradoEducativo']; ?></td>
						<td>
						    <a class="btn btn-link" href="<?php echo $urlGrupo; ?>">
						        <i class="fa fa-cog"></i> Configurar
						    </a>
						</td>
						<td>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"admin","gpo"=>$grupo['idGrupoEscolar']),null,true) ?>">
								<span class="glyphicon glyphicon-search"></span> Grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong>
							</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<br />
		</div>
	</div>
	
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/mencuesta/consultaGrupos.js"></script>