<?php
	$nivel = $this->nivel;
	$grado = $this->grado;
	$grupo = $this->grupo;
	$materias = $this->materias;
	$profesores = $this->profesores;
	$docente = null;
	$materiaD = null;
	
	$params = array("module"=>"encuesta","controller"=>"conjunto","action"=>"conjuntos","gpo"=>$grupo['idGrupoEscolar']);
    $urlConjuntos = $this->url($params,null,true);
?>
<section class="row">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h3 class="panel-title">
				Nivel: <strong><?php echo $nivel['nivelEducativo']; ?></strong> >> Grado: <strong><?php echo $grado['gradoEducativo'] ?></strong> >> Grupo: <strong><?php echo $grupo['grupoEscolar'] ?></strong>
			</h3>
		</div>
		<div class="panel-body">
			<a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"admin","gpo"=>$grupo['idGrupoEscolar']), null, true); ?>">
				<span class="glyphicon glyphicon-chevron-left"></span> Regresar a Grupo: <strong><?php echo $grupo['grupoEscolar']; ?></strong>
			</a>
			<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"aencuesta","idGrupo"=>$grupo['idGrupoEscolar']), null, true); ?>">
				<span class="glyphicon glyphicon-plus"></span> Asociar Encuesta con Materia-Docente.
			</a>
			<a target="_blank" class="btn btn-link" href="<?php echo $urlConjuntos; ?>">
			    <i class="fa fa-external-link-square"></i> Ir a Conjuntos
			</a>
			<br />
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Materia</th>
    					<th>Docente</th>
    					<th>Consultar</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($materias as $materia) : ?>
					<tr>
						<td><?php echo $materia['materiaEscolar']; ?></td>
						<td>
							<?php
								if(!empty($profesores) && key_exists($materia['idMateriaEscolar'], $profesores)){
									$profesor = $profesores[$materia['idMateriaEscolar']];
									$docente = $profesor["profesor"]; 
									$materiaD = $profesor["materia"];
									echo $docente['apellidos'] . ", " . $docente['nombres'];
								}else{?>
											<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"asociarp","idGrupo"=>$grupo['idGrupoEscolar'],"idMateria"=>$materia['idMateriaEscolar']),null,true) ?>">
												<span class="glyphicon glyphicon-plus"></span> Asignar profesor
											</a>
							<?php } ?>
						</td>
						<td>
							<?php if(!empty($profesores) && key_exists($materia['idMateriaEscolar'], $profesores)){ 
								$obj = $profesores[$materia['idMateriaEscolar']];
								?>
							<a class="btn btn-link" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grupoe","action"=>"encuestas","idAsignacion" =>$obj["idAsignacionGrupo"]),null,true) ?>">
								<span class="glyphicon glyphicon-search"></span> Encuestas
							</a>
							<?php } ?>
						</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</section>