<?php 
	$seccion = $this->seccion;
	//$formulario = $this->formulario;
	//$formulario->setAction($this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"edita","id"=>$seccion->getIdSeccionEncuesta()), null, TRUE));
	
	$urlEncuesta = $this->url(array("module"=>"encuesta","controller"=>"encuesta","action"=>"index"));
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <span class="icon">
                    <i class="icon-search"></i>
                </span>
                <h5 class="panel-title">Detalle Sección</h5>
            </div>
            <div class="panel-body">
                <div>
                    <a class="btn btn-info" href="<?php echo $urlEncuesta; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Encuesta
                    </a>
                </div>
                <hr />
                <div>
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Fecha Creacion</th>
                                <th>Orden</th>
                                <th>Elementos</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?php echo $seccion->getNombre(); ?></td>
                                <td><?php echo $seccion->getFecha(); ?></td>
                                <td><?php echo $seccion->getOrden(); ?></td>
                                <td>
                                    <a class="btn btn-success btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"index","id"=>$seccion->getIdSeccionEncuesta()),null,true) ?>">
                                        <i class="badge"><?php echo $seccion->getElementos() ?></i> x <i class="fa fa-cubes"></i> Elementos 
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <span class="icon">
                    <i class="icon-edit"></i>
                </span>
                <h5 class="panel-title">Editar Sección</h5>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded"
                    action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"editar","id"=>$seccion->getIdSeccionEncuesta()),null,true) ?>">
                    <div class="form-group">
                        <label for="nombre" class="col-xs-2 control-label">Nombre Sección:</label>
                        <div class="col-xs-10">
                            <input class="form-control" type="text" name="nombre" value="<?php echo $seccion->getNombre() ?>" />
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-xs-offset-2 col-xs-10">
                            <button class="btn btn-warning" type="submit">
                                <i class="fa fa-repeat"></i> Actualizar Sección
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
</div>