<?php 
	$encuesta = $this->encuesta;
	$seccion = $this->seccion;
	$elementos = $this->elementos;
	$tipo = Zend_Registry::get("tipo");
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">
                    Grupos y preguntas de la sección: <strong><?php echo $seccion->getNombre(); ?></strong>
                </h5>
            </div>
            <div class="panel-body">
                <div>
                    <a class="btn btn-info" href="<?php echo $this->url(array("module" => "encuesta", "controller" => "encuesta", "action" => "secciones", "id" => $encuesta->getIdEncuesta()), null, true); ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Secciones
                    </a>
                    <a class="btn btn-warning" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"seccion","action"=>"admin","id"=>$seccion->getIdSeccionEncuesta()), null, true) ?>">
                        <i class="fa fa-cog"></i> Administrar Sección
                    </a>
                    <a class="btn btn-success" href="<?php echo $this->url(array("module" => "encuesta", "controller" => "grupo", "action" => "alta", "id" => $seccion->getIdSeccionEncuesta()), null, true); ?>">
                        <i class="fa fa-plus"></i> Agregar grupo
                    </a>
                    <a class="btn btn-success" href="<?php echo $this->url(array("module" => "encuesta", "controller" => "pregunta", "action" => "alta", "idSeccion" => $seccion->getIdSeccionEncuesta()), null, true); ?>">
                        <i class="fa fa-plus"></i> Agregar pregunta
                    </a>
                </div>
                <hr />
                <div>
                    <?php if(!is_null($elementos) && count($elementos)) { ?>
                    <table class="table table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>Elemento</th>
                                <th>Nombre</th>
                                <th>Orden</th>
                                <th>Tipo Pregunta(s)</th>
                                <th>Creación</th>
                                <th>Administrar</th>
                            </tr>
                        </thead>
                        <?php foreach ($elementos as $elemento) : 
                            $t = ($elemento instanceof Encuesta_Models_Grupo) ? "grupo" : "pregunta";
                            $id = ($elemento instanceof Encuesta_Models_Grupo) ? $elemento->getIdGrupoSeccion() : $elemento->getIdPregunta();
                            $url = $this->url(array("module" => "encuesta", "controller" => $t, "action" => "admin", "id".ucfirst($t) => $id), null, true);
                            ?>
                        <tr>
                            <td><?php echo ucfirst($t); ?></td>
                            <td><?php echo ($elemento instanceof Encuesta_Models_Grupo) ? $elemento->getNombre() : $elemento->getNombre(); ?></td>
                            <td><?php echo $elemento->getOrden(); ?></td>
                            <td><?php echo $tipo[$elemento->getTipo()]; ?></td>
                            <td><?php echo $elemento->getFecha(); ?></td>
                            <td>
                                <a class="btn btn-info" href="<?php echo $url; ?>">
                                    <span class="glyphicon glyphicon-cog"></span> Administrar
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </table>
                    <?php }else{ ?>
                        <h3>Esta seccion no contiene grupos ni preguntas.</h3>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
