<?php
    $module = "biblioteca";
    $urlBibliotecaDashboard = $this->url(array("module"=>$module,"controller"=>"dashboard","action"=>"index"),null,true);
?>
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Navegación</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<?php echo $urlBibliotecaDashboard; ?>">CSC Biblioteca</a>
</div>
<!-- /.navbar-header -->