<?php
   $modulo = "biblioteca";
   $urlDashboard = $this->url(array("module"=>$modulo,"controller"=>"dashboard","action"=>"index"),null,true);
   
   
   
   $urlSClasificacion = $this->url(array("module"=>$modulo,"controller"=>"clasificacion","action"=>"index"),null,true);
   $urlSColeccion = $this->url(array("module"=>$modulo,"controller"=>"coleccion","action"=>"index"),null,true);
   $urlSTema = $this->url(array("module"=>$modulo,"controller"=>"tema","action"=>"index"),null,true);
   $urlSIdioma = $this->url(array("module"=>$modulo,"controller"=>"idioma","action"=>"index"),null,true);
   
   $urlResources = $this->url(array("module"=>$modulo,"controller"=>"recurso","action"=>"index"),null,true);
   $urlRLibro = $this->url(array("module"=>$modulo,"controller"=>"libro","action"=>"index"),null,true);
   $urlRMultiMedia = $this->url(array("module"=>$modulo,"controller"=>"multimedia","action"=>"index"),null,true); 
?>
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Busqueda...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="<?php echo $urlDashboard; ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-archive fa-fw"></i> Recursos<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="<?php echo $urlResources; ?>"><i class="fa fa-book"></i> Libros</a>
                    </li>
                    <li>
                        <a href="<?php echo $urlRMultiMedia; ?>"><i class="fa fa-video-camera"></i> Multimedia</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-cogs fa-fw"></i> Configuración<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="<?php echo $urlSClasificacion; ?>"><i class="fa fa-sort-alpha-asc"></i> Clasificación</a>
                    </li>
                    <li>
                        <a href="<?php echo $urlSColeccion; ?>"><i class="fa fa-dropbox"></i> Colección</a>
                    </li>
                    <li>
                        <a href="<?php echo $urlSIdioma; ?>"><i class="fa fa-globe"></i> Idioma</a>
                    </li>
                    <li>
                        <a href="<?php echo $urlSTema; ?>"><i class="fa fa-info-circle"></i> Tema</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->