<?php
    $usuario = $this->usuario;
    $url = $this->url(array('module'=>'biblioteca', 'controller'=>'prestamo','action'=>'user','us'=>$usuario['id']),null,true);
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Registrar pago de multa</h5>
			</div>
			<div class="panel-body">
				<div>
					<a href="<?php echo $url; ?>" class="btn btn-info"><i class="fa fa-chevron-left"></i></a>
					<?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <br />
                    <?php } ?>
				</div>
				<hr />
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded" >
						<div class="form-group">
							<label for="tipoPago" class="control-label col-md-2">Tipo Pago: </label>
							<div class="col-md-5">
								<select name="tipoPago" class="form-control">
									<option id="1">Boucher Caja</option>
									<option id="2">Efectivo</option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="montoPago" class="control-label col-md-2">Monto Pago: </label>
							<div class="col-md-5">
								<input type="text" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-success">
        							<i class="fa fa-save"></i> Guardar
        						</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>