<?php
    $materiales = $this->materiales;
    
    $params = array("module"=>"biblioteca","controller"=>"material","action"=>"alta");
    $urlAltaMaterial = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Materiales Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaMaterial; ?>">
			            <i class="fa fa-plus"></i> Nuevo Material
			        </a>
			    </div>
			    <hr />
			    <div>
			   
			        <table id="tMaterial" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Material</th>
			                    <th>Descripción</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($materiales as $material) : 
			                     $urlAdminMaterial = $this->url(array('module'=>'biblioteca','controller'=>'material','action'=>'admin','mtrl'=>$material['idMaterial']));
			                ?>
			                <tr>
			                    <td><?php echo $material["material"]; ?> </td>
			                    <td><?php echo $material["descripcion"]; ?></td>
			                    <td><?php echo $material["codigo"]; ?></td>
			                    <td><?php echo $material["creacion"]; ?></td>
			                    <td>
			                    	 <a class="btn btn-link" href="<?php echo $urlAdminMaterial; ?>">
										<i class="fa fa-edit"></i> 
									</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			     
			    </div>
			</div>
		</div>
	</div>
</div>

<script>

	$().ready(function(){
		//console.log("jQuery Activo!!");

		$("#tMaterial").DataTable();
		
	});
		
</script>
