<?php
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
    
    $urlEncuestas = $this->url(array("module"=>"encuesta","controller"=>"encuesta","action"=>"index"),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Alta de nueva encuesta</h5>
			</div>
			<div class="panel-body">
				<div>
				    <a class="btn btn-info" href="<?php echo $urlEncuestas; ?>">
				        <i class="fa fa-arrow-circle-left"></i> Regresar a encuestas
				    </a>
				    <?php if(!is_null($messageSuccess)){ ?>
                    
                    <?php } ?>
				</div>
				<hr />
				<div>
				    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded" >
                        <div class="form-group">
                            <label for="nombre" class="control-label col-md-2">Nombre de la Encuesta</label>
                            <div class="col-md-10">
                                <input class="form-control" type="text" name="nombre" placeholder="Nombre Encuesta" autofocus="" required="required" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label col-md-2">Nombre Clave de la encuesta:</label>
                            <div class="col-md-10">
                                <input class="form-control" type="text" name="nombreClave" placeholder="Nombre clave" required="required" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label col-md-2">Descripcion de la Encuesta</label>
                            <div class="col-md-10">
                                <input class="form-control" type="text" name="descripcion" placeholder="Descripcion" required="required" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-success" type="submit">
                                    <i class="fa fa-save"></i> Guardar
                                </button>
                            </div>
                        </div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</div>
