<?php
    $encuesta = $this->encuesta;
    $estatusEncuesta = Zend_Registry::get("estatus");
    
    $urlSecciones = $this->url(array("module"=>"encuesta","controller"=>"encuesta","action"=>"secciones", "id"=>$encuesta->getIdEncuesta()),null,true);
?>
<!-- Detalle Encuesta -->
<div class="row">
    <div class="panel panel-info">
        <div class="panel-heading">
            <span class="icon">
                <i class="icon-cogs"></i>
            </span>
            <h5 class="panel-title">Configurando Encuesta:<strong></strong></h5>
        </div>
        <div class="panel-body">
            <div>
               <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"encuesta","action"=>"index"),null,true) ?>">
                 <span class="fa fa-arrow-circle-left"></span> Regresar a Encuestas
               </a>
               <a class="btn btn-success" href="<?php echo $urlSecciones; ?>">
                   <i class="fa fa-copy"></i> Secciones
               </a>
            </div>
            <hr />
            <div>
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Nombre Clave</th>
                            <th>Descripcion</th>
                            <th>Estatus</th>
                            <th>Creación</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo $encuesta->getNombre() ?></td>
                            <td><?php echo $encuesta->getNombreClave() ?></td>
                            <td><?php echo $encuesta->getDescripcion() ?></td>
                            <td><?php echo $estatusEncuesta[$encuesta->getEstatus()] ?></td>
                            <td><?php echo $encuesta->getFecha() ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Editando Encuesta -->
<div class="row">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <span class="icon">
                <i class="icon-edit"></i>
            </span>
            <h5 class="panel-title">Editar Encuesta</h5>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded"
                  action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"encuestas","action"=>"editar","id"=>$encuesta->getIdEncuesta()),null,true) ?>"  >
                <div class="form-group">
                    <label for="nombre" class="col-xs-2 control-label">Nombre Encuesta</label>
                    <div class="col-xs-10">
                        <input class="form-control" name="nombre" type="text" autofocus="" value="<?php echo $encuesta->getNombre() ?>" />
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="nombreClave" class="col-xs-2 control-label">Nombre Clave de Encuesta</label>
                    <div class="col-xs-10">
                        <input class="form-control" name="nombreClave" type="text" value="<?php echo $encuesta->getNombreClave() ?>" />
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="descripcion" class="col-xs-2 control-label">Descripcion</label>
                    <div class="col-xs-10">
                        <input class="form-control" name="descripcion" type="text" value="<?php echo $encuesta->getDescripcion() ?>" />
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-xs-offset-2 col-xs-10">
                        <button type="submit" class="btn btn-warning">
                            <i class="fa fa-repeat"></i> Actualizar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>