<?php 
    $encuestas = $this->encuestas;
    
    $params = array("module"=>"encuesta","controller"=>"encuestas", "action"=>"alta");
    $urlAltaEncuesta = $this->url($params,null,true);
    
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Encuestas</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-success" href="<?php echo $urlAltaEncuesta; ?>">
                        <i class="fa fa-plus"></i> Nueva Encuesta
                    </a>
                    
				</div>
				<hr />
				<div>
					
				</div>
			    <table class="table table-bordered table-striped">
			    	<thead>
			    		<tr>
			    			<th>N. Clave</th>
			    			<th>Encuesta</th>
			    			<th>Secciones</th>
			    			<th>Descripcion</th>
			    			<th>Creación</th>
			    		</tr>
			    	</thead>
                    <tbody>
                        <?php foreach ($encuestas as $encuesta) : ?>
                        <tr>
                        	<td><?php echo $encuesta['nombreClave']; ?></td>
                        	<td><?php echo $encuesta['nombre']; ?></td>
                        	<td>
                        		<button class="btn btn-link" name="btnQuerySecciones" encuesta="<?php echo $encuesta['idEncuesta']; ?>">
                        			<i class="fa fa-th"></i> Secciones
                        		</button>
                        	</td>
                            <td><?php echo $encuesta['descripcion']; ?></td>
                            <td>
                                <?php echo $encuesta['creacion'] ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
	
	<div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Secciones</h5>
            </div>
            <div class="panel-body">
            	<div>
            		<table id="secciones" class="table table-striped table-condensed">
            			<thead>
            				<tr>
            					<th>Nombre</th>
            					<th>Grupos</th>
            					<th>Orden</th>
            					<th>Elementos</th>
            					<th>Creacion</th>
            				</tr>
            			</thead>
            			<tbody></tbody>
            		</table>
            	</div>
            </div>
        </div>
    </div>
    
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Grupos</h5>
            </div>
            <div class="panel-body">
                <div>
            		<table id="grupos" class="table table-striped table-condensed">
            			<thead>
            				<tr>
            					<th>Nombre</th>
            					<th>Tipo</th>
            					<th>V.Max</th>
            					<th>V.Min</th>
            					<th>Preguntas</th>
            					<th>Orden</th>
            					<th>Elementos</th>
            					<th>Creacion</th>
            				</tr>
            			</thead>
            			<tbody></tbody>
            		</table>
            	</div>
            </div>
        </div>
    </div>
    
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h5 class="panel-title">Preguntas</h5>
            </div>
            <div class="panel-body">
                <div>
                	<table id="preguntas" class="table table-striped table-condensed">
                		<thead>
                			<tr>
                				<th>Pregunta</th>
                				<th>Tipo Pregunta</th>
                				<th>Orden</th>
                				<th>Creación</th>
                			</tr>
                		</thead>
                		<tbody></tbody>
                	</table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl().'/public/js/encuesta/consulta.js' ?>">
</script>
