<?php 
	$categoria = $this->categoria;
	
	$messageFail = $this->messageFail;
	$messageSuccess = $this->messageSuccess;
    $valores = Zend_Registry::get("tipoValor");
    
    $params = array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","ca"=>$categoria["idCategoriasRespuesta"]);
    $urlCategoria = $this->url($params,null,true);
?>
<div class="row">
    <div class="col-md-12">
    	<div class="panel panel-success">
    		<div class="panel-heading">
                <h5 class="panel-title">
                	<i class="fa fa-plus"></i>
                	Nueva Opción en la Categoría: <strong><?php echo $categoria["categoria"]; ?></strong>
                </h5>
            </div>
            <div class="panel-body">
                <div>
                    <a class="btn btn-info" href="<?php echo $urlCategoria; ?>">
                        <span class="fa fa-chevron-left"></span> Regresar a Categoría
                    </a><br />
                    <?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <?php } ?>
                </div>
                <hr />
                <div>
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                        <div class="form-group">
                            <label class="control-label col-md-2" for="nombreOpcion">Opcion: </label>
                            <div class="col-md-10">
                                <input name="nombreOpcion" class="form-control" type="text" placeholder="Nombre opción" autofocus="autofocus" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label col-md-2" for="tipoValor">Tipo Valor: </label>
                            <div class="col-md-10">
                                <select class="form-control" name="tipoValor">
                                    <?php foreach ($valores as $key => $value) : ?>
                                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="valor" class="control-label col-md-2">Valor: </label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="valor" placeholder="Valor texto/decimal/entero" />
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-success" type="submit">
                                    <span class="fa fa-save"></span> Guardar Opción
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    	</div>
    </div>
</div>
