<?php
    $usuario = $this->usuario;
    $copia = $this->copia;
    $recurso = $this->recurso;
    $urlPrestamo = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'alta','us'=>$usuario['id']),null,true);
    
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Prestamos Configurables</h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="row">
						<div class="col-md-2">
							<a href="<?php echo $urlPrestamo; ?>" class="btn btn-info">
								<i class="fa fa-chevron-left"></i> Regresar a Prestamos
							</a>
						</div>
						<div class="col-md-5">
							<h5>Usuario: <strong><?php echo $usuario['nombres'].' '.$usuario['apaterno'].' '.$usuario['amaterno'] ?></strong></h5>
						</div>
						<div class="col-md-5">
							<h5>Recurso: <strong><?php echo $recurso['titulo'] ?></strong></h5>
						</div>
					</div>
				</div>
				<hr />
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<input name="idRecurso" type="hidden" value="<?php echo $recurso['idRecurso'] ?>" />
						<input name="idUsuario" type="hidden" value="<?php echo $usuario['id'] ?>" />
						<div class="form-group">
							<label for="fechaPrestamo" class="control-label col-md-2">Fecha Prestamo</label>
							<div class="col-md-6">
								<input id="fechaPrestamo" name="fechaPrestamo" type="datetime" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="fechaDevolucion" class="control-label col-md-2">Fecha Devolucion</label>
							<div class="col-md-6">
								<input id="fechaDevolucion" name="fechaDevolucion" type="datetime" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-6">
								<button class="btn btn-success">
									<i class="fa fa-arrow-up"></i> Prestar Recurso
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		// $.datepicker.formatDate("yy-mm-dd");
		$("#fechaPrestamo").datepicker({
			dateFormat: "yy-mm-dd",
			changeMonth: true,
			changeYear: true
		});
		$("#fechaDevolucion").datepicker({
			dateFormat: "yy-mm-dd",
			changeMonth: true,
			changeYear: true
		});
	});
</script>

