<?php
    $usuario = $this->usuario;
    $contenedor = $this->contenedor;
    
    $multasUsuario = $this->multasUsuario;
    $linkUser = $this->url(array('module'=>'biblioteca','controller'=>'usuarios','action'=>'user','us'=>$usuario['id']),null,true);
    $linkUsers = $this->url(array('module'=>'biblioteca','controller'=>'usuarios','action'=>'index'),null,true);
    $linkAlta = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'alta','us'=>$usuario['id']),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Prestamos del Usuario</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $linkUser; ?>">
						<i class="fa fa-user"></i> Regresar a usuario
					</a>
					<a class="btn btn-info" href="<?php echo $linkUsers; ?>">
						<i class="fa fa-users"></i> Regresar a usuarios
					</a>
					<a class="btn btn-success" href="<?php echo $linkAlta; ?>">
						<i class="fa fa-plus"></i> Alta Prestamo
					</a>
				</div>
				<hr />
				<div>
				<?php if (!empty($contenedor)) { ?>
				<table class="table table-striped table-condensed">
					<thead>
						<tr>
							<th>Recurso</th>
							<th>Estatus</th>
							<th>Fecha Prestamo</th>
							<th>Fecha Entrega</th>
							<th>Devolver</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($contenedor as $cont) : 
						      $prestamo = $cont['prestamo'];
						      $copia = $cont['copia'];
						      $ejemplar = $cont['ejemplar'];
						      $recurso = $cont['recurso'];
						      $urlDevolucion = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'devolucion','cp'=>$copia['idInventario']),null,true);
						      
						      $fechaPrestamo = new DateTime($prestamo['prestamo']['fechaPrestamo']);
						      $fechaDevolucion = new DateTime($prestamo['prestamo']['fechaDevolucion']);
						?>
						<tr>
							<td><?php echo $recurso['recurso']['titulo']; ?></td>
							<td><?php echo $prestamo['estatus']['estatusPrestamo']; ?></td>
							<td><?php echo $fechaPrestamo->format('Y-m-d'); ?></td>
							<td><?php echo $fechaDevolucion->format('Y-m-d'); ?></td>
							<td>
								<a href="<?php echo $urlDevolucion; ?>" class="btn btn-link">
									<i class="fa fa-refresh"></i> Devolver
								</a>
							</td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
				<?php } else { ?>
				<p style="color: red;">
					<strong>No se encontraron prestamos para el usuario.</strong>
				</p>
				<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h5 class="panel-title">Multas del Usuario</h5>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<div>
					<?php if (!empty($multasUsuario)) { ?>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Ejemplar</th>
								<th>Fecha Multa</th>
								<th>Tiempo Excedido</th>
								<th>Importe Unitario</th>
								<th>Importe Multa</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
					<?php } else { ?>
					<p style="color: red;">
        				<strong>No se encontraron multas para el usuario.</strong>
        			</p>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>