<?php
    $usuario = $this->usuario;
    $nombreUsuario = $usuario['apaterno'].' '.$usuario['amaterno'].', '.$usuario['nombres'];
    $contenedor = $this->contenedor;
    
    $multas = $this->multas;
    $linkUser = $this->url(array('module'=>'biblioteca','controller'=>'usuarios','action'=>'user','us'=>$usuario['id']),null,true);
    $linkUsers = $this->url(array('module'=>'biblioteca','controller'=>'usuarios','action'=>'index'),null,true);
    $linkAlta = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'alta','us'=>$usuario['id']),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Prestamos del Usuario: <strong><?php echo $nombreUsuario; ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $linkUser; ?>">
						<i class="fa fa-user"></i> Regresar a usuario
					</a>
					<a class="btn btn-info" href="<?php echo $linkUsers; ?>">
						<i class="fa fa-users"></i> Regresar a usuarios
					</a>
					<a class="btn btn-success" href="<?php echo $linkAlta; ?>">
						<i class="fa fa-plus"></i> Alta Prestamo
					</a>
				</div>
				<hr />
				<div>
				<?php if (!empty($contenedor)) { ?>
				<table class="table table-striped table-condensed">
					<thead>
						<tr>
							<th>Recurso</th>
							<th>Estatus Prestamo</th>
							<th>Fecha Prestamo</th>
							<th>Fecha Entrega</th>
							<th>Devolver</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($contenedor as $cont) : 
						      $prestamo = $cont['prestamo'];
						      $copia = $cont['copia'];
						      $ejemplar = $cont['ejemplar'];
						      $recurso = $cont['recurso'];
						      $urlDevolucion = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'devolucion','us'=>$usuario['id'] ,'po'=>$prestamo['prestamo']['idPrestamo']),null,true);
						      
						      $fechaPrestamo = new DateTime($prestamo['prestamo']['fechaPrestamo']);
						      $fechaDevolucion = new DateTime($prestamo['prestamo']['fechaDevolucion']);
						?>
						<tr>
							<td><?php echo $recurso['recurso']['titulo']; ?></td>
							<td><?php echo $prestamo['estatus']['estatusPrestamo']; ?></td>
							<td><?php echo $fechaPrestamo->format('Y-m-d'); ?></td>
							<td><?php echo $fechaDevolucion->format('Y-m-d'); ?></td>
							<td>
								<?php if ($prestamo['estatus']['estatusPrestamo'] == 'ENTREGADO') { ?>
								Ejemplar Entregado!!
								<?php } else { ?>
								<a href="<?php echo $urlDevolucion; ?>" class="btn btn-link">
									<i class="fa fa-arrow-down"></i> Devolver
								</a>
								<?php } ?>
							</td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
				<?php } else { ?>
				<p style="color: red;">
					<strong>No se encontraron prestamos para el usuario.</strong>
				</p>
				<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h5 class="panel-title">Multas del Usuario: <strong><?php echo $nombreUsuario; ?></strong></h5>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<div>
					<?php if (!empty($multas)) { ?>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Ejemplar</th>
								<th>Estatus Multa</th>
								<th>Tiempo Excedido</th>
								<th>Importe Unitario</th>
								<th>Importe Multa</th>
								<th>Pagar Multa</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($multas as $multa): 
							//print_r($multa);
							$fechaDevolucion = new DateTime($multa['prestamo']['fechaDevolucion']);
							$fechaVencimiento = new DateTime($multa['prestamo']['fechaVencimiento']);
							$dias = abs($fechaVencimiento->diff($fechaDevolucion)->format('%R%a'));
							
							$urlPagoMulta = $this->url(array('module'=>'biblioteca','controller'=>'multa','action'=>'pago','us'=>$usuario['id'],'mu'=>$multa['multa']['idMulta']),null,true);
							?>
							<tr>
								<td><?php echo $multa['recurso']['titulo']; ?></td>
								<td><?php echo $multa['estatus']['estatus']; ?></td>
								<td><?php echo $dias . ' dia(s)'; ?></td>
								<td><?php echo $multa['tipo']['importeUnitario']; ?></td>
								<td><?php echo $multa['multa']['importe']; ?></td>
								<td>
									<a href="<?php echo $urlPagoMulta; ?>" class="btn btn-danger">
										<i class="fa fa-arrow-up"></i> Pagar Multa
									</a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php } else { ?>
					<p style="color: red;">
        				<strong>No se encontraron multas para el usuario.</strong>
        			</p>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>