<?php

    $serieejemplar = $this->seriejemplar;
    
   // $formulario = $this->formulario;
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
    
    $params = array("module"=>"biblioteca","controller"=>"serieejemplar","action"=>"index");
    $urlSeries= $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Edición de serie.</h5>
			</div>
			<div class="panel-body">
			    <div>
                    <a class="btn btn-info" href="<?php echo $urlSeries; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Series Ejmplar
                    </a><br />
                    <?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <br />
                    <?php } ?>
                </div>
                <hr />
                <div>
                   <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                   
                 		<div class="form-group">
                 			<label for="nombreSerie" class="control-label col-md-2"> Nombre de la serie</label>
                 			<div class="col-md-5">
								<input name="nombreSerie" type="text" class="form-control" value="<?php echo $serieejemplar['nombreSerie']?>" />
							</div>
                 		</div>
                 		
                 		<div class="form-group">
                 			<label for="descripcion" class="control-label col-md-2">Descripción</label>
                 			<div class="col-md-5">
								<input name="descripcion" type="text" class="form-control" value="<?php echo $serieejemplar['descripcion']?>" />
							</div>
                 	</div>
                 		
                 		<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-warning" type="submit">
									<i class="fa fa-refresh"></i> Actualizar Serie Ejemplar
								</button>
							</div>
						</div>
                 	</form>
                </div>
			</div>
		</div>
	</div>
</div>