<?php
    $series = $this->series;
    
    $params = array("module"=>"biblioteca","controller"=>"serieejemplar","action"=>"alta");
    $urlAltaSeries = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Series registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaSeries; ?>">
			            <i class="fa fa-plus"></i> Nueva Serie de Ejemplar
			        </a>
			    </div>
			    <hr />
			    <div>
			    	
			        <table id="tSerieEjemplar" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Nombre de la Serie</th>
			                    <th>Descripción</th>
			                  
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($series as $serie) : 
			              //  print_r($clasificacion); print_r('<br> / <br> /');
			                		$urlAdminSeries = $this->url(array('module'=>'biblioteca','controller'=>'serieejemplar','action'=>'admin','sre'=>$serie['idSeriesEjemplar']));
			                ?>
			                <tr>
			                    <td><?php echo $serie["nombreSerie"]; ?></td>
			                    <td><?php echo $serie["descripcion"]; ?></td>
			                 
			                    <td>
			                    	 <a class="btn btn-link" href="<?php echo $urlAdminSeries; ?>">
										<i class="fa fa-edit"></i> 
									</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			        
			    </div>
			</div>
		</div>
	</div>
</div>
<script>

	$().ready(function(){
		console.log("jQuery Activo!!");

		$("#tSerieEjemplar").DataTable();
		
	});
		
</script>