<?php 
	$categorias = $this->categorias;
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	        	<i class="fa fa-comments fa-fw"></i> Categorias Disponibles
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"alta"), null, true) ?>">
	                    <span class="fa fa-plus-square"></span> Nueva Categoría
	                </a>
	            </div>
	            <br /><br />
	            <table class="table table-striped table-condensed">
	                <thead>
	                    <tr>
	                        <th>Nombre</th>
	                        <th>Descripción</th>
	                        <th>Creación</th>
	                        <th>Configuración</th>
	                    </tr>
	                </thead>
	                <tbody>
	                    <?php foreach ($categorias as $categoria) : 
	                    $params = array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","ca"=>$categoria["idCategoriasRespuesta"]);
	                    $url = $this->url($params, null, true);
	                    ?>
	                    <tr>
	                        <td><?php echo $categoria["categoria"] ?></td>
	                        <td><?php echo $categoria["descripcion"] ?></td>
	                        <td><?php echo $categoria["fecha"] ?></td>
	                        <td>
	                            <a class="btn btn-link btn-block" href="<?php echo $url; ?>">
	                                <span class="fa fa-cogs"></span> Configuración
	                            </a>
	                        </td>
	                    </tr>
	                    <?php endforeach; ?>
	                </tbody>
	            </table>
	        </div>
    	</div>
    </div>
</div>
