<?php 
	$categorias = $this->categorias;
?>
<div class="row">
    <div class="col-xs-12 panel panel-default">
        <div class="panel-heading">
        	<i class="fa fa-comments fa-fw"></i> Categorias Disponibles
        </div>
        <div class="panel-body">
            <div>
                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"alta"), null, true) ?>">
                    <span class="fa fa-plus-square"></span> Nueva Categoría
                </a>
            </div>
            <br /><br />
            <table class="table table-striped table-condensed">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Creación</th>
                        <th>Descripción</th>
                        <th>Configuración</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($categorias as $categoria) : ?>
                    <tr>
                        <td><?php echo utf8_encode($categoria["categoria"]) ?></td>
                        <td><?php echo $categoria["fecha"] ?></td>
                        <td><?php echo utf8_encode($categoria["descripcion"]) ?></td>
                        <td>
                            <a class="btn btn-warning btn-block" 
                                href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","idCategoria"=>$categoria["idCategoriasRespuesta"] ), null, true) ?>">
                                <span class="icon icon-cogs"></span> Configuración
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
