<?php 
	$opciones = $this->opciones;
	$categoria = $this->categoria;
	
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	            <h5 class="panel-title">Opciones de la Categoría: <strong><?php echo $categoria["categoria"] ?></strong></h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"admin","idCategoria"=>$categoria["idCategoriasRespuesta"]),null,true) ?>">
	                    <span class="fa fa-arrow-circle-left"></span> Regresar a Categoría: <strong><?php echo $categoria["categoria"] ?></strong>
	                </a>
	                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"opcion","action"=>"alta","idCategoria"=>$categoria["idCategoriasRespuesta"]), null, true) ?>">
	                    <span class="fa fa-plus-circle"></span> Agregar Opción
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-striped table-condensed">
	                    <thead>
	                        <tr>
	                            <th>Nombre</th>
	                            <th>Orden</th>
	                            <th>Valor</th>
	                            <th>Mayor</th>
	                            <th>Menor</th>
	                            <th>Configurar</th>
	                            <th>Creación</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <?php foreach ($opciones as $opcion) : 
	                        $valor = '';
	                        switch ($opcion['tipoValor']){
	                            case 'EN' :
	                                $valor = $opcion['valorEntero'];
	                                break;
	                            case 'DC' :
	                                $valor = $opcion['valorDecimal'];
	                                break;
	                            case 'ST' :
	                                $valor = $opcion['valorTexto'];
	                                break;
	                        }
	                        $mayor = $categoria['idOpcionMayor'] == $opcion['idOpcionCategoria'] ? 'Mayor' : '';
	                        $menor = $categoria['idOpcionMenor'] == $opcion['idOpcionCategoria'] ? 'Menor' : '';
	                        
	                        $params = array('module'=>'encuesta','controller'=>'opcion','action'=>'admin','op'=>$opcion['idOpcionCategoria']);
	                        $urlOpcionAdmin = $this->url($params,null,true);
	                        ?>
	                        <tr>
	                            <td><?php echo $opcion["nombreOpcion"]; ?></td>
	                            <td><?php echo $opcion["orden"].'°'; ?></td>
	                            <td><?php echo $valor; ?></td>
	                            <td><?php echo $mayor; ?></td>
	                            <td><?php echo $menor; ?></td>
	                            <td>
	                            	<a href="<?php echo $urlOpcionAdmin; ?>" class="btn btn-link">
	                            		<i class="fa fa-cogs"></i> Configurar
	                            	</a>
	                            </td>
	                            <td><?php echo $opcion["fecha"]; ?></td>
	                        </tr>
	                        <?php endforeach ?>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>
