<?php
    $rol = $this->rol;
    $urlRoles = $this->url(array('controller' => 'rol', 'action' => 'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Editando Rol: <strong><?php echo $rol['rol']; ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlRoles; ?>">
						<i class="fa fa-chevron-left"></i> Regresar a Roles
					</a>
				</div>
				<hr />
				<div>
					<form action="" method="post" enctype="application/x-www-form-urlencoded" class="form-horizontal">
						<div class="form-group">
							<label for="rol" class="col-md-2 control-label">Rol</label>
							<div class="col-md-10">
								<input name="rol" type="text" class="form-control" autofocus="autofocus" value="<?php echo $rol['rol'] ?>" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button class="btn btn-warning">
    								<i class="fa fa-refresh"></i> Actualizar
    							</button>
							</div>
						</div>
						
					</form>
				</div>
			</div>
		</div>
	</div>
</div>