<?php
    $roles = $this->roles;
    $urlDashboard = $this->url(array('controller'=>'dashboard', 'action' => 'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h5 class="panel-title">Roles en el Sistema</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlDashboard; ?>">
						<i class="fa fa-chevron-left"></i> Dashboard
					</a>
				</div>
				<hr />
				<div>
					<table class="table table striped table-condensed">
						<thead>
							<tr>
								<th>Rol</th>
								<th>Editar</th>
								<th>Creacion</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($roles as $role): 
							 $urlEdit = $this->url(array('controller'=>'rol', 'action'=>'edit', 'rol'=>$role['idRol']),null,true);
							?>
							<tr>
								<td><?php echo $role['rol']; ?></td>
								<td>
									<a class="btn btn-link" href="<?php echo $urlEdit; ?>">
										<i class="fa fa-pencil"></i> Editar
									</a>
								</td>
								<td><?php echo $role['creacion']; ?></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>