<?php 
    $modulo = "deportes";
    $params = array('module'=>$modulo,'controller'=>'dashboard','action'=>'index');
    $urlDashboardIndex = $this->url($params,null,true);
    $params = array('module'=>$modulo,'controller'=>'dashboard','action'=>'actions');
    $urlDashboardActions = $this->url($params,null,true);
    
    $params = array('module'=>$modulo,'controller'=>'concursante','action'=>'adminest');
    $urlEConcursante = $this->url($params,null,true);
    
    $params = array('module'=>$modulo,'controller'=>'equipo','action'=>'adminest');
    $urlEEquipo = $this->url($params,null,true);
    
    $params = array('module'=>$modulo,'controller'=>'competencia','action'=>'adminest');
    $urlECompetencia = $this->url($params,null,true);
    
?>
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <!-- 
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Busqueda...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
            </li>
             -->
            <li>
                <a href="<?php echo $urlDashboardIndex; ?>">
                	<i class="fa fa-dashboard fa-fw"></i> Dashboard
                </a>
            </li>
            <li>
                <a href="<?php echo $urlDashboardActions; ?>">
                	<i class="fa fa-cubes fa-fw"></i> Acciones
               	</a>
            </li>
            <li>
                <a href="#">
                	<i class="fa fa-wrench fa-fw"></i> Config Sistema<span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="<?php echo $urlEConcursante; ?>"><i class="fa fa-user"></i> Estatus Concursante</a>
                    </li>
                    <li>
                        <a href="<?php echo $urlEEquipo; ?>"><i class="fa fa-users"></i> Estatus Equipo</a>
                    </li>
                    <li>
                        <a href="<?php echo $urlECompetencia; ?>"><i class="fa fa-arrow-up"></i> Estatus Competencia</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->