<?php

    $clasificaciones = $this->clasificaciones;
    
    $formulario = $this->formulario;
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
    
    $params = array("module"=>"biblioteca","controller"=>"clasificacion","action"=>"index");
    $urlClasificaciones = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Edición de Clasificaciones</h5>
			</div>
			<div class="panel-body">
			    <div>
                    <a class="btn btn-info" href="<?php echo $urlClasificaciones; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Clasificaciones
                    </a><br />
                    <?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                       <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <br />
                    <?php } ?>
                    
                </div>
                <hr />
                <div >
                 	<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                 	
                 		<div class="form-group">
                 			<label for="clasificacion" class="control-label col-md-2"> Clasificación</label>
                 			<div class="col-md-5">
								<input name="clasificacion" type="text" class="form-control" value="<?php echo $clasificaciones['clasificacion']?>" />
							</div>
                 		</div>
                 		
                 		<div class="form-group">
                 			<label for="descripcion" class="control-label col-md-2"> Descripción</label>
                 			<div class="col-md-5">
								<input name="descripcion" type="text" class="form-control"  value="<?php echo $clasificaciones['descripcion']?>"/>
							</div>
                 		</div>
                 		
                 		<div class="form-group">
                 			<label for="codigo" class="control-label col-md-2"> Código</label>
                 			<div class="col-md-5">
								<input name="codigo" type="text" class="form-control" value="<?php echo $clasificaciones['codigo']?>" />
							</div>
                 		</div>
                 		
                 		<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-warning" type="submit">
									<i class="fa fa-refresh"></i> Actualizar Clasificación
								</button>
							</div>
						</div>
                 	</form>
                </div>
			</div>
		</div>
	</div>
</div>