<?php
    $clasificaciones = $this->clasificaciones;
    
    $params = array("module"=>"biblioteca","controller"=>"clasificacion","action"=>"alta");
    $urlAltaClasificacion = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Clasificaciones Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaClasificacion; ?>">
			            <i class="fa fa-plus"></i> Nueva Clasificación
			        </a>
			    </div>
			    <hr />
			    <div>
			    <?php if(false){?>
			        <table class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Clasificación</th>
			                    <th>Descripción</th>
			                     <th>Código</th>
			                    <th>Creación</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($clasificaciones as $clasificacion) :
			                $urlAdminClasificacion = $this->url(array('module'=>'biblioteca','controller'=>'clasificacion','action'=>'admin','cla'=>$clasificacion['clasificacion']['idClasificacion']));
   			                ?>
			                <tr>
			                    <td>
			                    	<?php echo $clasificacion["clasificacion"]; ?>
			                    	<a class="btn btn-link" href="<?php echo $urlAdminClasificacion; ?>">
										<i class="fa fa-cogs"></i> 
									</a>
			                    </td>
			                    <td><?php echo $clasificacion["descripcion"]; ?></td>
			                    <td><?php echo $clasificacion["codigo"]; ?></td>
			                    <td><?php echo $clasificacion["creacion"]; ?></td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			        	<?php } ?>
			        	
			        		    <?php if(true){?>
			        <table id="tClasificacion" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Clasificación</th>
			                    <th>Descripción</th>
			                     <th>Código</th>
			                    <th>Creación</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($clasificaciones as $clasificacion) : 
			                $urlAdminClasificacion = $this->url(array('module'=>'biblioteca','controller'=>'clasificacion','action'=>'admin','clas'=>$clasificacion['clasificacion']['idClasificacion']));
			                ?>
			                <tr>
			                    <td>
			                   		 <?php echo $clasificacion["clasificacion"]; ?>
			                   		 <a class="btn btn-link" href="<?php echo $urlAdminClasificacion; ?>">
										<i class="fa fa-cog"></i> 
									</a>
			                    </td>
			                    <td><?php echo $clasificacion["descripcion"]; ?></td>
			                    <td><?php echo $clasificacion["codigo"]; ?></td>
			                    <td><?php echo $clasificacion["creacion"]; ?></td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			        	<?php } ?>
			    </div>
			</div>
		</div>
	</div>
</div>
<script>

	$().ready(function(){
		console.log("jQuery Activo!!");

		$("#tClasificacion").DataTable();
		
	});
		
</script>