<?php
    $clasification = $this->clasificaciones;
    
    $params = array("module"=>"biblioteca","controller"=>"clasificacion","action"=>"alta");
    $urlAltaClasificacion = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Clasificaciones Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaClasificacion; ?>">
			            <i class="fa fa-plus"></i> Nueva Clasificación
			        </a>
			    </div>
			    <hr />
			    <div>
			    	
			        <table id="tClasificacion" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Clasificación</th>
			                    <th>Descripción</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                    <th>Editar</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($clasification as $clasificacion) : 
			              //  print_r($clasificacion); print_r('<br> / <br> /');
			                		$urlAdminClasificacion = $this->url(array('module'=>'biblioteca','controller'=>'clasificacion','action'=>'admin','cfn'=>$clasificacion['idClasificacion']));
			                ?>
			                <tr>
			                    <td><?php echo $clasificacion["clasificacion"]; ?></td>
			                    <td><?php echo $clasificacion["descripcion"]; ?></td>
			                    <td><?php echo $clasificacion["codigo"]; ?></td>
			                    <td><?php echo $clasificacion["creacion"]; ?></td>
			                    <td>
			                    	 <a class="btn btn-link" href="<?php echo $urlAdminClasificacion; ?>">
										<i class="fa fa-edit"></i> 
									</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			        
			    </div>
			</div>
		</div>
	</div>
</div>
<script>

	$().ready(function(){
		console.log("jQuery Activo!!");

		$("#tClasificacion").DataTable();
		
	});
		
</script>