<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <meta name="author" content="Hector Rodriguez">
        <meta name="description" content="">
        
        <?php $public = $this->baseUrl()."/public" ?>
        
        <link rel="shortcut icon" href="<?php echo $public; ?>/images/favicon.ico">
        <link rel="apple-touch-icon" href="<?php echo $public; ?>/images/icono.png">
		
		<title>Colegio Sagrado Corazón México</title>
		<link rel="stylesheet" href="<?php echo $public; ?>/lib/bootstrap/css/bootstrap.min.css ">
		<!-- Theme CSS -->
		<link href="<?php echo $public ?>/css/sagrado.css" rel="stylesheet">
		<!-- Custom Fonts -->
		<link href="<?php echo $public ?>/lib/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    	<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    	<script type="text/javascript" src="<?php echo $public ?>/lib/jquery/jquery.min.js"></script>
    	
    	<!-- jQuery DataTables -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-2.2.4/dt-1.10.13/r-2.1.1/datatables.min.css"/>
	</head>
	<body id="page-top" class="index">
		<?php echo $this->layout()->content; ?>
	</body>
	
	<script type="text/javascript" src="<?php echo $public ?>/lib/bootstrap/js/bootstrap.min.js"></script>
	<!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <!-- Theme JavaScript -->
    <script src="<?php echo $public ?>/js/freelancer.min.js"></script>
</html>