<?php ?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Alta de Evento</h5>
			</div>
			<div class="panel-body">
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<!-- NombreEvento -->
						<div class="form-group">
							<label class="control-label col-md-2" for="nombre">Nombre Evento: </label>
							<div class="col-md-5">
								<input id="nombre" class="form-control" name="nombre" type="text"  />
							</div>
						</div>
						<!-- LugarEvento -->
						<div class="form-group">
							<label class="control-label col-md-2" for="lugar">Lugar Evento: </label>
							<div class="col-md-5">
								<input id="lugar" class="form-control" name="lugar" type="text"  />
							</div>
						</div>
						<!-- InicioEvento -->
						<div class="form-group">
							<label class="control-label col-md-2" for="feInicio">Inicio Evento: </label>
							<div class="col-md-5">
								<input id="feInicio" class="form-control" name="feInicio" type="text"  />
							</div>
						</div>
						<!-- TerminoEvento -->
						<div class="form-group">
							<label class="control-label col-md-2" for="feTermino">Termino Evento: </label>
							<div class="col-md-5">
								<input id="feTermino" class="form-control" name="feTermino" type="text"  />
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-success" type="submit">
									<i class="fa fa-save"></i> Agregar Evento
								</button>
							</div>
						</div>
					</form>
				</div>
				
				<div>
					
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$().ready(function(){
		$("#feInicio").datepicker({
			changeMonth: true,
			changeYear: true,
			dateFormat: 'yy-mm-dd',
			minDate: 0,
			showAnim: 'drop'			
		});

		$("#feTermino").datepicker({
			changeMonth: true,
			changeYear: true,
			dateFormat: 'yy-mm-dd',
			minDate: 0,
			showAnim: 'drop'
		});
	});
</script>