<?php
    $recurso = $this->recurso;
    
    $estatusRecurso = $this->estatusRecurso;
    $materiales = $this->materiales;
    $colecciones = $this->colecciones;
    $clasificaciones = $this->clasificaciones;
    
    $urlRecursos = $this->url(array('module'=>'biblioteca', 'controller'=>'recurso', 'action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h5 class="panel-title">Edicion de Recurso</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlRecursos; ?>">
						<i class="fa fa-chevron-left"></i> Regresar a Recursos
					</a>
				</div>
				<hr />
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<div class="form-group">
							<label for="recurso" class="control-label col-md-2">Recurso: </label>
							<div class="col-md-5">
								<input name="recurso" type="text" class="form-control" value="<?php echo $recurso['recurso'] ?>" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="descripcion" class="control-label col-md-2">Descripcion recurso: </label>
							<div class="col-md-5">
								<input name="descripcion" type="text" class="form-control" value="<?php echo $recurso['descripcion'] ?>" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="idMaterial" class="control-label col-md-2">Material: </label>
							<div class="col-md-5">
								<select name="idMaterial" id="idMaterial" class="form-control">
									<option value="0">Seleccione Material</option>
									<?php foreach ($materiales as $material) : 
									   $seleccionado = $material['idMaterial'] == $recurso['idMaterial'] ? 'selected="selected"' : '' ;
									?>
									<option value="<?php echo $material['idMaterial']; ?>" <?php echo $seleccionado; ?> >
										<?php echo $material['material'] ?>
									</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="idColeccion" class="control-label col-md-2">Coleccion: </label>
							<div class="col-md-5">
								<select name="idColeccion" id="idColeccion" class="form-control">
									<option value="0">Seleccione Coleccion</option>
									<?php foreach ($colecciones as $coleccion) :
									$seleccionado = $coleccion['idColeccion'] == $recurso['idColeccion'] ? 'selected="selected"' : '' ;
									?>
									<option value="<?php echo $coleccion['idColeccion'] ?>" <?php echo $seleccionado; ?> >
										<?php echo $coleccion['coleccion'] ?>
									</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="idClasificacion" class="control-label col-md-2">Clasificacion:</label>
							<div class="col-md-5">
								<select name="idClasificacion" id="idClasificacion" class="form-control">
									<option value="0">Seleccione Clasificacion</option>
									<?php foreach ($clasificaciones as $clasificacion) : 
									$seleccionado = $clasificacion['idClasificacion'] == $recurso['idClasificacion'] ? 'selected="selected"' : '' ;
									?>
									<option value="<?php echo $clasificacion['idClasificacion'] ?>" <?php echo $seleccionado; ?> >
										<?php echo $clasificacion['clasificacion'] ?>
									</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="idEstatusRecurso" class="control-label col-md-2">Estatus de Recurso: </label>
							<div class="col-md-5">
								<select name="idEstatusRecurso" id="idEstatusRecurso" class="form-control">
									<option value="0">Seleccione Estatus de Recurso</option>
									<?php foreach ($estatusRecurso as $estatus) : 
									$seleccionado = $estatus['idEstatusRecurso'] == $recurso['idEstatusRecurso'] ? 'selected="selected"' : '' ;
									?>
									<option value="<?php echo $estatus['idEstatusRecurso']; ?>" <?php echo $seleccionado; ?> >
										<?php echo $estatus['estatusRecurso'] ?>
									</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="codBarrOrigen" class="control-label col-md-2">Codigo Barras:</label>
							<div class="col-md-5">
								<input id="codBarrOrigen" name="codBarrOrigen" type="text" class="form-control" autofocus="autofocus" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-warning" type="submit">
									<i class="fa fa-reload"></i> Actualizar Recurso
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>