<?php
    $materiales = $this->materiales;
    $colecciones = $this->colecciones;
    $clasificaciones = $this->clasificaciones;
    
	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
?>
<section class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4 class="panel-title"> Alta de Recurso</h4>
			</div>
			<div class="panel-body">
				<div>
					<?php if(!is_null($messageSuccess)){ ?>
    				<div class="alert alert-success" role="alert">
    					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    					  <span aria-hidden="true">&times;</span>
    					</button>
    					<?php echo $messageSuccess; ?>
    				</div>
    				<?php }elseif(!is_null($messageFail)){ ?>
    				<div class="alert alert-danger" role="alert">
    					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    					  <span aria-hidden="true">&times;</span>
    					</button>
    					<?php echo $messageFail; ?>
    				</div>
    				<?php } ?>
    				
				</div>
				<div>
					<form action="" class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<div class="form-group">
							<label for="titulo" class="control-label col-md-2">Titulo: </label>
							<div class="col-md-5">
								<input name="titulo" type="text" class="form-control" autofocus="autofocus" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="subtitulo" class="control-label col-md-2">Subtitulo: </label>
							<div class="col-md-5">
								<input name="subtitulo" type="text" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="material" class="control-label col-md-2">Material: </label>
							<div class="col-md-5">
								<select name="material" id="material" class="form-control">
									<option value="0">Seleccione Material</option>
									<?php foreach ($materiales as $material) : ?>
									<option value="<?php echo $material['idMaterial'] ?>"><?php echo $material['material'] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="coleccion" class="control-label col-md-2">Coleccion: </label>
							<div class="col-md-5">
								<select name="coleccion" id="coleccion" class="form-control">
									<option value="0">Seleccione Coleccion</option>
									<?php foreach ($colecciones as $coleccion) : ?>
									<option value="<?php echo $coleccion['idColeccion'] ?>"><?php echo $coleccion['coleccion'] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="clasificacion" class="control-label col-md-2">Clasificacion:</label>
							<div class="col-md-5">
								<select name="clasificacion" id="clasificacion" class="form-control">
									<option value="0">Seleccione Clasificacion</option>
									<?php foreach ($clasificaciones as $clasificacion) : ?>
									<option value="<?php echo $clasificacion['idClasificacion'] ?>"><?php echo $clasificacion['clasificacion'] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="barcodeOrigin" class="control-label col-md-2">Codigo Barras:</label>
							<div class="col-md-5">
								<input name="barcodeOrigin" type="text" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-success" type="submit">
									<i class="fa fa-save"></i> Guardar Recurso
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	$().ready(function(){
		
		var appname = "/colegio/biblioteca";
		var url = window.location.origin + appname;
		
		$('#tipoAutor').on('change', function () {
		  var valor = $(this).val();
		  console.log(valor);
		  
		  var urlAutor = url + '/json/';
		  
		  if(valor != 'PEN'){
		  	
		  	switch(valor) {
		  		case 'IND' : 
		  			urlAutor += "autoresi";
		  		break;
		  		case 'VAR' : 
		  			urlAutor += "autoresv";
		  		break;
		  	}
		  	
		  	console.log(urlAutor);
		  	
		  	$.ajax({
				url: urlAutor,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("#idAutor").empty();
					//$("#grado").append($("<option></option>").attr("value","0").text("Seleccione Grado Educativo"));
					
					$.each(data, function(i,item){//function(key,value)
						
						var nombre = "";
						
						switch(valor) {
					  		case 'IND' : 
					  			nombre = item.apellidos + " " + item.nombres;
					  		break;
					  		case 'VAR' : 
					  			nombre = item.autores;
					  		break;
					  	}
						
						
						$("#idAutor").append($("<option></option>").attr("value",item.idAutor).text(nombre));
					});
					//$("#grupo").empty();
				}
			});
		  }else {
		  	$("#idAutor").empty();
		  	$('#idAutor')
		 
		  	
		  }
		});
	
	});
</script>
