<?php 
	$formulario = $this->formulario;

	$messageSuccess = $this->messageSuccess;
	$messageFail = $this->messageFail;
?>
<section class="row">
	<div class="col-xs-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h4> Alta de Recurso</h4>
			</div>
			<div class="panel-body">
				<?php if(!is_null($messageSuccess)){ ?>
				<div class="alert alert-success" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageSuccess; ?>
				</div>
				<?php }elseif(!is_null($messageFail)){ ?>
				<div class="alert alert-danger" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<?php echo $messageFail; ?>
				</div>
				<?php } ?>
				<?php echo $formulario ?>
			</div>
		</div>
	</div>
</section>

<script>
	$().ready(function(){
		
		var appname = "/colegio/biblioteca";
		var url = window.location.origin + appname;
		
		$('#tipoAutor').on('change', function () {
		  var valor = $(this).val();
		  console.log(valor);
		  
		  var urlAutor = url + '/json/';
		  
		  if(valor != 'PEN'){
		  	
		  	switch(valor) {
		  		case 'IND' : 
		  			urlAutor += "autoresi";
		  		break;
		  		case 'VAR' : 
		  			urlAutor += "autoresv";
		  		break;
		  	}
		  	
		  	console.log(urlAutor);
		  	
		  	$.ajax({
				url: urlAutor,
				dataType: "json",
				success: function(data){
					console.dir(data);
					$("#idAutor").empty();
					//$("#grado").append($("<option></option>").attr("value","0").text("Seleccione Grado Educativo"));
					
					$.each(data, function(i,item){//function(key,value)
						
						var nombre = "";
						
						switch(valor) {
					  		case 'IND' : 
					  			nombre = item.apellidos + " " + item.nombres;
					  		break;
					  		case 'VAR' : 
					  			nombre = item.autores;
					  		break;
					  	}
						
						
						$("#idAutor").append($("<option></option>").attr("value",item.idAutor).text(nombre));
					});
					//$("#grupo").empty();
				}
			});
		  }else {
		  	$("#idAutor").empty();
		  	$('#idAutor')
		 
		  	
		  }
		});
	
	});
</script>
