<?php
    $recurso = $this->recurso;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Detalle del Recurso: <strong><?php echo $recurso['recurso']; ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div></div>
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Material</th>
								<th>Coleccion</th>
								<th>Clasificacion</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><?php echo $recurso['material'][''] ?></td>
								<td></td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>