<?php
    $subscripcion = $this->subscripcion;
    $tiposCodificacion = array(
        'NONE' => 'Sin Codificacion',
        'SHA1' => 'Codificacion SHA1',
        'MD5' => 'Codificacion MD5',
    );
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Cambiando contraseña de suscripción</h5>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<div class="form-group">
							<label for="password" class="control-label col-md-2">Password: </label>
							<div class="col-md-10">
    							<input name="password" type="text" class="form-control" value="<?php echo $subscripcion['password']; ?>" />
    						</div>
						</div>
						
						<div class="form-group">
							<label for="enctype" class="control-label col-md-2">Enc Type: </label>
							<div class="col-md-10">
    							<select name="enctype" id="" class="form-control">
    								<?php foreach ($tiposCodificacion as $k => $tCodif) : ?>
    								<option value="<?php echo $k; ?>"><?php echo $tCodif; ?></option>
    								<?php endforeach;  ?>
    							</select>
    						</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
    							<button class="btn btn-warning" type="submit">
    								<i class="fa fa-refresh"></i> Cambiar codificación
    							</button>
    						</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>