<?php
    $subscripciones = $this->subscripciones;
    $tiposConeccion = array(
        'O' => 'Operación',
        'Q' => 'Consulta',
    );
    
    $tiposCodificacion = array(
        'NONE' => 'Sin Codificacion',
        'SHA1' => 'Codificacion SHA1',
        'MD5' => 'Codificacion MD5',
    );
    
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Conectores a BD</h5>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>BD</th>
								<th>Tipo Conn</th>
								<th>Username</th>
								<th>Password</th>
								<th>Enc Type Pass</th>
								<th>Creación</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($subscripciones as $subscripcion) : 
							 $urlAddCodif = $this->url(array('controller'=>'subscripcion','action'=>'acodif', 'sub' => $subscripcion['idSubscripcion']),null,true);
							?>
							<tr>
								<td><?php echo $subscripcion['dbname']; ?></td>
								<td><?php echo $tiposConeccion[$subscripcion['tipo']]; ?></td>
								<td><?php echo $subscripcion['username']; ?></td>
								<td><?php echo $subscripcion['password']; ?></td>
								<td><?php echo $tiposCodificacion[$subscripcion['enctype']]; ?>
									<?php if($subscripcion['enctype'] == 'NONE'){ ?>
										<a class="btn btn-link" href="<?php echo $urlAddCodif ?>">
											<i class="fa fa-plus"></i> Agregar
										</a>
									<?php } ?>
									<?php if($subscripcion['enctype'] != 'NONE'){ ?>
										<a class="btn btn-link" href="#">
											<i class="fa fa-pencil"></i> Modificar
										</a>
									<?php } ?>
								</td>
								<td><?php echo $subscripcion['creacion']; ?></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>