<?php
    $usuarios = $this->usuarios;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Consulta de Usuarios</h5>
			</div>
			<div class="panel-body">
				<div>
					<form class="form-inline" method="post" enctype="application/x-www-form-urlencoded">
						<div class="form-group">
							<label for="tipo" class="col-md-2 control-label">Criterio: </label>
							
							<div class="col-md-4">
								<select name="tipo" class="form-control">
									<option value="0">Seleccione tipo</option>
									<option value="1">Nickname</option>
									<option value="2">Nombres</option>
								</select>
							</div>
							
							<div class="col-md-4">
								<input name="pattern" type="text" class="form-control" />
							</div>
							
							<div class="col-md-2">
								<button type="submit" class="btn btn-success">
									<i class="fa fa-search"></i> Buscar
								</button>
							</div>
						</div>
					</form>
				</div>
				<hr />
				<div>
					<?php if (!empty($usuarios)) { ?>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Tipo</th>
								<th>Nickname</th>
								<th>Nombre</th>
								<th>Fecha Alta</th>
								<th>Ver Estado</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($usuarios as $usuario) : 
							     $tipo = "";
                                 switch ($usuario['tipoUsuario']) {
                                     case 'AL': $tipo = 'Alumna'; break;
                                     case 'DO': $tipo = 'Docente'; break;
                                     case 'EX': $tipo = 'Ex-Alumna'; break;
							     }
							     $nombreCompleto = $usuario['apaterno'].' '.$usuario['amaterno'].', '.$usuario['nombres'];
							     $link = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'user','us' => $usuario['id']), null, true);
							?>
							<tr>
								<td><?php echo $tipo; ?></td>
								<td><?php echo $usuario['nickname']; ?></td>
								<td><?php echo $nombreCompleto; ?></td>
								<td><?php echo $usuario['creacion']; ?></td>
								<td>
									<a class="btn btn-link" href="<?php echo $link; ?>">
										<i class="fa fa-cogs"></i> Estado
									</a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php } else { ?>
					<p style="color: red;">
						<strong>No se encontraron usuarios.</strong>
					</p>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>