<?php
    $module = 'biblioteca';
    $usuarios = $this->usuarios;
    
    $urlAltaUsuario = $this->url(array('module'=>$module,'controller'=>'usuarios','action'=>'alta'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Consulta de Usuarios</h5>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-5">
						<a class="btn btn-success" href="<?php echo $urlAltaUsuario; ?>">
    						<i class="fa fa-plus"></i> Nuevo Usuario
    					</a>
					</div>
					<div class="col-md-7">
						<form class="form-inline" method="post" enctype="application/x-www-form-urlencoded">
        					<div class="form-group">
        						<label for="tipo">Tipo Usuario: </label>
        						<select name="tipo" class="form-control">
    								<option value="ST">Seleccione tipo</option>
    								<option value="AL">Alumna</option>
    								<option value="DO">Docente</option>
    								<option value="EX">ExAlumna</option>
    							</select>
        					</div>
        					
        					<div class="form-group">
        						<label for="pattern"></label>
        						<input name="pattern" type="text" class="form-control" placeholder="nickname, nombres, apellidos..." />
        					</div>
        					
        					<div class="form-group">
        						<button type="submit" class="btn btn-success">
    								<i class="fa fa-search"></i> Buscar
    							</button>
        					</div>
        				</form>
					</div>
				</div>
				<hr />
				<div>
					<?php if (!empty($usuarios)) { ?>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Tipo</th>
								<th>Nickname</th>
								<th>Nombre</th>
								<th>Fecha Alta</th>
								<th>Ver Estado</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($usuarios as $usuario) : 
			$urlAdminUsuario = $this->url(array('module'=>'biblioteca','controller'=>'usuarios','action'=>'edit','us'=>$usuarios['usuario']['idUsuario']));
							     $tipo = "";
                                 switch ($usuario['tipoUsuario']) {
                                     case 'AL': $tipo = 'Alumna'; break;
                                     case 'DO': $tipo = 'Docente'; break;
                                     case 'EX': $tipo = 'Ex-Alumna'; break;
							     }
							     $nombreCompleto = $usuario['apaterno'].' '.$usuario['amaterno'].', '.$usuario['nombres'];
							     $link = $this->url(array('module'=>'biblioteca','controller'=>'prestamo','action'=>'user','us' => $usuario['id']), null, true);
							?>
							<tr>
								<td><?php echo $tipo; ?></td>
								<td>
									<?php echo $usuario['nickname']; ?>
									<a class="btn btn-link" href="<?php echo $urlAdminUsuario?>">
										<i class="fa fa-cog"></i> 
									</a>
								</td>
								<td><?php echo $nombreCompleto; ?></td>
								<td><?php echo $usuario['creacion']; ?></td>
								<td>
									<a class="btn btn-link" href="<?php echo $link; ?>">
										<i class="fa fa-cogs"></i> Estado
									</a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php } else { ?>
					<p style="color: red;">
						<strong>No se encontraron usuarios.</strong>
					</p>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>