<?php
    $usuario = $this->usuario;
    
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Perfil de Usuario: <strong><?php echo $usuario['apaterno'].' '.$usuario['amaterno'].', '.$usuario['nombres'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<div>
					
				</div>
			</div>
		</div>
	</div>
</div>