<?php 
    $nivel = $this->nivel;
    $grados = $this->grados;
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	            <h5 class="panel-title">Grados Escolares del Nivel: <strong><?php echo $nivel['nivelEducativo'] ?></strong></h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-info" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"nivel","action"=>"index"),null,true) ?>">
	                    <span class="fa fa-arrow-circle-left"></span> Regresar a los Niveles
	                </a>
	                
	                <a class="btn btn-success" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"alta","idNivel"=>$nivel['idNivelEducativo']),null,true) ?>">
	                    <span class="fa fa-plus-circle"></span> Agregar Grado
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-striped table-bordered">
	                    <thead>
	                        <tr>
	                            <th>Grado</th>
	                            <th>Descripción</th>
	                            <th>Configuración</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <?php foreach ($grados as $grado) : ?>
	                        <tr>
	                            <td><?php echo $grado['gradoEducativo']; ?></td>
	                            <td><?php echo $grado['descripcion']; ?></td>
	                            <td>
	                                <a class="btn btn-warning btn-block" href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"grado","action"=>"admin","idGrado"=>$grado['idGradoEducativo']),null,true) ?>">
	                                    <span class="fa fa-cogs"></span> Configurar
	                                </a>
	                            </td>
	                        </tr>
	                        <?php endforeach ?>
	                    </tbody>
	                </table>
	            </div>
	        </div>
    	</div>
    </div>
</div>
