<?php
    $grado = $this->grado;
    $grupos = $this->grupos;
    
    $params = array("module"=>"encuesta","controller"=>"grado","action"=>"admin","gr"=>$grado['idGradoEducativo']);
    $urlAdminGrado = $this->url($params,null,true);
    
    $params = array("module"=>"encuesta","controller"=>"grupoe","action"=>"alta","gr"=>$grado['idGradoEducativo']);
    $urlAltaGrupo = $this->url($params,null,true);
    
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Grupos en el Grado: <strong><?php echo $grado['gradoEducativo'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlAdminGrado; ?>">
        				<span class="fa fa-arrow-circle-left"></span> Regresar al Grado: <strong><?php echo $grado['gradoEducativo']; ?></strong>
        			</a>
        			<a class="btn btn-success" href="<?php echo $urlAltaGrupo; ?>">
        				<span class="fa fa-plus"></span> Agregar Grupo Escolar
        			</a>
				</div>
				<hr />
				<div>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Grupo Escolar</th>
								<th>Configurar</th>
								<th>Creacion</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($grupos as $grupo):
							     $params = array('module'=>'encuesta', 'controller'=>'grupoe', 'action'=>'admin','gpo'=>$grupo['idGrupoEscolar']);
							     $urlAdminGrupo = $this->url($params,null,true);
							?>
							<tr>
								<td><?php echo $grupo['grupoEscolar']; ?></td>
								<td>
									<a class="btn btn-link" href="<?php echo $urlAdminGrupo; ?>">
										<i class="fa fa-cog"></i> Configurar
									</a>
								</td>
								<td><?php echo $grupo['creacion'] ?></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>