<?php
    $usuarios = $this->usuarios;
    $tipos = $this->tiposEquipos;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Restaurar Info Base</h5>
			</div>
			<div class="panel-body">
				<div>
					<div class="form-horizontal">
						<div class="form-group">
							<label for="usuario" class="control-label col-md-2">Usuario: </label>
							<div class="col-md-10">
								<select id="usuario" name="usuario" class="form-control" >
									<option value="0">Seleccione Usuario</option>
									<?php foreach ($usuarios as $usuario): ?>
									<option value="<?php echo $usuario["id"] ?>"><?php echo $usuario["usuario"] ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="ubicacion" class="control-label col-md-2">Ubicacion: </label>
							<div class="col-md-10">
								<select id="ubicacion" name="ubicacion" class="form-control">
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<button id="btnQuery" class="btn btn-success hidden" >
									<i class="fa fa-search"></i> Buscar Equipos
								</button>
							</div>
						</div>
					</div>
				</div>
				<hr />
				<div>
					<table id="tableRes" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Equipo</th>
								<th>NumSerie</th>
								<th>Detalles</th>
								<th>Tipo</th>
								<th>Asignar</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Message Config -->
<div class="modal fade" id="msgConfirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title">Confirmar Re Asignacion.</h4>
			</div>
			<div class="modal-body">
				<p>El equipo: <strong><span id="equipo"></span></strong> se reasignara con el tipo: <strong><span id="tipo"></span></strong>.</p>
				<p>Se eliminara este registro del antiguo esquema y se agregara al nuevo.</p>
				<p>Esta operacion es irreversible</p>
			</div>
			<div class="modal-footer">
				<button id="finalConfirm" type="button" class="btn btn-success" data-dismiss="modal">
					<span class="glyphicon glyphicon-random"></span> Re Asignar Equipo
				</button>
				<button type="button" class="btn btn-danger" data-dismiss="modal">
					<span class="glyphicon glyphicon-close"></span> Cancelar
				</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$().ready(function(){
		var appname = "/colegio/soporte";
        var url = window.location.origin + appname;
		var equipos = null;
		
		var idEquipo = null;
		var idTipo = null;
		var idUsuario = null;
		var idUbicacion = null;
        
		$("#usuario").on('change', function(){
			var usuario = $(this).val();
			idUsuario = usuario;
			//console.log(usuario);
			// LLamar las ubicaciones del usuario: usuario ubicaciones usrubs
			var urlQueryUbicaciones = url + "/json/usrubs/us/"+usuario;

			console.log(urlQueryUbicaciones);

			$.ajax({
                url: urlQueryUbicaciones,
                dataType: "json",
                success: function(data){
                    //console.dir(data);
                    $("#ubicacion").empty();
                    $("#ubicacion").append($("<option></option>").attr("value","0").text("Seleccione Ubicacion"));
                    $.each(data, function(i,item){//function(key,value)
                        $("#ubicacion").append($("<option></option>").attr("value",data[i].id).text(data[i].ubicacion));
                    });
                    //$("#grupo").empty();

                    
                }
            });
		});

		$("#ubicacion").on('change', function(){
			var ubicacion = $(this).val();
			if(ubicacion != 0){
				$("#btnQuery").removeClass("hidden");
			}
		});

		$("#btnQuery").on('click', function(){
			//$("#btnQuery").addClass("hidden");

			var usuario = $("#usuario").val();
			var ubicacion = $("#ubicacion").val();
			idUbicacion = ubicacion;

			var urlQueryRes = url + "/json/queryres/us/"+usuario+"/ub/"+ubicacion;

			//console.log(urlQueryRes);
			

			$.ajax({
                url: urlQueryRes,
                dataType: "json",
                success: function(data){
                    //console.dir(data);
                    equipos = data;

                    var tbody = $("#tableRes").find('tbody');
                    tbody.empty();
                    
                    $.each(data, function(i,item){//function(key,value)

                    	var opts = $("<select></select>").
                        	attr("class","form-control").
                        	attr("equipo",item.idComputadora);
            	
                    	<?php foreach ($tipos as $tipo): ?>
                		opts.append(new Option("<?php echo $tipo["tipo"] ?>", "<?php echo $tipo["id"] ?>"));
                		<?php endforeach; ?>

                    	var btn = $("<button></button>")
                            .attr("class","btn btn-info equipo")
                            .attr("type","button")
                            .attr("equipo",item.idComputadora)
                            .attr("data-toggle","modal")
                            .attr("data-target","#msgConfirm")
                            .text("ReAsignar");

                        
                    	tbody.append($('<tr>').
                            append($('<td>').append(item.equipo)).
                            append($('<td>').append(item.noSerie)).
                            append($('<td>').append(item.sisOperativo+"-"+item.direccionIP)).
                            append($('<td>').append(opts)).
                            append($('<td>').append(btn))
                        );
                    });
                }
            });
			
		});

		$("#tableRes").on('click','button.equipo', function(){
			var equipo = $(this).attr("equipo");
			//console.dir(equipos);
			//console.log(equipo);
			var select = $("select[equipo='"+equipo+"'] option:selected");
			idTipo = select.val();
			var tipo = select.text();
			//console.log("Tipo: " + tipo);
			//console.dir(select);
			$("#tipo").text(tipo);
			$.each(equipos, function(i, item){
				if(item.idComputadora == equipo){
					$("#equipo").text(item.equipo);
					idEquipo = item.idComputadora;
					//$("#tipo").text($("select.equipo"));
				}
			});
		});

		$("button#finalConfirm").on('click', function(){
			console.log("Tipo: "+idTipo);
			console.log("Equipo: "+idEquipo);
			console.log("Usuario: "+idUsuario);
			console.log("Ubicacion: " + idUbicacion);

			var urlAsignacion = url + "/json/asigne/eq/"+idEquipo+"/us/"+idUsuario+"/ub/"+idUbicacion+"/tp/"+idTipo;
			console.log(urlAsignacion);

			$.ajax({
                url: urlAsignacion,
                dataType: "json",
                success: function(data){
                    //console.dir(data);
                }
            });
			
		});

		
	});
</script>