<?php
    $formulario = $this->formulario;
    $messageSuccess = $this->messageSuccess;
    $messageFail = $this->messageFail;
    
    $params = array("module"=>"biblioteca","controller"=>"editorial","action"=>"index");
    $urlEditoriales = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Alta de Editorial(es) en Biblioteca.</h5>
			</div>
			<div class="panel-body">
			    <div>
                    <a class="btn btn-info" href="<?php echo $urlEditoriales; ?>">
                        <i class="fa fa-arrow-circle-left"></i> Regresar a Editoriales
                    </a><br />
                    <?php if(!is_null($messageSuccess)){ ?>
                    <br />
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageSuccess; ?>
                    </div>
                    <?php }elseif(!is_null($messageFail)){ ?>
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <?php echo $messageFail; ?>
                    </div>
                    <br />
                    <?php } ?>
                </div>
                <hr />
                <div>
                    <form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
                 		<div class="form-group">
                 			<label for="editorial" class="control-label col-md-2"> Editorial</label>
                 			<div class="col-md-5">
								<input name="editorial" type="text" class="form-control" autofocus="autofocus" required="required" />
							</div>
                 		</div>
                 		<div class="form-group">
							<div class="col-md-offset-2 col-md-5">
								<button class="btn btn-success" type="submit">
									<i class="fa fa-save"></i> Guardar Editorial
								</button>
							</div>
						</div>
                 	</form>
                </div>
			</div>
		</div>
	</div>
</div>