<?php
	$editoriales = $this->editoriales;
	
	$params = array("module"=>"biblioteca","controller"=>"editorial","action"=>"alta");
	$urlAltaEditorial = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Autores Registrados en Biblioteca</h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-success" href="<?php echo $urlAltaEditorial; ?>">
						<i class="fa fa-plus"></i> Nueva Editorial
					</a>
				</div>
				<hr />
		
				
				<div>
					<table id="tEditorial" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Editorial</th>
								<th>Creación</th>
								<th>Editar</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($editoriales as $editorial) : 
							//print_r($editorial); print_r('<br /><br />');
							$urlAdminEditorial = $this->url(array('module'=>'biblioteca','controller'=>'editorial','action'=>'admin','ed'=>$editorial['idEditorial']));
							?>
								<tr>
									<td><?php echo $editorial["editorial"]; ?></td>
									<td><?php echo $editorial["creacion"]; ?></td>
									<td>
										<a class="btn btn-link" href="<?php echo $urlAdminEditorial; ?>">
										<i class="fa fa-edit"></i> 
									</a>
									</td>
									
									
								</tr>
							<?php endforeach; ?>	
							<!-- <?php 
							     $buscar = $_POST["palabra"]
							?> -->
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<script>

	$().ready(function(){
		console.log("jQuery Activo!!");

		$("#tEditorial").DataTable();

	});
		
</script>