<?php
	$niveles = $this->niveles;
	$params = array("module"=>"encuesta","controller"=>"nivel","action"=>"alta");
	$urlAltaNivel = $this->url($params,null,true);
	
?>
<div class="row">
    <div class="col-xs-12">
    	<div class="panel panel-info">
    		<div class="panel-heading">
	            <h5 class="panel-title"> <strong><i class="fa fa-list"></i></strong> Niveles Educativos</h5>
	        </div>
	        <div class="panel-body">
	            <div>
	                <a class="btn btn-success" href="<?php echo $urlAltaNivel; ?>">
	                    <i class="fa fa-plus-circle"></i> Nuevo Nivel
	                </a>
	            </div>
	            <hr />
	            <div>
	                <table class="table table-condensed table-striped">
	                    <thead>
	                        <tr>
	                            <th>Nivel</th>
	                            <th>Descripción</th>
	                            <th>Grados Educativos</th>
	                            <th>Creación</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                        <?php foreach ($niveles as $nivel) : 
	                           $params = array("module"=>"encuesta","controller"=>"grado","action"=>"grados","ni"=>$nivel['idNivelEducativo']);
	                           $urlGradosNivel = $this->url($params,null,true)
	                        ?>
	                        <tr>
	                            <td><?php echo $nivel['nivelEducativo']; ?></td>
	                            <td><?php echo $nivel['descripcion']; ?></td>
	                            <td>
	                                <a class="btn btn-info btn-block" href="<?php echo $urlGradosNivel; ?>">
	                                    <span class="fa fa-search"></span> Grados
	                                </a>
	                            </td>
	                            <td><?php echo $nivel['creacion'] ?></td>
	                        </tr>
	                        <?php endforeach ?>
	                    </tbody>
	                </table>
	            </div>
        	</div>
    	</div>
    </div>
</div>
