<?php
    $estatusConcursante = $this->estatusConcursante;
?>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Nuevo Integrante en Sistema</h5>
			</div>
			<div class="panel-body">
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
						<fieldset>
							<legend>Nuevo Integrante</legend>
							
							<div class="form-group">
    							<label for="idEstatusConcursante" class="control-label col-md-2">Nombres: </label>
    							<div class="col-md-10">
    								<select name="idEstatusConcursante" class="form-control">
    									<option value="0">Seleccione Estatus de Concursante...</option>
    									<?php foreach ($estatusConcursante as $estatusC) { ?>
    									<option value="<?php echo $estatusC['idEstatusConcursante'] ?>"><?php echo $estatusC['estatus'] ?></option>
    									<?php } ?>
    								</select>
    							</div>
    						</div>
							
							<div class="form-group">
    							<label for="nombres" class="control-label col-md-2">Nombres: </label>
    							<div class="col-md-10">
    								<input name="nombres" type="text" class="form-control" placeholder="Nombres..." />
    							</div>
    						</div>
    						
    						<div class="form-group">
    							<label for="apellidos" class="control-label col-md-2">Apellidos: </label>
    							<div class="col-md-10">
    								<input name="apellidos" type="text" class="form-control" placeholder="Apellidos..." />
    							</div>
    						</div>
    						    						
    						<div class="form-group">
    							<div class="col-md-offset-2 col-md-10">
    								<button class="btn btn-success" type="submit">
    									<i class="fa fa-save"></i> Guardar Integrante
    								</button>
    							</div>
    						</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>