<?php
    $estatusLibro = $this->estatusLibro;
    $prestamos = $this->prestamos;
    $message = $this->message;
    
?>
<div class="page-header">
	<h1>
		Prestamo
		<small>
			<i class="ace-icon fa fa-angle-double-right"></i>
			Información de prestamos
		</small>
	</h1>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-xs-12">
		<div class="row">
        	<div class="col-md-12">
        		<div class="panel panel-info">
        			<div class="panel-heading">
        				<h5 class="panel-title">Información de Préstamos</h5>
        			</div>
        			<div class="panel-body">
        				<div>
        					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded">
        						<fieldset>
                                    <legend>Consulta de Prestamos:</legend>
                                    <div class="form-group">
                                        <label class="col-xs-2" for="estatus">Tipo: </label>
                                        <div class="col-xs-4">
                                        	<select name="estatus" class="form-control" >
                                        	<option value="0">Seleccione Estatus</option>
                                        	<?php foreach ($estatusLibro as $estatusl) : ?>
                                            	<option value="<?php echo $estatusl['idEstatus'] ?>"><?php echo $estatusl['estatus'] ?></option>
                                            <?php endforeach; ?>
                                            </select>
                                        </div>
                                        <div class="col-xs-4">
                                            <button type="submit" class="btn btn-success">
                                                <i class="fa fa-search"></i> Consultar
                                            </button>
                                        </div>
                                    </div>
                                </fieldset>
        					</form>
        				</div>
        				<hr />
        				<div>
        					<?php if (!is_null($prestamos) && !empty($prestamos)) { ?>
        					<table class="table table-striped table-condensed">
        						<thead>
        							<tr>
        								<th>Nickname</th>
        								<th>Estatus</th>
        								<th>Nombres</th>
        								<th>Apellido Paterno</th>
        								<th>Apellido Materno</th>
        								<th>Creacion</th>
        							</tr>
        						</thead>
        						<tbody>
        							<?php foreach ($prestamos as $prestamo) : ?>
        							<tr>
        								<td><?php echo $prestamo;  ?></td>
        								<td><?php echo $prestamo;  ?></td>
        								<td><?php echo $prestamo;  ?></td>
        								<td><?php echo $prestamo;  ?></td>
        								<td><?php echo $prestamo;  ?></td>
        								<td><?php echo $prestamo;  ?></td>
        							</tr>
        							<?php endforeach; ?>
        						</tbody>
        					</table>
        					<?php }else { ?>
        					<p style="color: red;">
        						<?php echo $message; ?>
        					</p>
        					<?php } ?>
        				</div>
        			</div>
        		</div>
        	</div>
		</div>
	</div>
</div>