<?php
    $evento = $this->evento;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Registro de Asistente a Evento: <strong><?php echo $evento['nombre'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<form class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded" >
						<div class="form-group">
							<label for="nombres" class="control-label col-md-2">Nombres: </label>
							<div class="col-md-6">
								<input id="nombres" type="text" name="nombres" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="apaterno" class="control-label col-md-2">Apellido Paterno: </label>
							<div class="col-md-6">
								<input id="apaterno" type="text" name="apaterno" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="amaterno" class="control-label col-md-2">Apellido Materno: </label>
							<div class="col-md-6">
								<input id="amaterno" type="text" name="amaterno" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="email" class="control-label col-md-2">E-Mail: </label>
							<div class="col-md-6">
								<input id="email" type="text" name="email" class="form-control" />
							</div>
						</div>
						
						<div class="form-group">
							<label for="mailist" class="control-label col-md-2">Suscribirse?: </label>
							<div class="col-md-1">
								<input id="mailist" type="checkbox" name="mailist" checked="checked" />
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-offset-2 col-md-6">
								<button type="submit" class="btn btn-success">
									<i class="fa fa-save"></i> Registrar Usuario
								</button>
							</div>
						</div>
					</form>
				</div>
				<div>
					
					<table id="table" class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombres</th>
								<th>Apellido Paterno</th>
								<th>Apellido Materno</th>
								<th>E-Mail</th>
								<th>Estatus</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$().ready(function(){
		var appname = "/colegio/evento";
        var url = window.location.origin + appname;
		
		
		$("input#nombres").on('blur', function(){
			var nombres = $(this).val();
			console.log(nombres);
			
			var urlQuery = encodeURI(url + "/json/findreg/ns/"+nombres);
			
			console.log(urlQuery);
			$.ajax({
                url: urlQuery,
                dataType: "json",
                success: function(data){
                    console.dir(data);
                    //$("#gradoR").empty();
                    //$("#gradoR").append($("<option></option>").attr("value","0").text("Seleccione Grado Educativo"));
                    //$.each(data, function(i,item){//function(key,value)
                    //    $("#gradoR").append($("<option></option>").attr("value",data[i].idGradoEducativo).text(data[i].gradoEducativo));
                    //});
                    //$("#grupo").empty();
                }
            });
			
		});

		$("input#apaterno").on('blur', function(){
			var apaterno = $(this).val();
			console.log(apaterno);
			
		});

		$("input#amaterno").on('blur', function(){
			var amaterno = $(this).val();
			console.log(amaterno);
			
		});
	});
</script>