<?php
    $evento = $this->evento;
    $asistentesConfirmados = $this->asistentesConfirmados;
    
    $params = array('module'=>'evento','controller'=>'dashboard','action'=>'actions');
    $urlDashboard = $this->url($params,null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Asistentes confirmados en evento: <strong><?php echo $evento['evento'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a href="<?php echo $urlDashboard; ?>" class="btn btn-info">
						<i class="fa fa-arrow-circle-left"></i> Regresar a Acciones
					</a>
				</div>
				<hr />
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nombres</th>
    							<th>A. Paterno</th>
    							<th>A. Materno</th>
    							<th>Evento</th>
    							<th>Sistema</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($asistentesConfirmados as $ac) : ?>
							<tr>
								<td><?php echo $ac["nombres"]; ?></td>
								<td><?php echo $ac["apaterno"]; ?></td>
								<td><?php echo $ac["amaterno"]; ?></td>
								<td><?php echo $ac["entrada"]; ?></td>
								<td><?php echo $ac["creacion"]; ?></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>