<?php
    $evento = $this->evento;
    $asistentesConfirmados = $this->asistentesConfirmados;
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Asistentes confirmados en evento: <strong><?php echo $evento['nombre'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<th>Nombres</th>
							<th>A. Paterno</th>
							<th>A. Materno</th>
							<th>Evento</th>
							<th>Sistema</th>
						</thead>
						<tbody>
							<?php foreach ($asistentesConfirmados as $ac) : ?>
							<tr>
								<td><?php echo $ac["nombres"]; ?></td>
								<td><?php echo $ac["apaterno"]; ?></td>
								<td><?php echo $ac["amaterno"]; ?></td>
								<td><?php echo $ac["entrada"]; ?></td>
								<td><?php echo $ac["creacion"]; ?></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>