<?php
    $temas = $this->temas;
    
    $params = array("module"=>"biblioteca","controller"=>"tema","action"=>"alta");
    $urlAltaTema = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Temas Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaTema; ?>">
			            <i class="fa fa-plus"></i> Nuevo Tema
			        </a>
			    </div>
			    <hr />
			    <div>
			        <table class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Tema</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($temas as $tema) : ?>
			                <tr>
			                    <td><?php echo $tema["tema"]; ?></td>
			                    <td><?php echo $tema["codigo"]; ?></td>
			                    <td><?php echo $tema["creacion"]; ?></td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
</div>