<?php
    $temas = $this->temas;
    
    $params = array("module"=>"biblioteca","controller"=>"tema","action"=>"alta");
    $urlAltaTema = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Temas Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaTema; ?>">
			            <i class="fa fa-plus"></i> Nuevo Tema
			        </a>
			    </div>
			    <hr />
			    <div>
			 
			        <table id="tTema" class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Tema</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                    <th>Editar</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($temas as $tema) :
			                  $urlAdminTema = $this->url(array('module'=>'biblioteca','controller'=>'tema','action'=>'admin','tm'=>$tema['idTema']));
			                ?>
			                <tr>
			                    <td><?php echo $tema["tema"]; ?></td>
			                    <td><?php echo $tema["descripcion"]; ?></td>
			                    <td><?php echo $tema["creacion"]; ?></td>
			                    <td>
			                    	 <a class="btn btn-link" href="<?php echo $urlAdminTema; ?>">
										<i class="fa fa-edit"></i> 
									</a>
			                    </td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			        	
			    </div>
			</div>
		</div>
	</div>
</div>

<script>

	$().ready(function(){
		//console.log("jQuery Activo!!");

		$("#tTema").DataTable();
		
	});
		
</script>