<?php
    $recurso = $this->recurso;
    $ejemplares = $this->ejemplares;
    $urlRecurso = $this->url(array('module'=>'biblioteca','controller'=>'recurso','action'=>'index','rc'=>$recurso['idRecurso']),null,true);
    $urlAltaEjemplarARecurso = $this->url(array('module'=>'biblioteca','controller'=>'ejemplar','action'=>'alta','rc'=>$recurso['idRecurso']),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Ejemplares de Recurso:<strong><?php echo $recurso['titulo'].', '.$recurso['subtitulo'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a href="<?php echo $urlRecurso; ?>" class="btn btn-info">
						<i class="fa fa-chevron-left"></i> Volver a Recurso
					</a>
					<a href="<?php echo $urlAltaEjemplarARecurso; ?>" class="btn btn-success">
						<i class="fa fa-plus"></i> Alta de Ejemplar en el Recurso.
					</a>
				</div>
				<hr />
				<div>
					<?php if (!empty($ejemplares)) { ?>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Ejemplar</th>
								<th>Editorial</th>
								<th>Pais</th>
								<th>Idioma</th>
								<th>Copias</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($ejemplares as $ejemplar): ?>
							<tr>
								<td><?php echo $ejemplar; ?></td>
								<td><?php echo $ejemplar['editorial']['editorial']; ?></td>
								<td><?php echo $ejemplar['pais']['nombre']; ?></td>
								<td><?php echo $ejemplar['idioma']['idioma']; ?></td>
								
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php } else { ?>
					No hay ejemplares asociados al recurso.
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>