<?php
    $recurso = $this->recurso;
    $ejemplares = $this->ejemplares;
    $urlRecurso = $this->url(array('module'=>'biblioteca','controller'=>'recurso','action'=>'admin','rc'=>$recurso['idRecurso']),null,true);
    $urlAltaEjemplarARecurso = $this->url(array('module'=>'biblioteca','controller'=>'ejemplar','action'=>'alta','rc'=>$recurso['idRecurso']),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h5 class="panel-title">Ejemplares de Recurso:<strong><?php echo $recurso['titulo'].', '.$recurso['subtitulo'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a href="<?php echo $urlRecurso; ?>" class="btn btn-info">
						<i class="fa fa-chevron-left"></i> Volver a Recurso
					</a>
					<a href="<?php echo $urlAltaEjemplarARecurso; ?>" class="btn btn-success">
						<i class="fa fa-plus"></i> Alta de Ejemplar en el Recurso.
					</a>
				</div>
				<hr />
				<div>
					<?php if (!empty($ejemplares)) { ?>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Editorial</th>
								<th>Editar Ejemplar</th>
								<th>Tipo Libro</th>
								<th>Pais</th>
								<th>Idioma</th>
								<th>Copias</th>
								<th>Alta Copia</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($ejemplares as $ejemplar): 
							 //print_r($ejemplar); print_r('<br /><br />');
							 foreach ($ejemplar as $key => $value){
							     //print_r($key); print_r('-'); print_r($value); print_r('<br />');
							 }
							 $copias = count($ejemplar['inventario']);
							 
							 $urlEditEjemplar = $this->url(array('module'=>'biblioteca','controller'=>'ejemplar','action'=>'admin','ej'=>$ejemplar['ejemplar']['idEjemplar']),null,true);
							 $urlAddCopia = $this->url(array('module'=>'biblioteca','controller'=>'ejemplar','action'=>'acopia','ej'=>$ejemplar['ejemplar']['idEjemplar']),null,true);
							 
							?>
							<tr>
								<td><?php echo $ejemplar['editorial']['editorial']; ?></td>
								<td>
									<a href="<?php echo $urlEditEjemplar; ?>" class="btn btn-warning">
										<i class="fa fa-cogs"></i> Editar Ejemplar
									</a>
								</td>
								<td><?php echo $ejemplar['tipoLibro']['tipoLibro']; ?></td>
								<td><?php echo $ejemplar['pais']['nombre']; ?></td>
								<td><?php echo $ejemplar['idioma']['idioma']; ?></td>
								<td>
									<span class="badge">
										<?php echo $copias; ?>
									</span>
								</td>
								<td>
									<a href="<?php echo $urlAddCopia; ?>" class="btn btn-success">
										<i class="fa fa-plus"></i> Agregar Copia
									</a>
								</td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
					<?php } else { ?>
					No hay ejemplares asociados al recurso.
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>