<?php
    $module = "deportes";
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
                <span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url(array("module"=>"default", "controller"=>"index", "action"=>"index"),null,true); ?>">
                <i class="fa fa-home"></i> CSC México
            </a>
        </div>
        
        <div id="menu-nav-1" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#login">Login</a>
                </li>
                
                <li class="page-scroll">
					<a href="#resultados">Resultados</a>
				</li>
				
				<li class="page-scroll">
					<a href="#competencias">Competencias</a>
				</li>
				
				<li class="page-scroll">
					<a href="#soporte">Acerca de</a>
				</li>
            </ul>
        </div>
    </div>
</nav>

<header id="login">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Login <?php echo $this->message; ?> </h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <form class="form-horizontal" action="<?php echo $this->url(array("module"=>$module,"controller"=>"index","action"=>"login"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
                    <fieldset>
                        <legend>Acceso al Sistema:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="nickname">Usuario: </label>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" name="nickname" placeholder="Usuario..." autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="password">Password: </label>
                            <div class="col-xs-10">
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    Acceder
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="col-sm-2"></div>
        </div>
    </div>
</header>

<section id="resultados">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Resultados</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</section>

<section id="competencias">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Competencias</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</section>

<section id="soporte">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Acerca de</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</section>

<footer class="text-center">
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Plataforma de Gestión de Eventos By Zazil Consultores S.A. de C.V. 2016 - 2017
                </div>
            </div>
        </div>
    </div>
</footer>