<?php
    $consultaActiva = true;
    $loginActivo = true;
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
                <span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url(array("module"=>"default", "controller"=>"index", "action"=>"index"),null,true); ?>">
                <i class="fa fa-home"></i> CSC México
            </a>
        </div>
        
        <div id="menu-nav-1" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#about">
                    	<i class="fa fa-star"></i> Acerca de
                    </a>
                </li>
                <?php if ($loginActivo) { ?>
				<li class="page-scroll">
					<a href="#login">
						<i class="fa fa-user"></i> Login
					</a>
				</li>
				<?php }  ?>
                <?php if ($consultaActiva) { ?>
				<li class="page-scroll">
					<a href="#consulta">
						<i class="fa fa-search"></i> Consulta
					</a>
				</li>
				<?php } ?>
            </ul>
        </div>
    </div>
</nav>

<header id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Sistema de Biblioteca</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
            	<p>
            		Consulta, Prestamos y Renovación de libros de biblioteca del Colegio Sagrado Corazón plantel CDMX.
            	</p>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</header>

<?php if ($loginActivo) { ?>
<section id="login">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Login</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-5">
				<form class="form-horizontal" action="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"index","action"=>"loginu"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
                    <fieldset>
                        <legend>Alumnas y Docentes:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="tipo">Tipo: </label>
                            <div class="col-xs-10">
                                <select name="tipo" class="form-control" >
                                	<option value="ST">Seleccione Tipo</option>
                                	<option value="AL">Alumna</option>
                                	<option value="DO">Docente</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-xs-2" for="nickname">Nickname: </label>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" name="nickname" placeholder="Nickname..." autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="password">Password: </label>
                            <div class="col-xs-10">
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    Acceder
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
			</div>
            <div class="col-sm-2">
            </div>
            <div class="col-sm-5">
            	<form class="form-horizontal" action="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"index","action"=>"loginb"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
                    <fieldset>
                        <legend>Bibliotecarios y Sistema:</legend>
                        
                        <div class="form-group">
                            <label class="col-xs-2" for="tipo">Tipo: </label>
                            <div class="col-xs-10">
                                <select name="tipo" class="form-control" >
                                	<option value="ST">Seleccione Tipo</option>
                                	<option value="AL">Bibliotecario</option>
                                	<option value="DO">Sistema</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-xs-2" for="nickname">Nickname: </label>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" name="nickname" placeholder="Nickname..." autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="password">Password: </label>
                            <div class="col-xs-10">
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    Acceder
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
		</div>
	</div>	
</section>
<?php } ?>

<?php if ($consultaActiva) { ?>
<section id="consulta">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Consulta de libros</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
		</div>
		<div class="row">
		</div>
	</div>	
</section>
<?php } ?>

<footer class="text-center">
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Plataforma de Gestión de Biblioteca By Zazil Consultores S.A. de C.V. 2016 - 2017
                </div>
            </div>
        </div>
    </div>
</footer>
