<?php
    $consultaActiva = true;
    $loginActivo = true;
    $errorMessage = $this->errorMessage;
    
    $materiales = $this->materiales;
    $colecciones = $this->colecciones;
    $clasificaciones = $this->clasificaciones;
    
    $resources = $this->recursos;
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
                <span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url(array("module"=>"default", "controller"=>"index", "action"=>"index"),null,true); ?>">
                <i class="fa fa-home"></i> CSC México
            </a>
        </div>
        
        <div id="menu-nav-1" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#about">
                    	<i class="fa fa-star"></i> Acerca de
                    </a>
                </li>
                <?php if ($consultaActiva) { ?>
				<li class="page-scroll">
					<a href="#consulta">
						<i class="fa fa-search"></i> Consulta
					</a>
				</li>
				<?php } ?>
                <?php if ($loginActivo) { ?>
				<li class="page-scroll">
					<a href="#login">
						<i class="fa fa-user"></i> Login
					</a>
				</li>
				<?php }  ?>
            </ul>
        </div>
    </div>
</nav>

<header id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Sistema de Biblioteca</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
            	<p>
            		Consulta, Prestamos y Renovación de libros de biblioteca del Colegio Sagrado Corazón plantel CDMX.
            	</p>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</header>

<?php if ($consultaActiva) { ?>
<section id="consulta">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Consulta de libros</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<form id="consultaEjemplares" class="form-horizontal" method="post" enctype="application/x-www-form-urlencoded" >
					<div class="input-group">
						<span class="input-group-addon">
							<input type="checkbox" id="cmaterial" aria-label="..." />
						</span>
						<label class="form-control" aria-label="...">Material</label>
					</div>
					<div class="input-group">
						<span class="input-group-addon">
							<input type="checkbox" id="ccoleccion" aria-label="..." />
						</span>
						<label class="form-control" aria-label="...">Colección</label>
					</div>
					<div class="input-group">
						<span class="input-group-addon">
							<input type="checkbox" id="cclasificacion" aria-label="..." />
						</span>
						<label class="form-control" aria-label="...">Clasificación</label>
					</div>
					
					<hr />
					
					<div class="form-group">
						<label for="titulo" class="col-md-2 control-label">Titulo:</label>
						<div class="col-md-10">
							<input id="titulo" name="titulo" type="text" class="form-control" />
						</div>
					</div>
					
					<div class="form-group">
						<label for="subtitulo" class="col-md-2 control-label">Subtitulo:</label>
						<div class="col-md-10">
							<input id="subtitulo" name="subtitulo" type="text" class="form-control" />
						</div>
					</div>
					
					<div id="containerMaterial" class="form-group hidden">
						<label for="material" class="col-md-2 control-label">Material:</label>
						<div class="col-md-10">
							<select name="idMaterial" id="material" class="form-control">
								<option value="0">Sin Material</option>							
								<?php foreach ($materiales as $material) : ?>
									<option value="<?php echo $material["idMaterial"]?>"><?php echo utf8_encode($material["material"]) ?>
										
			               			</option>
			               	    <?php endforeach; ?>
								

							</select>
						</div>
					</div>
					
					<div id="containerColeccion" class="form-group hidden">
						<label for="coleccion" class="col-md-2 control-label">Colección:</label>
						<div class="col-md-10">
							<select name="idColeccion" id="coleccion" class="form-control">
									<option value=0>Sin Coleccion</option>
								 <?php foreach ($colecciones as $coleccion) : ?>
								 
			                		 <option value="<?php echo $coleccion["idColeccion"]?>">
			                		 	<?php echo $coleccion["coleccion"]; ?>
			               			 </option>
			               		 <?php endforeach; ?>
			               	</select>
						</div>
					</div>
					
					<div id="containerClasificacion" class="form-group hidden">
						<label for="clasificacion" class="col-md-2 control-label">Clasificación:</label>
						<div class="col-md-10">
							<select name="idClasificacion" id="clasificacion" class="form-control">
									<option value=0>Sin Clasificación</option>
								<?php foreach ($clasificaciones as $clasificacion) : ?>
									<option value="<?php echo $clasificacion["idClasificacion"]?>"> 	
										<?php echo $clasificacion["clasificacion"]; ?>
									</option>
			                    <?php endforeach; ?>
			               		
							</select>
						</div>
					</div>
					
					    <div class="form-group">
                      <div class="col-xs-offset-2 col-xs-10">
                          <button id="btnConsultar" type="submit" class="btn btn-success">
                              <span class="glyphicon glyphicon-flash"></span> Consultar
                          </button>
                      </div>
                  </div>
				</form>
				<!-- Fin del formulario -->
		</div>
		<div class="row">
			<table class="table table-striped table-condensed">
	            <thead>
	                <tr>
	                    <th>Recurso</th>
	                    <th>Ejemplares</th>
	                    <th>Material</th>
	                    <th>Colección</th>
	                    <th>Clasificación</th>
	                </tr>
	            </thead>
	            <tbody>
	                <?php foreach ($resources as $recurso) : 
	                $nombreRecurso = strlen($recurso['recurso']['titulo']) > 35 ? substr($recurso['recurso']['titulo'], 0, 35) . ' ...' : $recurso['recurso']['titulo'];
	                //$urlAdminResource = $this->url(array('module'=>'biblioteca','controller'=>'recurso','action'=>'admin','re'=>$recurso['recurso']['idRecurso']));
	                //$urlEjemplares = $this->url(array('module'=>'biblioteca','controller'=>'ejemplar','action'=>'ejemplares','rc'=>$recurso['recurso']['idRecurso']));
	                ?>
	                <tr>
	                   <td>
	                   		<?php echo $nombreRecurso; ?>
	                   </td>
	                   <td>
	                   		Ejemplares
	                   </td>
	                   <td><?php echo $recurso["material"]["material"]; ?></td>
	                   <td><?php echo $recurso["coleccion"]["coleccion"]; ?></td>
	                   <td><?php echo $recurso["clasificacion"]["clasificacion"]; ?></td>
	                </tr>
	                 <?php endforeach; ?>
	            </tbody> 
	        </table>
		</div>
	</div>	
</section>
<?php } ?>

<?php if ($loginActivo) { ?>
<section id="login">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Login</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-5">
				<form class="form-horizontal" action="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"index","action"=>"loginu"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
                    <fieldset>
                        <legend>Alumnas y Docentes:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="tipo">Tipo: </label>
                            <div class="col-xs-10">
                                <select name="tipo" class="form-control" >
                                	<option value="ST">Seleccione Tipo</option>
                                	<option value="AL">Alumna</option>
                                	<option value="DO">Docente</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-xs-2" for="nickname">Nickname: </label>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" name="nickname" placeholder="Nickname..." autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="password">Password: </label>
                            <div class="col-xs-10">
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    Acceder
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
                <?php if (!is_null($errorMessage) || $errorMessage != "") { ?>
            	<p style="color: red;">
                	<strong><?php echo $errorMessage; ?></strong>
                </p>
            	<?php } ?>
			</div>
            <div class="col-sm-2">
            </div>
            <div class="col-sm-5">
            	<form class="form-horizontal" action="<?php echo $this->url(array("module"=>"biblioteca","controller"=>"index","action"=>"login"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
                    <fieldset>
                        <legend>Bibliotecarios y Sistema:</legend>
                        
                        <div class="form-group">
                            <label class="col-xs-2" for="tipo">Tipo: </label>
                            <div class="col-xs-10">
                                <select name="tipo" class="form-control" >
                                	<option value="ST">Seleccione Tipo</option>
                                	<option value="AL">Bibliotecario</option>
                                	<option value="DO">Sistema</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-xs-2" for="nickname">Nickname: </label>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" name="nickname" placeholder="Nickname..." autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="password">Password: </label>
                            <div class="col-xs-10">
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-offset-2 col-xs-10">
                                <button type="submit" class="btn btn-success">
                                    Acceder
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
		</div>
	</div>	
</section>
<?php } ?>


<footer class="text-center">
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Plataforma de Gestión de Biblioteca By Zazil Consultores S.A. de C.V. 2016 - 2017
                </div>
            </div>
        </div>
    </div>
</footer>

<script type="text/javascript">
	$().ready(function(){
		//console.log("jQuery Activo!!");
		var url = window.location.origin + "/colegio/";
		console.log(url);
		
		$('#cmaterial').change(function(){
			//console.log("checkbox checado!!");
			if(this.checked){
				//console.log("Checado");
				$("#containerMaterial").removeClass('hidden');
			}else{
				//console.log("No checado");
				$("#containerMaterial").addClass('hidden');
				$("#containerMaterial").val('0').change();
				$("#containerMaterial").find('option:first').attr('selected','selected').parent('select');
			}
			
		});
		
		$('#ccoleccion').change(function(){
			//console.log("checkbox checado!!");
			if(this.checked){
				//console.log("Checado");
				$("#containerColeccion").removeClass('hidden');
			}else{
				//console.log("No checado");
				$("#containerColeccion").addClass('hidden');
				$("#containerColeccion").val('0').change();
				$("#containerColeccion").find('option:first').attr('selected','selected').parent('select');
			}
			
		});
		
		$('#cclasificacion').change(function(){
			//console.log("checkbox checado!!");
			if(this.checked){
				//console.log("Checado");
				$("#containerClasificacion").removeClass('hidden');
			}else{
				//console.log("No checado");
				$("#containerClasificacion").addClass('hidden');
				$("#containerClasificacion").val('0').change();
				$("#containerClasificacion").val('0').change();
				$("#containerClasificacion").find('option:first').attr('selected','selected').parent('select');
			}
		});

		$('#consultaEjemplares').submit(function(event){
			console.log('En consulta Ejemplares');
			var titulo = $(this).find('#titulo').val();
			var subtitulo = $(this).find('#subtitulo').val();

			if(titulo == "" && subtitulo ==""){
				alert( "Ingrese un titulo o subtitulo de Ejemplar a buscar" );
				event.preventDefault();
			}else{
				$(this).submit();
			}
		});
});
</script>