<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"dashboard","action"=>"index"),null,true) ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
            	<a href="#"><i class="fa fa-th-large fa-fw"></i> Encuestas<span class="fa arrow"></span></a>
            	<ul class="nav nav-second-level">
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"categoria","action"=>"index"),null,true) ?>">
            				<i class="fa fa-list-ol"></i> Conjuntos Respuesta
            			</a>
            		</li>
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"encuesta","action"=>"index"),null,true) ?>">
            				<i class="fa fa-search"></i> Consultar Encuestas
            			</a>
            		</li>
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"encuesta","action"=>"alta"),null,true) ?>">
            				<i class="fa fa-plus-circle"></i> Nueva Encuesta
            			</a>
            		</li>
            	</ul>
            </li>
            
            <li>
            	<a href="#"><i class="fa fa-th-large fa-fw"></i> Encuestas Escolares<span class="fa arrow"></span></a>
            	<ul class="nav nav-second-level">
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"plan","action"=>"index"),null,true) ?>">
            				<i class="fa fa-search"></i> Planes Estudio
            			</a>
            		</li>
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"nivel","action"=>"index"),null,true) ?>">
            				<i class="fa fa-list-ul"></i> Niveles Educativos
            			</a>
            		</li>
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"docente","action"=>"index"),null,true) ?>">
            				<i class="fa fa-graduation-cap"></i> Docentes
            			</a>
            		</li>
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"evaluador","action"=>"index"),null,true) ?>">
            				<i class="fa fa-users"></i> Evaluadores
            			</a>
            		</li>
            		<li>
            			<a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"conjunto","action"=>"index"),null,true) ?>">
            				<i class="fa fa-list-alt"></i> Conjuntos de Evaluacion
            			</a>
            		</li>
            		<li>
                        <a href="<?php echo $this->url(array("module"=>"encuesta","controller"=>"resultado","action"=>"index"),null,true) ?>">
                            <i class="fa fa-list-alt"></i> Resultados Evaluacion
                        </a>
                    </li>
            	</ul>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>