<?php
    $organizacion = $this->organizacion;
    $modulos = $this->modulos;
    $urlDashboard = $this->url(array('controller'=>'dashboard', 'action'=>'index'),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Modulos de la Organizacion: <strong><?php echo $organizacion['nombre'] ?></strong> </h5>
			</div>
			<div class="panel-body">
				<div>
					<a class="btn btn-info" href="<?php echo $urlDashboard; ?>">
						<i class="fa fa-chevron-left"></i> Dashboard
					</a>
				</div>
				<hr />
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Modulo</th>
								<th>Estatus</th>
								<th>PDF Dir</th>
								<th>Image Dir</th>
								<th>QR Dir</th>
								<th>File Dir</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($modulos as $modulo) :
							     $estatus = $modulo['mod']['activo'] == 'S' ? 'Activo':'Inactivo';
							?>
							<tr>
								<td><?php echo $modulo['obj']['modulo']; ?></td>
								<td><?php echo $estatus; ?></td>
								<td><?php if ($modulo['mod']['pdf_dir'] != "") {
								    echo $modulo['mod']['pdf_dir'];
								}else{
								    $urlApdf = $this->url(array('controller'=>'module','action'=>'adir', 'md' => $modulo['obj']['idModulo'], 'te'=>'pdf'),null,true);
								    echo '<a class="btn btn-link" href="'.$urlApdf.'"><i class="fa fa-plus"></i> SetUp Dir</a>';
								} ?></td>
								<td><?php if ($modulo['mod']['image_dir'] != "") {
								    echo $modulo['mod']['image_dir'];
								}else{
								    $urlAimage = $this->url(array('controller'=>'module','action'=>'adir', 'md' => $modulo['obj']['idModulo'], 'te'=>'img'),null,true);
								    echo '<a class="btn btn-link" href="'.$urlAimage.'"><i class="fa fa-plus"></i> SetUp Dir</a>';
								} ?></td>
								<td><?php if ($modulo['mod']['qr_dir'] != "") {
								    echo $modulo['mod']['qr_dir'];
								}else{
								    $urlAqr = $this->url(array('controller'=>'module','action'=>'adir', 'md' => $modulo['obj']['idModulo'], 'te'=>'qr'),null,true);
								    echo '<a class="btn btn-link" href="'.$urlAqr.'" ><i class="fa fa-plus"></i> SetUp Dir</a>';
								} ?></td>
								<td><?php if ($modulo['mod']['file_dir'] != "") {
								    echo $modulo['mod']['file_dir'];
								}else{
								    $urlAfile = $this->url(array('controller'=>'module','action'=>'adir', 'md' => $modulo['obj']['idModulo'], 'te'=>'fe'),null,true);
								    echo '<a class="btn btn-link" href="'.$urlAfile.'" ><i class="fa fa-plus"></i> SetUp Dir</a>';
								} ?></td>
							</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>