<?php
    $conjuntos = $this->conjuntos;
?>
<section id="evaluaciones">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Conjuntos</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Creacion</th>
                            <th>Evaluadores</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($conjuntos as $conjunto) : 
                            $urlEvaluaciones = $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"evals","idConjunto"=>$conjunto["idConjuntoEvaluador"],"idEvaluacion"=>"3"),null,true);
                            ?>
                        <tr>
                            <td><?php echo $conjunto["nombre"] ?></td>
                            <td><?php echo $conjunto["creacion"] ?></td>
                            <td>
                                <a class="btn btn-link" href="<?php echo $urlEvaluaciones; ?>">
                                    <i class="fa fa-users"></i> Evaluadores
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>