<?php
    $conjunto = $this->conjunto;
    $evaluador = $this->evaluador;
    $evaluaciones = $this->evaluaciones;
    //print_r($evaluaciones);
?>
<section id="evaluadores">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Evaluaciones disponibles para: <?php echo $evaluador["apellidos"].", ".$evaluador["nombres"]; ?> </h3>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripcion</th>
                            <th>Evaluaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($evaluaciones as $evaluacion) : 
                            $params = array(
                                "module" => "encuesta",
                                "controller" => "index",
                                "action" => "asigns",
                                "conjunto" => $conjunto["idConjuntoEvaluador"],
                                "evaluador" => $evaluador["idEvaluador"],
                                "evaluacion" => $evaluacion["idEncuesta"]
                            );
                            $url = $this->url($params,null,true);
                            ?>
                        <tr>
                            <td><?php echo $evaluacion["nombre"] ?></td>
                            <td><?php echo $evaluacion["descripcion"] ?></td>
                            <td>
                                <a class="btn btn-link" href="<?php echo $url; ?>">
                                    <i class="fa fa-check-circle-o"></i> Consultar Evaluaciones.
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>