<?php
	$asignacion = $this->asignacion;
    $grupo = $this->grupo;
    $materia = $this->materia;
    $docente = $this->docente;
    
    $grado = $this->grado;
    $nivel = $this->nivel;
    
    $evaluador = $this->evaluador;
    
    $formulario = $this->formulario;
    $form = $this->form;
	
	$urlSurvey = $this->baseUrl()."/public/lib/survey-jquery/survey.jquery.min.js";
	$urlProcessForm = $this->baseUrl()."/public/js/helpers/processForm.js";
?>
<style type="text/css">
    .txtHelper{
        color: #ce1126;
    }
</style>
<section id="evaluaciones" evaluador="<?php echo $evaluador["idEvaluador"] ?>" asignacion="<?php echo $asignacion["idAsignacionGrupo"] ?>">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Materia: <span class="txtHelper"><?php echo $materia["materiaEscolar"] ?></span>  -  Docente: <span class="txtHelper"><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></span> </h3>
                <hr class="star-primary">
                <h5>Nivel: <span class="txtHelper"><?php echo $nivel->getNivel(); ?></span> Grado: <span class="txtHelper"><?php echo $grado->getGradoEducativo(); ?></span> Grupo: <span class="txtHelper"><?php echo $grupo->getGrupo(); ?></span> </h5>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <?php //echo $form; ?>
                <div id="surveyContainer"></div>
            </div>
        </div>
    </div>
</section>
<script src="<?php echo $urlSurvey; ?>" type="text/javascript"></script>
<script src="<?php echo $urlProcessForm; ?>" type="text/javascript"></script>