<?php
    $grupo = $this->grupo;
    $materia = $this->materia;
    $docente = $this->docente;
    
    $grado = $this->grado;
    $nivel = $this->nivel;
    
    $evaluador = $this->evaluador;
    
    $formulario = $this->formulario;
    $form = $this->form;
?>
<style type="text/css">
    .txtHelper{
        color: #ce1126;
    }
</style>
<section id="evaluaciones">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Materia: <span class="txtHelper"><?php echo $materia["materiaEscolar"] ?></span>  -  Docente: <span class="txtHelper"><?php echo $docente->getApellidos().", ".$docente->getNombres() ?></span> </h3>
                <hr class="star-primary">
                <h5>Nivel: <span class="txtHelper"><?php echo $nivel->getNivel(); ?></span> Grado: <span class="txtHelper"><?php echo $grado->getGradoEducativo(); ?></span> Grupo: <span class="txtHelper"><?php echo $grupo->getGrupo(); ?></span> </h5>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <?php echo $formulario; ?>
            </div>
        </div>
    </div>
</section>