<?php 
	$grupo = $this->grupo;
	$conjuntos = $this->conjuntos;
?>
<section id="evaluadores">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Evaluadores del grupo: <strong><?php echo $grupo->getGrupo(); ?></strong> </h3>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped table-condensed">
                	<thead>
                		<tr>
                			<th>Apellidos</th>
                			<th>Nombres</th>
                			<th>Evaluaciones</th>
                		</tr>
                	</thead>
                	<tbody>
                	    <?php foreach ($conjuntos as $index => $conjunto) :
                                $idConjunto = $index; 
                	               foreach ($conjunto as $key => $evaluador) :
                                       //print_r($evaluador);
                                       $params = array(
                                            "module" => "encuesta",
                                            "controller" => "index",
                                            "action" => "evaluaciones",
                                            "conjunto" => $idConjunto,
                                            "evaluador" => $evaluador["idEvaluador"]
                                       );
                                       $url = $this->url($params,null,TRUE);
                	        ?>
                		<tr>
                			<td><?php echo $evaluador["apellidos"]; ?></td>
                			<td><?php echo $evaluador["nombres"]; ?></td>
                			<td>
                			    <a class="btn btn-link" href="<?php echo $url; ?>">
                			        <i class="fa fa-check-circle-o"></i> Evaluaciones
                			    </a>
                			</td>
                		</tr>
                		<?php 
                		          endforeach;
                		      endforeach; ?>
                	</tbody>
                </table>
            </div>
        </div>
    </div>
</section>