    <?php
	$ciclosEscolares = $this->ciclosEscolares;
	$nivelesEscolares = $this->nivelesEscolares;
	//$niveles = array();
	$evaluaciones = array();
    $encuestasActivas = true;
    $consultaActiva = true;
?>
<!-- Navegacion  --> 
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
	<div class="container">
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-nav-1">
				<span class="sr-only">Activar Navegación</span> Menú <i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="<?php echo $this->url(array("module"=>"default", "controller"=>"index", "action"=>"index"),null,true); ?>">Colegio Sagrado Corazón</a>
		</div>
		
		<div id="menu-nav-1" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="hidden">
					<a href="#page-top"></a>
				</li>
				<li class="page-scroll">
					<a href="#login">Login</a>
				</li>
				<?php if ($encuestasActivas) { ?>
				<li class="page-scroll">
					<a href="#evaluaciones">Evaluaciones</a>
				</li>
				<?php }  ?>
				<?php if ($consultaActiva) { ?>
				<li class="page-scroll">
					<a href="#consulta">Consulta</a>
				</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</nav>

<header id="login">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Login</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				<form class="form-horizontal" action="<?php echo $this->url(array("module"=>"encuesta","controller"=>"index","action"=>"login"),null,true) ?>" method="post" enctype="application/x-www-form-urlencoded">
					<fieldset>
						<legend>Acceso al Sistema:</legend>
						<div class="form-group">
							<label class="col-xs-2" for="usuario">Usuario: </label>
							<div class="col-xs-10">
								<input type="text" class="form-control" name="usuario" placeholder="Usuario..." autofocus>
							</div>
						</div>
						<div class="form-group">
							<label class="col-xs-2" for="password">Password: </label>
							<div class="col-xs-10">
								<input type="password" class="form-control" name="password">
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-offset-2 col-xs-10">
								<button type="submit" class="btn btn-success">
									Acceder
								</button>
							</div>
						</div>
					</fieldset>
				</form>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</header>
<?php if ($encuestasActivas) { ?>
<section id="evaluaciones">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Evaluaciones</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				<div id="form-eval" class="form-horizontal">
					<fieldset>
						<legend>Realizar evaluación:</legend>
						<div class="form-group">
							<label class="col-xs-2" for="ciclo">Ciclo Escolar: </label>
							<div class="col-xs-10">
								<select id="ciclo" class="form-control" name="ciclo">
									<?php foreach ($ciclosEscolares as $cicloEscolar) : ?>
									<option <?php echo ($cicloEscolar["vigente"] == '1') ? 'selected="selected"' : '' ; ?> value="<?php echo $cicloEscolar["idCicloEscolar"] ?>"><?php echo $cicloEscolar["ciclo"] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-xs-2" for="nivel">Nivel: </label>
							<div class="col-xs-10">
								<select id="nivel" class="form-control" name="nivel">
									<option value="0">Seleccione Nivel Educativo</option>
									<?php foreach ($nivelesEscolares as $nivelEscolar) : ?>
										<option value="<?php echo $nivelEscolar->getIdNivel() ?>" > <?php echo $nivelEscolar->getNivel() ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-xs-2" for="grado">Grado: </label>
							<div class="col-xs-10">
								<select id="grado" class="form-control" name="grado">
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="col-xs-2" for="grupo">Grupo: </label>
							<div class="col-xs-10">
								<select id="grupo" class="form-control" name="grupo">
								</select>
							</div>
						</div>
					</fieldset>
				</div>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</section>
<?php } ?>

<?php if ($consultaActiva) { ?>
<section id="consulta">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Consulta</h2>
				<hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<div id="form-eval" class="form-horizontal">
                    <fieldset>
                        <legend>Resultados por Grupo:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="cicloR">Ciclo Escolar: </label>
                            <div class="col-xs-10">
                                <select id="cicloR" class="form-control" name="cicloR">
                                    <?php foreach ($ciclosEscolares as $cicloEscolar) : ?>
                                    <option <?php echo ($cicloEscolar["vigente"] == '1') ? 'selected="selected"' : '' ; ?> value="<?php echo $cicloEscolar["idCicloEscolar"] ?>"><?php echo $cicloEscolar["ciclo"] ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="nivelR">Nivel: </label>
                            <div class="col-xs-10">
                                <select id="nivelR" class="form-control" name="nivelR">
                                    <option value="0">Seleccione Nivel Educativo</option>
                                    <?php foreach ($nivelesEscolares as $nivelEscolar) : ?>
                                        <option value="<?php echo $nivelEscolar->getIdNivel() ?>" > <?php echo $nivelEscolar->getNivel() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="gradoR">Grado: </label>
                            <div class="col-xs-10">
                                <select id="gradoR" class="form-control" name="gradoR">
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="grupoR">Grupo: </label>
                            <div class="col-xs-10">
                                <select id="grupoR" class="form-control" name="grupoR">
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button id="btnQueryReports" class="btn btn-success hidden">
                                    <i class="fa fa-file-pdf-o"></i> Consultar Reportes
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </div>
			</div>
			
			<div class="col-sm-6">
			    <div id="form-eval" class="form-horizontal">
                    <fieldset>
                        <legend>Resultados por Docente-Materia:</legend>
                        <div class="form-group">
                            <label class="col-xs-2" for="cicloTwo">Ciclo Escolar: </label>
                            <div class="col-xs-10">
                                <select id="cicloR" class="form-control" name="cicloTwo">
                                    <?php foreach ($ciclosEscolares as $cicloEscolar) : ?>
                                    <option <?php echo ($cicloEscolar["vigente"] == '1') ? 'selected="selected"' : '' ; ?> value="<?php echo $cicloEscolar["idCicloEscolar"] ?>"><?php echo $cicloEscolar["ciclo"] ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="nivelTwo">Nivel: </label>
                            <div class="col-xs-10">
                                <select id="nivelTwo" class="form-control" name="nivelTwo">
                                    <option value="0">Seleccione Nivel Educativo</option>
                                    <?php foreach ($nivelesEscolares as $nivelEscolar) : ?>
                                        <option value="<?php echo $nivelEscolar->getIdNivel() ?>" > <?php echo $nivelEscolar->getNivel() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-2" for="gradoTwo">Grado: </label>
                            <div class="col-xs-10">
                                <select id="gradoTwo" class="form-control" name="gradoTwo">
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button id="btnQueryReportsTwo" class="btn btn-success hidden">
                                    <i class="fa fa-file-pdf-o"></i> Consultar Reportes
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </div>
			</div>
		</div>
		<div class="row">
		    <div class="col-sm-2"></div>
		    <div class="col-sm-8">
		        <div>
		            <table id="reports" class="table table-condensed table-striped">
		                <thead>
		                    <tr>
		                        <th>Reporte</th>
		                        <th>Tipo Reporte</th>
		                        <th>Descarga Archivo</th>
		                    </tr>
		                </thead>
		                <tbody></tbody>
		            </table>
		        </div>
		    </div>
		    <div class="col-sm-2"></div>
		</div>
	</div>	
</section>
<?php } ?>

<footer class="text-center">
	<div class="footer-below">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					Copyright &copy; Plataforma de Evaluaciones By Zazil Consultores 2016 - 2017
				</div>
			</div>
		</div>
	</div>
</footer>
<script src="<?php echo $this->baseUrl()."/public" ?>/js/helpers/homepage.js"></script>
<script src="<?php echo $this->baseUrl()."/public" ?>/js/helpers/consulta.js"></script>
<script src="<?php echo $this->baseUrl()."/public" ?>/js/helpers/consultaGenerales.js"></script>