<?php
    $module = 'biblioteca';
    $links = array(
        'udashboardIndex' => $this->url(array('module'=>$module,'controller'=>'udashboard','action'=>'index'),null,true),
        'uuserIndex' => $this->url(array('module'=>$module,'controller'=>'uusuario','action'=>'index'),null,true),
        'uuserSettings' => $this->url(array('module'=>$module,'controller'=>'uusuario','action'=>'configuracion'),null,true),
        'uuserLogout' => $this->url(array('module'=>$module,'controller'=>'uusuario','action'=>'logout'),null,true),
        'uprestamoIndex' => $this->url(array('module'=>$module,'controller'=>'uprestamo','action'=>'index'),null,true),
        'uprestamoMultas' => $this->url(array('module'=>$module,'controller'=>'uprestamo','action'=>'multa'),null,true),
        'uprestamoHistorial' => $this->url(array('module'=>$module,'controller'=>'uprestamo','action'=>'historial'),null,true),
        'uconsultaIndex' => $this->url(array('module'=>$module,'controller'=>'uconsulta','action'=>'index'),null,true),
        
    );
    
    $auth = Zend_Auth::getInstance();
    $identity = $auth->getIdentity();
    $usuario = $identity['user'];
?>

<div class="page-header">
	<h1>
		Dashboard
		<small>
			<i class="ace-icon fa fa-angle-double-right"></i>
			Información de cuenta
		</small>
	</h1>
</div><!-- /.page-header -->

<div class="row">
	<div class="col-xs-12">
		<div class="row">
        	<div class="col-md-12">
        		<div class="panel panel-info">
        			<div class="panel-heading">
        				<h5 class="panel-title">Informacion de Conexión</h5>
        			</div>
        			<div class="panel-body">
        				<div>
        					<?php //print_r($identity); ?>
        				</div>
        				<div>
        					<table class="table table-striped table-condensed">
        						<thead>
        							<tr>
        								<th>Nickname</th>
        								<th>Estatus</th>
        								<th>Nombres</th>
        								<th>Apellido Paterno</th>
        								<th>Apellido Materno</th>
        								<th>Creacion</th>
        							</tr>
        						</thead>
        						<tbody>
        							<tr>
        								<td><?php echo $usuario['nickname'];  ?></td>
        								<td><?php echo $usuario['estatus'];  ?></td>
        								<td><?php echo $usuario['nombres'];  ?></td>
        								<td><?php echo $usuario['apaterno'];  ?></td>
        								<td><?php echo $usuario['amaterno'];  ?></td>
        								<td><?php echo $usuario['creacion'];  ?></td>
        							</tr>
        						</tbody>
        					</table>
        				</div>
        			</div>
        		</div>
        	</div>
		</div>
	</div>
</div>
