<?php
    $auth = Zend_Auth::getInstance();
    $identity = $auth->getIdentity();
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title"></h5>
			</div>
			<div class="panel-body">
				<div>
					
				</div>
				<hr />
				<div>
					<table class="table table-striped table-condensed">
						<thead>
							<tr>
								<th>Nickname</th>
								<th>Estatus</th>
								<th>A Paterno</th>
								<th>A Materno</th>
								<th>Nombre</th>
								<th>Creacion</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><?php echo $identity['user']['nickname'] ?></td>
								<td><?php echo $identity['user']['estatus'] ?></td>
								<td><?php echo $identity['user']['apaterno'] ?></td>
								<td><?php echo $identity['user']['amaterno'] ?></td>
								<td><?php echo $identity['user']['nombres'] ?></td>
								<td><?php echo $identity['user']['creacion'] ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>