<?php
    $colecciones = $this->colecciones;
    
    $params = array("module"=>"biblioteca","controller"=>"coleccion","action"=>"alta");
    $urlAltaColeccion = $this->url($params,null,TRUE);
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h5 class="panel-title">Colecciones Registradas en Biblioteca</h5>
			</div>
			<div class="panel-body">
			    <div>
			        <a class="btn btn-success" href="<?php echo $urlAltaColeccion; ?>">
			            <i class="fa fa-plus"></i> Nueva Coleccion
			        </a>
			    </div>
			    <hr />
			    <div>
			        <table class="table table-striped table-condensed">
			            <thead>
			                <tr>
			                    <th>Colección</th>
			                    <th>Código</th>
			                    <th>Creación</th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php foreach ($colecciones as $coleccion) : ?>
			                <tr>
			                    <td><?php echo $coleccion["coleccion"]; ?></td>
			                    <td><?php echo $coleccion["codigo"]; ?></td>
			                    <td><?php echo $coleccion["creacion"]; ?></td>
			                </tr>
			                <?php endforeach; ?>
			            </tbody>
			        </table>
			    </div>
			</div>
		</div>
	</div>
</div>